(function(g){var window=this;'use strict';var D2=function(a){a.publish("cardstatechange",a.Dl()&&a.Vp()?1:0)},E2=function(a,b){var c=g.Qa(b),d=c?b:arguments;
for(c=c?0:1;c<d.length;c++){if(a==null)return;a=a[d[c]]}return a},Bdb=function(a){var b=g.Gm(a);
a=g.Jm(a);return new g.um(b.x,b.y,a.width,a.height)},Cdb=function(a,b,c){var d=d===void 0?{}:d;
var e;return e=g.Fs(a,b,function(){g.Gs(e);c.apply(a,arguments)},d)},H2=function(a){a=g.Ua(a);
delete F2[a];g.Og(F2)&&G2&&G2.stop()},Edb=function(){G2||(G2=new g.ip(function(){Ddb()},20));
var a=G2;a.isActive()||a.start()},Ddb=function(){var a=g.Xa();
g.Eg(F2,function(b){Fdb(b,a)});
g.Og(F2)||Edb()},I2=function(a,b,c,d){g.vp.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.B=a;this.N=b;this.duration=c;this.G=d;this.coords=[];this.progress=this.K=0;this.D=null},Fdb=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);a.progress>1&&(a.progress=1);a.K=1E3/(b-a.D);a.D=b;Gdb(a,a.progress);a.progress==1?(a.j=0,H2(a),a.onFinish(),a.Gs()):a.isPlaying()&&a.nO()},Gdb=function(a,b){typeof a.G==="function"&&(b=a.G(b));
a.coords=Array(a.B.length);for(var c=0;c<a.B.length;c++)a.coords[c]=(a.N[c]-a.B[c])*b+a.B[c]},Hdb=function(a,b){g.Th.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.K;this.state=b.j},J2=function(a,b,c,d,e){I2.call(this,b,c,d,e);
this.element=a},Idb=function(a,b,c,d,e){if(b.length!=2||c.length!=2)throw Error("Start and end points must be 2D");
J2.call(this,a,b,c,d,e)},Jdb=function(a){return Math.pow(a,3)},Kdb=function(a){return 3*a*a-2*a*a*a},Ldb=function(a){g.O.call(this);
this.B=a||window;this.j=[]},K2=function(a){return a.baseUrl||null},L2=function(a,b){return g.tn(g.Il(a,b),function(c){return!!c})},Mdb=function(a,b,c){function d(pa){var aa=pa.hovercardButton;
if(!aa)return null;aa=aa.subscribeButtonRenderer;if(!aa)return null;var R=f(aa.unsubscribedButtonText),T=f(aa.subscribedButtonText);if(aa.subscribed){var v=f(aa.subscriberCountWithUnsubscribeText);var V=f(aa.subscriberCountText)}else v=f(aa.subscriberCountText),V=f(aa.subscriberCountWithSubscribeText);var bb=null;if(pa.signinEndpoint){bb=E2(pa,"signinEndpoint","webNavigationEndpointData","url");if(!bb){var yb,nb;bb=(nb=g.Q((yb=aa.signInEndpoint)==null?void 0:yb.commandMetadata,g.w1))==null?void 0:
nb.url}if(!bb)return null}return R&&(T||bb)?{subscribed:aa.subscribed,subscribeText:R,subscribeCount:v,unsubscribeText:T,unsubscribeCount:V,enabled:aa.enabled,signinUrl:bb,classic:pa.useClassicSubscribeButton}:null}
function e(pa){if(pa){var aa=[],R=pa.videoId;R&&aa.push("v="+R);(R=pa.playlistId)&&aa.push("list="+R);(pa=pa.startTimeSeconds)&&aa.push("t="+pa);return"/watch?"+aa.join("&")}}
function f(pa){if(!pa)return null;var aa=pa.simpleText;return aa?aa:pa.runs?g.Il(pa.runs,function(R){return R.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var h=b.style,l=b.endpoint||{},m=null,n=null,p=!1,q=null,r=null,t=null,u=null,y=!1,A=null,C=null,F=null,H=null,N=null,M=null;if(h==="VIDEO")g.Q(l,g.Yx)?m=g.Q(l,g.Yx).url:(M=g.Q(l,g.OQ),m=e(M)),n=!1,q=a,b.thumbnailOverlays?(p=b.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,r=f(p.text),p=p.style==="LIVE"):r=f(b.videoDuration);else if(h==="PLAYLIST")g.Q(l,g.Yx)?m=g.Q(l,g.Yx).url:(M=g.Q(l,g.OQ),m=e(M)),n=!1,q=a,t=f(b.playlistLength);else if(h===
"CHANNEL"){if(y=E2(l,"browseEndpoint","browseId"))u=y,m="/channel/"+u;n=!1;q="new";(y=!!b.isSubscribe)?A=d(b):C=f(b.subscribersText)}else h==="WEBSITE"?((F=E2(l,"urlEndpoint","url"))&&(m=F),n=!0,q="new",F=b.icon.thumbnails[0].url):h==="CREATOR_MERCHANDISE"&&(b.productPrice&&(H=f(b.productPrice)),b.additionalFeesText&&(N=f(b.additionalFeesText)),(n=E2(l,"urlEndpoint","url"))&&(m=n),n=!0,q="new");a=E2(b,"title","accessibility","accessibilityData","label");var X=b.endpoint?b.endpoint.clickTrackingParams:
null,W="";if(b.metadata){var fa=f(b.metadata);fa&&(W=fa)}return{id:"element-"+c,type:h,title:f(b.title),metadata:W,callToAction:f(b.callToAction),iY:b.image,iconUrl:F,left:Number(b.left),width:Number(b.width),top:Number(b.top),aspectRatio:Number(b.aspectRatio),startMs:Math.floor(Number(b.startMs)),endMs:Math.floor(Number(b.endMs)),videoDuration:r,iG:p,playlistLength:t,channelId:u,subscribeButton:A,subscribersText:C,isSubscribe:y,targetUrl:m||null,I$:n,sessionData:X?{itct:X}:null,mfa:q,xE:a?a:null,
isPlaceholder:b.isPlaceholder,impressionUrls:L2(b.impressionUrls||[],K2),y$:L2(b.hovercardShowUrls||[],K2),clickUrls:L2(l.loggingUrls||[],K2),visualElement:g.Iw(b.trackingParams),productPrice:H,additionalFeesText:N,watchEndpoint:M||null}},Ndb=function(a,b){var c={startMs:Math.floor(Number(a.startMs)),
impressionUrls:L2(a.impressionUrls||[],K2),elements:L2(a.elements||[],function(d,e){return Mdb(b,d,e)})};
a.trackingParams&&(c.visualElement=g.Iw(a.trackingParams));return c},Odb=function(a){g.UX.call(this,a);
this.C=this.endscreen=null;this.j={};this.G={};this.D=this.B=null;this.N=[];this.W=!0;this.K=0;a=a.U();this.Z=g.oP(a)||g.qP(a);this.events=new g.PF(this);g.P(this,this.events);this.events.T(this.player,g.rE("creatorendscreen"),this.onCueRangeEnter);this.events.T(this.player,g.sE("creatorendscreen"),this.onCueRangeExit);this.events.T(this.player,"resize",this.jc);this.events.T(window,"focus",this.oda);this.load();var b=g.jh("STYLE");(g.ah("HEAD")[0]||document.body).appendChild(b);this.addOnDisposeCallback(function(){g.oh(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},Pdb=function(a){return a.player.getVideoData().Gf?"current":a.Z?"new":"current"},M2=function(a){return a.player.U().playerStyle==="creator-endscreen-editor"},Qdb=function(a){var b=a.player.getVideoData(),c=b.videoId;
a.C&&a.C.abort();c={method:"POST",onFinish:function(e){var f=a.C=null;e.status===200&&(e=e.responseText,e.substring(0,3)===")]}"&&(e=e.substring(3),f=JSON.parse(e),f=Ndb(f,Pdb(a))));N2(a,f)},
urlParams:{v:c},withCredentials:!0};a.Z&&(c.urlParams.ptype="embedded");var d=b.Gw;d&&(c.postParams={ad_tracking:d});if(b=g.ULa(b))if(b=g.Pf(b),b=g.Lf(b))a.C=g.Ir(b,c)},N2=function(a,b,c){c=c===void 0?!0:c;
a.player.gf("creatorendscreen");a.B&&(a.B.dispose(),a.B=null,a.D.dispose(),a.D=null);for(var d=g.w(Object.values(a.j)),e=d.next();!e.done;e=d.next())e.value.dispose();a.j={};a.G={};a.N.length>0&&(a.N.forEach(function(l){l.dispose()}),a.N.length=0);
a.K=0;if((a.endscreen=b)&&b.elements){c&&Rdb(a);c=[];d=new g.pE(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.U().B||(a.B=new g.U({I:"div",S:"ytp-ce-shadow"}),g.gS(a.player,a.B.element,4),a.D=new g.py(a.B,200));for(d=0;d<b.elements.length;++d){e=b.elements[d];var f=Sdb(a,e);if(f){a.j[e.id]=f;a.G[e.id]=e;g.gS(a.player,f.element,4);var h=new g.pE(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(h);Tdb(a,f,e)}else g.Uw(new g.ct("buildEndscreenElement null",
e))}a.player.lf(c);a.jc()}},Rdb=function(a){var b=g.Kw(),c=g.Lw();
c&&b&&a.endscreen.visualElement&&g.hr(g.fx)(void 0,c,b,a.endscreen.visualElement)},Sdb=function(a,b){var c=null;
switch(b.type){case "VIDEO":a={I:"div",Ka:["ytp-ce-element","ytp-ce-video"],X:{tabindex:"0","aria-label":b.xE||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-covering-image",X:O2(b)},{I:"div",S:"ytp-ce-covering-shadow-top"},{I:"a",S:"ytp-ce-covering-overlay",X:{href:P2(a,b.targetUrl),tabindex:"-1"},V:[{I:"div",Ka:["ytp-ce-video-title","ytp-webkit-ellipsis"],X:{dir:g.zp(b.title||"")},va:b.title},{I:"div",S:b.iG?"ytp-ce-live-video-duration":"ytp-ce-video-duration",
va:b.videoDuration||void 0}]}]};c=new g.U(a);break;case "PLAYLIST":a={I:"div",Ka:["ytp-ce-element","ytp-ce-playlist"],X:{tabindex:"0","aria-label":b.xE||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-covering-image",X:O2(b)},{I:"div",S:"ytp-ce-covering-shadow-top"},{I:"a",S:"ytp-ce-covering-overlay",X:{href:P2(a,b.targetUrl),tabindex:"-1"},V:[{I:"div",Ka:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],X:{dir:g.zp(b.title||"")},va:b.title},{I:"div",S:"ytp-ce-playlist-count",
V:[{I:"div",S:"ytp-ce-playlist-icon"},{I:"div",S:"ytp-ce-playlist-count-text",va:b.playlistLength||void 0}]}]}]};c=new g.U(a);break;case "CHANNEL":c={I:"div",Ka:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],X:{tabindex:"0","aria-label":b.xE||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-expanding-overlay",V:[{I:"div",S:"ytp-ce-expanding-overlay-hider"},{I:"div",S:"ytp-ce-expanding-overlay-background"},{I:"div",S:"ytp-ce-expanding-overlay-content",
V:[{I:"div",S:"ytp-ce-expanding-overlay-body",V:[{I:"div",S:"ytp-ce-expanding-overlay-body-padding",V:[{I:"a",Ka:["ytp-ce-channel-title","ytp-ce-link"],X:{href:P2(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.zp(b.title||"")},va:b.title},b.subscribeButton?{I:"div",S:"ytp-ce-subscribe-container",V:[{I:"div",S:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{I:"div",S:"ytp-ce-channel-subscribers-text",va:b.subscribersText}:"",b.metadata?{I:"div",Ka:["ytp-ce-channel-metadata","yt-ui-ellipsis",
"yt-ui-ellipsis-3"],va:b.metadata}:""]}]}]}]},{I:"div",S:"ytp-ce-expanding-image",X:O2(b)}]};c=new g.U(c);var d=g.bh(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.qp(d,"ytp-ce-subscribe-button");if(a.player.U().B){var e=null;var f=b.sessionData.itct}else e="endscreen",f=null;e=new g.AY(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,!!b.subscribeButton.enabled,!!b.subscribeButton.classic,
b.channelId,!!b.subscribeButton.subscribed,e,f,a.player,!1);d.appendChild(e.element);a.N.push(e)}break;case "WEBSITE":a={I:"div",Ka:["ytp-ce-element","ytp-ce-website"],X:{tabindex:"0","aria-label":b.xE||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-expanding-overlay",V:[{I:"div",S:"ytp-ce-expanding-overlay-hider"},{I:"div",S:"ytp-ce-expanding-overlay-background"},{I:"div",S:"ytp-ce-expanding-overlay-content",V:[{I:"div",S:"ytp-ce-expanding-overlay-body",V:[{I:"div",
S:"ytp-ce-expanding-overlay-body-padding",V:[{I:"div",S:"ytp-ce-website-title",X:{dir:g.zp(b.title||"")},va:b.title},{I:"div",S:"ytp-ce-website-metadata",va:b.metadata},{I:"a",Ka:["ytp-ce-website-goto","ytp-ce-link"],X:{href:P2(a,b.targetUrl),target:"_blank",tabindex:"-1"},va:b.callToAction}]}]}]}]},{I:"div",S:"ytp-ce-expanding-image",X:O2(b)},{I:"div",S:"ytp-ce-expanding-icon",X:Udb(b.iconUrl)}]};c=new g.U(a);break;case "CREATOR_MERCHANDISE":c="",b.productPrice&&(c={I:"div",S:"ytp-ce-merchandise-price-container",
V:[{I:"div",S:"ytp-ce-merchandise-price",va:b.productPrice}]},b.additionalFeesText&&c.V.push({I:"div",S:"ytp-ce-merchandise-additional-fees",va:b.additionalFeesText})),a={I:"div",Ka:["ytp-ce-element","ytp-ce-merchandise"],X:{tabindex:"0","aria-label":b.xE||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-expanding-overlay",V:[{I:"div",S:"ytp-ce-expanding-overlay-hider"},{I:"div",S:"ytp-ce-expanding-overlay-background"},{I:"div",S:"ytp-ce-expanding-overlay-content",
V:[{I:"div",S:"ytp-ce-expanding-overlay-body",V:[{I:"div",S:"ytp-ce-expanding-overlay-body-padding",V:[{I:"div",S:"ytp-ce-merchandise-title",X:{dir:g.zp(b.title||"")},va:b.title},c,{I:"div",S:"ytp-ce-merchandise-metadata",va:b.metadata},{I:"a",Ka:["ytp-ce-merchandise-goto","ytp-ce-link"],X:{href:P2(a,b.targetUrl),target:"_blank",tabindex:"-1"},va:b.callToAction}]}]}]}]},{I:"div",S:"ytp-ce-expanding-image",X:O2(b)},{I:"div",S:"ytp-ce-merchandise-invideo-cta-container",V:[{I:"div",S:"ytp-ce-merchandise-invideo-cta",
va:b.callToAction||void 0}]}]},c=new g.U(a)}b.isPlaceholder&&g.qp(c.element,"ytp-ce-placeholder");return c},O2=function(a){if(a.iY)var b=a.iY.thumbnails;
return Udb(b?b[b.length-1].url:null)},Udb=function(a){return a?{style:"background-image: url("+a+")"}:{}},Tdb=function(a,b,c){function d(m){m&&(b.listen("blur",function(){m.style.display!="none"&&a.W&&m.focus()}),b.T(m,"focus",f),b.T(m,"blur",h))}
function e(m){a.K+=m;a.K>0?(g.qp(b.element,"ytp-ce-force-expand"),Q2(a,c.id,!0)):(g.sp(b.element,"ytp-ce-force-expand"),g.sp(b.element,"ytp-ce-element-hover"),Q2(a,c.id,!1))}
function f(){e(1)}
function h(){e(-1)}
b.listen("mouseenter",function(){Vdb(a,b,c)});
b.listen("mouseleave",function(){Wdb(a,b,c)});
a.player.U().B||b.listen("click",function(){g.qp(b.element,"ytp-ce-element-hover")});
b.listen("click",function(m){Xdb(a,c,m)});
b.listen("keypress",function(m){Xdb(a,c,m)});
b.listen("focus",function(){Vdb(a,b,c)});
b.listen("blur",function(){Wdb(a,b,c)});
b.listen("touchstart",function(){Vdb(a,b,c)});
var l=g.dh("ytp-ce-expanding-overlay-hider",b.element);l&&b.T(l,"touchstart",function(m){m.stopPropagation();g.sp(b.element,"ytp-ce-element-hover");g.sp(b.element,"ytp-ce-force-expand")});
b.listen("keydown",function(m){a.W=m.keyCode===9&&!m.shiftKey});
d(g.dh("ytp-sb-subscribe",b.element));d(g.dh("ytp-sb-unsubscribe",b.element));b.listen("focus",f);b.listen("blur",h)},Xdb=function(a,b,c){if(b.targetUrl&&(!c||c.type!=="keypress"||c.keyCode===13)){for(var d=c.target;d&&!g.pp(d,"ytp-ce-element");){g.pp(d,"subscribe-label")&&Ydb(a,b);
if(g.pp(d,"ytp-ce-channel-subscribe"))return;d=d.parentElement||null}if(!d||g.pp(d,"ytp-ce-element-hover")){c.preventDefault();c.stopPropagation();if(d=a.j[b.id])Wdb(a,d,b),d.element.blur();if(c.ctrlKey||c.metaKey||b.mfa==="new")Ydb(a,b),a.player.sendVideoStatsEngageEvent(17,void 0),a.player.pauseVideo(),c=g.Pf(P2(a,b.targetUrl)),c=g.Lf(c),g.ez(c,void 0,b.sessionData);else{var e=g.DP(a.player.U())||a.player.getVideoData().Gf,f=function(){var h=P2(a,b.targetUrl),l=b.sessionData,m=b.watchEndpoint,n=
g.nr(h);e&&n&&(n.v||n.list)?a.player.Gp(n.v,l,n.list,!1,void 0,m||void 0):g.dz(h,l)};
Ydb(a,b,function(){a.player.sendVideoStatsEngageEvent(17,f)})}}}},P2=function(a,b){a=a.player.U();
if(b){if(b.startsWith("//"))return a.protocol+":"+b;if(b.startsWith("/"))return g.LP(a)+b}else return"";return b},Vdb=function(a,b,c){g.pp(b.element,"ytp-ce-element-hover")||(c.type==="VIDEO"||c.type==="PLAYLIST"?g.qp(b.element,"ytp-ce-element-hover"):a.player.U().B?(new g.ip(function(){g.qp(b.element,"ytp-ce-element-hover")},200)).start():g.qp(b.element,"ytp-ce-element-hover"),R2(a,c.y$),Q2(a,c.id,!0))},Wdb=function(a,b,c){g.sp(b.element,"ytp-ce-element-hover");
g.sp(b.element,"ytp-ce-force-expand");Q2(a,c.id,!1)},Q2=function(a,b,c){a.B&&(c?a.D.show():a.D.hide());
for(var d=g.w(Object.keys(a.j)),e=d.next();!e.done;e=d.next())e=e.value,e!==b&&g.up(a.j[e].element,"ytp-ce-element-shadow-show",c)},R2=function(a,b,c){function d(){f||(e++,e===b.length&&(h.stop(),c&&c()))}
if(!b||b.length===0||M2(a))c&&c();else{b=Zdb(a,b);var e=0,f=!1,h=new g.ip(function(){f=!0;c&&c()},1E3,a);
h.start();for(a=0;a<b.length;a++)g.cv(b[a],d)}},Ydb=function(a,b,c){R2(a,b.clickUrls,c);
(a=g.Lw())&&b.I$&&g.qx(a,b.visualElement)},Zdb=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce;
a=a.player.getCurrentTime().toFixed(2);c={CPN:c,AD_CPN:c,MT:a};a=[];for(var d=0;d<b.length;d++)a.push($db(b[d],c));return a},$db=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},aeb=function(a){return typeof a==="string"?a:""},S2=function(a,b,c){for(var d in b)if(b[d]===a)return a;
return c},beb=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.j=d},T2=function(a){return a.value?a.value:null},U2=function(a){if(!a)return null;
var b=g.Pf(aeb(a.value));b=g.Lf(b);if(!b)return null;var c=S2(a.target,ceb,"current");if(c==null)a=null;else{var d=a.show_link_icon;a=new beb(b,c,d==="true"||d==="false"?d==="true":!0,a.pause_on_navigation!=null?a.pause_on_navigation:!0)}return a},deb=function(a,b,c){this.type=a;
this.trigger=b;this.url=c},geb=function(a){if(!a)return null;
var b=S2(a.type,eeb),c=S2(a.trigger,feb);a=a.url;a=Array.isArray(a)&&a.length?a[0]:a;a=U2(a?a:null);return b?new deb(b,c,a):null},heb=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.data=e;this.action=d||[]},ieb=function(a,b){return g.Pb(a.action,b)},jeb=function(a,b){this.context=a;
this.j=b},keb=function(a){return a.customMessage?V2("div","iv-card-message",a.customMessage):""},W2=function(a,b){a="background-image: url("+a+");";
var c=[];b&&c.push(b);return{I:"div",S:"iv-card-image",X:{style:a},V:c}},leb=function(a){if(!a.metaInfo||a.metaInfo.length===0)return"";
var b=[];a=g.w(a.metaInfo);for(var c=a.next();!c.done;c=a.next())b.push(V2("li","",c.value));return{I:"ul",S:"iv-card-meta-info",V:b}},V2=function(a,b,c){b?typeof b==="string"?b={"class":b}:Array.isArray(b)&&(b={"class":b.join(" ")}):b={};
b.dir=g.zp(c);return{I:a,X:b,va:c}},meb=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.KE&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.KE+");");c.dir=g.zp(a.customMessage);var d=[{I:"span",va:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({I:"span",S:"iv-card-link-icon"}));return{I:"div",Ka:b,X:c,V:d}},X2=function(a,b,c,d){if(d){b=g.w(b);
for(var e=b.next();!e.done;e=b.next())a.j(e.value,d,c.id,c.sessionData,c.tj.click,5)}},neb=function(a,b){this.merchant=a;
this.price=b},oeb=function(a){var b;
(b=a)&&!(b=a.length>1?a.charAt(0)==="/"&&a.charAt(1)!=="/":a==="/")&&(b=a.replace(/^(https?:)?\/\//,"").split("/",1),b=!b||b.length<1||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b=b[0]==="com"&&b[1]==="youtube"||b[0]==="be"&&b[1]==="youtu");return b?a.indexOf("/redirect?")===-1:!1},peb=function(a,b){return b?b:oeb(a)?"current":"new"},Y2=function(a,b){g.O.call(this);
var c=this;this.element=a;this.context=b;this.kb=!1;this.Ta=new Map;this.Wa=new Map;this.context.J.addEventListener(g.rE("annotations_module"),function(d){(d=c.Ta.get(d))&&d.apply(c)});
this.context.J.addEventListener(g.sE("annotations_module"),function(d){(d=c.Wa.get(d))&&d.apply(c)})},Z2=function(a,b,c,d,e,f,h){a.context.j.listen(b,"click",function(l){a.oO(c,d,e,f||[],h||0,l)});
a.context.j.listen(b,"touchstart",function(){a.kb=!1});
a.context.j.listen(b,"touchmove",function(){a.kb=!0})},qeb=function(a){var b;
return((b=g.Q(a,g.Yx))==null?0:b.url)?g.Q(a,g.Yx).url:(a=g.Q(a,g.OQ))&&a.videoId?(b="/watch?v="+a.videoId,a.playlistId&&(b+="&list="+a.playlistId),a.index&&(b+="&index="+a.index),a.startTimeSeconds&&(b+="&t="+a.startTimeSeconds),b):null},$2=function(a,b,c){return{JZ:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl||""}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
m3:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
hN:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""})}},reb=function(a,b,c){Y2.call(this,b,c);
var d=this;this.J=a;this.eventId=null;this.Ab=this.La=this.Gb=this.C=this.isInitialized=!1;this.cards=[];this.qb=this.Z=this.Ja=this.G=this.Ua=this.j=null;this.oa=[];this.qa=this.N=this.Df=this.Fa=null;this.K=0;this.Ca=new g.ip(function(){},c.Y.gk?4E3:3E3);
g.P(this,this.Ca);this.ib=new g.ip(function(){});
g.P(this,this.ib);this.Aa=new jeb(c,function(e,f,h,l,m,n){Z2(d,e,f,h,l,m,n)});
this.W=new g.U({I:"div",S:"iv-drawer",X:{id:"iv-drawer"},V:[{I:"div",S:"iv-drawer-header",X:{"aria-role":"heading"},V:[{I:"span",S:"iv-drawer-header-text"},{I:"button",Ka:["iv-drawer-close-button","ytp-button"],X:{"aria-label":"Hide cards",tabindex:"0"}}]},{I:"div",S:"iv-drawer-content"}]});g.P(this,this.W);this.D=this.W.element;this.Va=new g.py(this.W,330);g.P(this,this.Va);this.Lb=g.dh("iv-drawer-header-text",this.D);this.B=g.dh("iv-drawer-content",this.D);this.addCueRange(0,c.videoData.lengthSeconds*
1E3,"",function(){d.Gb&&a3(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.Gb=d.C)&&b3(d)});
this.Na=new g.PF(this);g.P(this,this.Na);this.J.addEventListener("videodatachange",this.uu.bind(this))},seb=function(a,b){b=b.data;
b.autoOpenMs&&a.addCueRange(b.autoOpenMs,0x8000000000000,"",function(){a3(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.autoCloseMs&&a.addCueRange(b.autoCloseMs,0x8000000000000,"",function(){b3(a)});
var c=b.headerText;g.qh(a.Lb,c);a.Z&&a.Z.setAttribute("title",c);b.eventId&&(a.eventId=b.eventId);a.Fa=g.Iw(b.trackingParams);a.N=g.Iw(b.closeTrackingParams);a.Df=g.Iw(b.iconTrackingParams)},teb=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.K,d=a.J.U().experiments.bb("enable_error_corrections_infocard_web_client");
if(!b.content&&b.teaser.simpleCardTeaserRenderer&&d){var e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"simple",teaserText:g.Ex(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:{},sponsored:!1,tj:{},Yp:null,ek:e.trackingParams?g.Iw(e.trackingParams):null,Df:f&&f.trackingParams?g.Iw(f.trackingParams):null,imageUrl:"",displayDomain:null,showLinkIcon:!1,
KE:null,title:"",customMessage:"",url:null,onClickCommand:e.onTapCommand||null};c3(a,b)}else{var h;if((h=b.content)==null?0:h.simpleCardContentRenderer){if(!b.cueRanges.length)return;f=(e=b.content)==null?void 0:e.simpleCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;var l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"simple",teaserText:g.Ex(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,
sessionData:d3(a,c,b,f),sponsored:!1,tj:$2(f,e,f.command),Yp:f.trackingParams?g.Iw(f.trackingParams):null,ek:e.trackingParams?g.Iw(e.trackingParams):null,Df:l&&l.trackingParams?g.Iw(l.trackingParams):null,imageUrl:e3(f.image.thumbnails,290).url,displayDomain:f.displayDomain?g.Ex(f.displayDomain):null,showLinkIcon:!!f.showLinkIcon,KE:null,title:f.title?g.Ex(f.title):"",customMessage:f.callToAction?g.Ex(f.callToAction):"",url:g.Q(f.command,g.Yx).url?U2({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.Q(f.command,g.Yx).url}):null,onClickCommand:null};c3(a,b)}else{var m;if((m=b.content)==null?0:m.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;e=(f=b.content)==null?void 0:f.collaboratorInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"collaborator",teaserText:g.Ex(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),
autoOpen:!!b.autoOpen,sessionData:d3(a,c,b,e),sponsored:!1,tj:$2(e,f,e.endpoint),Yp:e.trackingParams?g.Iw(e.trackingParams):null,ek:f.trackingParams?g.Iw(f.trackingParams):null,Df:l&&l.trackingParams?g.Iw(l.trackingParams):null,channelId:g.Q(e.endpoint,g.hR).browseId,customMessage:e.customText?g.Ex(e.customText):null,profileImageUrl:e3(e.channelAvatar.thumbnails,290).url,title:e.channelName?g.Ex(e.channelName):"",metaInfo:[e.subscriberCountText?g.Ex(e.subscriberCountText):""],url:U2({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.Q(e.endpoint,g.hR).canonicalBaseUrl?g.Q(e.endpoint,g.hR).canonicalBaseUrl:"/channel/"+g.Q(e.endpoint,g.hR).browseId}),onClickCommand:null};c3(a,b)}else{var n;if((n=b.content)==null?0:n.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;e=(l=b.content)==null?void 0:l.playlistInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"playlist",teaserText:g.Ex(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:d3(a,c,b,e),sponsored:!1,tj:$2(e,f,e.action),Yp:e.trackingParams?g.Iw(e.trackingParams):null,ek:f.trackingParams?g.Iw(f.trackingParams):null,Df:l&&l.trackingParams?g.Iw(l.trackingParams):null,qI:e3(e.playlistThumbnail.thumbnails,258).url,customMessage:e.customMessage?g.Ex(e.customMessage):null,playlistVideoCount:g.Ex(e.playlistVideoCount),title:e.playlistTitle?g.Ex(e.playlistTitle):"",metaInfo:[e.channelName?g.Ex(e.channelName):
"",e.videoCountText?g.Ex(e.videoCountText):""],url:U2({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:qeb(e.action)}),onClickCommand:null};c3(a,b)}else{var p;if((p=b.content)==null?0:p.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;var q;e=(q=b.content)==null?void 0:q.videoInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"video",teaserText:g.Ex(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:d3(a,c,b,e),sponsored:!1,tj:$2(e,f,e.action),Yp:e.trackingParams?g.Iw(e.trackingParams):null,ek:f.trackingParams?g.Iw(f.trackingParams):null,Df:l&&l.trackingParams?g.Iw(l.trackingParams):null,qI:e3(e.videoThumbnail.thumbnails,258).url,videoDuration:e.lengthString?g.Ex(e.lengthString):null,customMessage:e.customMessage?g.Ex(e.customMessage):null,title:e.videoTitle?g.Ex(e.videoTitle):"",metaInfo:[e.channelName?g.Ex(e.channelName):
"",e.viewCountText?g.Ex(e.viewCountText):""],isLiveNow:!!e.badge,url:U2({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:qeb(e.action)}),onClickCommand:null};c3(a,b)}}}}}a.K++},e3=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height===b||a[e].width===290)return a[e];
((a[e].height||0)<b||(a[e].width||0)<290)&&(c<0||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||(a[e].width||0)>=290)&&(d<0||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[d>=0?d:c]},d3=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId||"",itct:d.trackingParams||""}},veb=function(a,b){if(b=ueb(a,b))b===a.j&&(a.j=null),a.J.removeCueRange(b.xf.id),g.oh(b.WO),g.Ub(a.cards,b),a.vJ(),f3(a)},a3=function(a,b,c){if(!a.C){a.Va.show();
a.Ua=new g.ip(function(){g.qp(a.context.J.getRootNode(),g.F_.IV_DRAWER_OPEN)},0);
a.Ua.start();a.Na.T(a.B,"mousewheel",function(h){a.Ca.start();h.preventDefault();h=h||window.event;var l=0;h.type=="MozMousePixelScroll"?l=0==(h.axis==h.HORIZONTAL_AXIS)?h.detail:0:window.opera?l=h.detail:l=h.wheelDelta%120==0?"WebkitTransform"in document.documentElement.style?window.chrome&&navigator.platform.indexOf("Mac")==0?h.wheelDeltaY/-30:h.wheelDeltaY/-1.2:h.wheelDelta/-1.6:h.wheelDeltaY/-3;if(h=l)a.B.scrollTop+=h});
a.C=!0;var d=g.Lw();d&&a.Fa&&a.N&&g.ox(d,[a.Fa,a.N]);b={TRIGGER_TYPE:b};for(var e=g.w(a.cards),f=e.next();!f.done;f=e.next())f=f.value,f.L_||(f.L_=!0,web(a.context.logger,f.xf.tj.JZ,b)),d&&g.ox(d,[f.xf.Yp]);D2(a.J);c&&(a.G=new g.ip(function(){a.Ja=a.Z;a.qb.focus()},330),a.G.start())}},b3=function(a){a.C&&(a.Va.hide(),g.Ms(a.Na),g.sp(a.context.J.getRootNode(),g.F_.IV_DRAWER_OPEN),a.C=!1,D2(a.J),a.G&&a.G.stop(),a.G=new g.ip(function(){a.Ja&&(a.Ja.focus(),a.Ja=null)},330),a.G.start())},xeb=function(a){g.rp(a.Ib(),
[g.F_.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.gS(a.J,a.D,5);a.hJ();a.Z=g.dh("ytp-cards-button",a.J.getRootNode());a.qb=g.dh("iv-drawer-close-button",a.D);a.isInitialized=!0},yeb=function(a){a.oa.push(g.vv("iv-teaser-shown",a.c5,a));
a.oa.push(g.vv("iv-teaser-hidden",a.eaa,a));a.oa.push(g.vv("iv-teaser-clicked",a.b5,a));a.Ab=!0},zeb=function(a,b){var c;
return b.onClickCommand&&((c=g.Q(b.onClickCommand,g.obb))==null?void 0:c.targetId)==="engagement-panel-error-corrections"?(a.qa=b,!0):!1},Aeb=function(a,b){a.qa=b;
var c=a.J.getVideoData();if(!c)return!1;c=g.gQ(c);if(c==null?0:c.markersMap)for(var d,e=0;((d=c)==null?void 0:d.markersMap.length)>e;e++){var f=void 0,h=(f=c)==null?void 0:f.markersMap[e];if(h.key==="ERROR_CORRECTION_MARKERS"&&(f=void 0,(h=(f=h.value)==null?void 0:f.markers)&&h.length>0))return d=void 0,b.startMs=((d=g.Q(h[0],g.j3a))==null?void 0:d.timeRangeStartMillis)||0,a.qa=null,!0}return!1},c3=function(a,b){if(!zeb(a,b)||Aeb(a,b)){var c=Beb(a,b);
if(c){var d={xf:b,WO:c.element,L_:!1};if(b.onClickCommand)a.J.L("web_infocards_teaser_show_logging_fix")&&(a.Ab||yeb(a),veb(a,b.id),c=a.findLastIndex(d),g.$b(a.cards,c,0,d));else{a.isInitialized||xeb(a);veb(a,b.id);var e=a.findLastIndex(d);g.$b(a.cards,e,0,d);c.Ha(a.B,e);a.vJ()}b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,function(){a.C||(a.j=d,f3(a),Ceb(a,d),a3(a,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(c=a.context.J.getCurrentTime()*1E3,c<5E3&&c>b.startMs&&Deb(a,d),a.addCueRange(b.startMs,
b.startMs+1,b.id,function(){Deb(a,d)}),f3(a))}}},Beb=function(a,b){switch(b.type){case "simple":a=a.Aa;
var c=b.displayDomain?{I:"div",S:"iv-card-image-text",va:b.displayDomain}:void 0;var d=meb(b);c={I:"div",Ka:["iv-card"],V:[{I:"a",S:"iv-click-target",X:{href:b.url?T2(b.url)||"":""},V:[W2(b.imageUrl,c),{I:"div",S:"iv-card-content",V:[V2("h2",void 0,b.title),d]}]}]};c=new g.U(c);X2(a,g.ch("iv-click-target",c.element),b,b.url);b=c;break;case "collaborator":a=a.Aa;c={I:"div",Ka:["iv-card","iv-card-channel"],V:[{I:"a",Ka:["iv-click-target"],X:{href:T2(b.url)||"","data-ytid":b.channelId},V:[W2(b.profileImageUrl),
{I:"div",S:"iv-card-content",V:[keb(b),{I:"h2",S:"iv-card-primary-link",va:b.title},leb(b)]}]}]};c=new g.U(c);X2(a,g.ch("iv-click-target",c.element),b,b.url);b=c;break;case "playlist":a=a.Aa;c={I:"div",Ka:["iv-card","iv-card-playlist"],V:[{I:"a",S:"iv-click-target",X:{href:T2(b.url)||""},V:[W2(b.qI,{I:"div",S:"iv-card-image-overlay",V:[{I:"span",S:"iv-card-playlist-video-count",va:b.playlistVideoCount}]}),{I:"div",S:"iv-card-content",V:[keb(b),V2("h2","iv-card-primary-link",b.title),leb(b)]}]}]};
c=new g.U(c);X2(a,g.ch("iv-click-target",c.element),b,b.url);b=c;break;case "productListing":a=a.Aa;var e=b.offers.length!=0;c=["iv-card"];d="";var f=meb(b);e&&(c.push("iv-card-product-listing"),d="iv-card-primary-link",f=b.offers[0],e=[],f.price&&e.push({I:"div",S:"iv-card-offer-price",va:f.price}),f.merchant&&e.push({I:"div",S:"iv-card-offer-merchant",va:f.merchant}),f={I:"div",V:e});e=b.url?T2(b.url)||"":"";c={I:"div",Ka:c,X:{tabindex:"0"},V:[{I:"a",Ka:["iv-card-image","iv-click-target"],X:{style:"background-image: url("+
b.imageUrl+");",href:e,"aria-hidden":"true",tabindex:"-1"}},{I:"div",S:"iv-card-content",V:[b.sponsored?{I:"div",S:"iv-card-sponsored",V:["Sponsored",{I:"div",S:"iv-ad-info-container",V:[{I:"div",S:"iv-ad-info",va:"{{adInfo}}"},{I:"div",S:"iv-ad-info-icon-container",V:[{I:"div",S:"iv-ad-info-icon"},{I:"div",S:"iv-ad-info-callout"}]}]}]}:"",{I:"a",S:"iv-click-target",X:{href:e},V:[V2("h2",d,b.title),f]}]}]};c=new g.U(c);d=g.jh("span");g.qh(d,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
c.Bd(d,"adInfo");X2(a,g.ch("iv-click-target",c.element),b,b.url);b=c;break;case "video":a=a.Aa;d=b.videoDuration?{I:"span",S:"iv-card-video-duration",va:b.videoDuration}:void 0;f=b.isLiveNow?{I:"span",Ka:["yt-badge","yt-badge-live"],va:"LIVE NOW"}:null;e={I:"div",Ka:["iv-card","iv-card-video"],V:[{I:"a",S:"iv-click-target",X:{href:((c=b.url)==null?void 0:T2(c))||""},V:[W2(b.qI,d),{I:"div",S:"iv-card-content",V:[keb(b),V2("h2","iv-card-primary-link",b.title),leb(b),f]}]}]};c=new g.U(e);X2(a,g.ch("iv-click-target",
c.element),b,b.url);b=c;break;default:return null}return b},Eeb=function(a){if(a.j)return a.j.xf.type==="productListing";
if(a.J.L("enable_wn_infocards")){var b;return!((b=a.cards)==null||!b.length)&&g.Jl(a.cards,function(c){return c.xf.type==="productListing"})}return g.Jl(a.cards,function(c){return c.xf.type==="productListing"})},f3=function(a){g.up(a.J.getRootNode(),"ytp-cards-shopping-active",Eeb(a))},Deb=function(a,b){if(!g.pp(a.J.getRootNode(),"ytp-cards-teaser-shown")){if(a.j!==b){var c=g.Lw(),d=a.j?a.j.xf.Df:a.Df;
c&&d&&g.px(c,[d]);a.j=b;f3(a)}(c=a.isInitialized&&a.Ib().style.display=="none")||(c=a.context.J.getPlayerState(),d=c===0&&a.context.J.getCurrentTime()===0,c=!(c===1||c===3||d));c||b.xf.teaserDurationMs&&a.J.AC(!0,{teaserText:b.xf.teaserText,durationMs:b.xf.teaserDurationMs,onClickCommand:b.xf.onClickCommand});a.ib.isActive()||((!a.C||!a.Ca.isActive()&&a.La)&&Ceb(a,b),a.ib.start(910+b.xf.teaserDurationMs))}},Ceb=function(a,b){a.W.Eb?(b=new I2([0,
a.B.scrollTop],[0,b.WO.offsetTop],600,Kdb),a.context.C.listen(b,"animate",function(c){a.B.scrollTop=c.y}),a.context.C.listen(b,"finish",function(c){a.B.scrollTop=c.y}),b.play()):(g.Ax(a.W,!0),a.B.scrollTop=b.WO.offsetTop,g.Ax(a.W,!1))},g3=function(a){return a.j&&a.j.xf?a.j.xf:a.cards[0]&&a.cards[0].xf?a.cards[0].xf:null},ueb=function(a,b){return g.Pb(a.cards,function(c){return c.xf.id===b})},h3=function(a,b,c){Y2.call(this,a,b);
this.annotation=c;this.isActive=!1},Feb=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(Number(b.start_ms),Number(b.end_ms),a.annotation.id,function(){a.show()},function(){a.hide()})},i3=function(a,b,c){h3.call(this,a,b,c);
this.B=null;this.N=!1;this.C=null;this.D=!1;this.j=this.K=this.G=null},Geb=function(a,b){var c=c===void 0?0:c;
var d=Bdb(b).width;g.Em(b,d);c=new Idb(b,[d,b.offsetTop],[d-d-c,b.offsetTop],200,Jdb);g.P(a,c);a.context.C.listen(c,"begin",function(){g.Km(b,!0)});
c.play()},Jeb=function(a,b){if(b.channel_name){var c=a.createElement({I:"div",
Ka:["iv-branding-context-name"],va:b.channel_name}),d=a.createElement({I:"div",Ka:["iv-branding-context-subscribe"]}),e=b.standalone_subscribe_button_data;e&&(a.j=new g.AY(e.subscribeText,e.subscribeCount,e.unsubscribeText,e.unsubscribeCount,!!e.enabled,!!e.classic,b.channel_id,!!e.subscribed,e.feature,b.session_data.itct,a.context.J,!1),a.j.Ha(d));var f=a.createElement({I:"div",Ka:["iv-branding-context-subscribe-caret"]}),h=a.createElement({I:"div",Ka:["branding-context-container-inner"]});h.appendChild(f);
h.appendChild(c);h.appendChild(d);g.Km(h,!1);var l=a.createElement({I:"div",Ka:["branding-context-container-outer"]});l.appendChild(h);g.xm(l,"right",b.image_width+"px");g.lh(a.Ib(),l);a.C=new g.ip(function(){Heb(a,h,l)},500);
g.P(a,a.C);a.context.j.listen(a.Ib(),"mouseover",function(){Ieb(a,h,l,f,b.image_height)});
a.context.j.listen(a.Ib(),"mouseout",function(){a.C.start()})}},Ieb=function(a,b,c,d,e){a.C.stop();
if(!a.D){var f=g.Jm(b);a.j||(b.style.width=g.Dm(f.width,!0),c.style.width=g.Dm(f.width,!0));g.xm(d,"top",f.height-Math.max(Math.min(f.height,e)/2+10,20)+"px");g.xm(d,"right","1px");a.D=!0;g.Km(b,!0);a.G=new g.ip(function(){g.qp(this.Ib(),"iv-branding-active")},0,a);
a.G.start()}},Heb=function(a,b,c){g.sp(a.Ib(),"iv-branding-active");
a.K=new g.ip(function(){g.Km(b,!1);a.j||(c.style.width=g.Dm(0,!0))},250);
a.K.start();a.D=!1},Keb=function(a,b,c,d,e,f,h){this.j=a;
this.C=b;this.Y=c;this.videoData=d;this.logger=e;this.J=f;this.B=h},Leb=function(a,b,c){h3.call(this,a,b,c);
var d=this;this.Z=this.isCollapsed=this.W=!1;this.K=5E3;this.B=this.C=this.j=this.D=null;this.N=this.createElement({I:"div",Ka:["iv-promo-contents"]});this.G=new g.ip(function(){d.j.setAttribute("aria-hidden","true");g.Km(d.C,!1);g.Km(d.B,!0)},700,this);
g.P(this,this.G)},Oeb=function(a,b,c){c.stopPropagation();
Meb(a);Neb(a,b);a.j.focus()},Peb=function(a){a.isCollapsed||a.Z||a.D||(g.qp(a.Ib(),"iv-promo-collapsed"),a.isCollapsed=!0,a.G.start())},Meb=function(a){a.G.stop();
a.isCollapsed&&(g.tp(a.Ib(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.isCollapsed=!1,a.j&&a.j.removeAttribute("aria-hidden"),g.Km(a.B,!1),g.Km(a.C,!0))},Neb=function(a,b){a.D||(a.D=g.Gi(function(){Qeb(this);
Peb(this)},b,a))},Qeb=function(a){a.D&&(g.La.clearTimeout(a.D),a.D=null)},Reb=function(a){this.J=a},web=function(a,b,c){b&&(c?j3(a,b.map(function(d){return g.Oo(d,c)})):j3(a,b))},j3=function(a,b,c,d){var e=1,f=void 0,h=-1;
if(c){var l=!1;f=function(){e--;e||l||(clearTimeout(h),l=!0,c())};
h=setTimeout(function(){l=!0;c()},1E3)}b=g.w(b||[]);
for(var m=b.next();!m.done;m=b.next())m=m.value,e++,g.cv(m,f);d&&(e++,d!==0&&a.J.sendVideoStatsEngageEvent(d,f))},Seb=function(a){g.UX.call(this,a);
var b=this;this.oa=this.Z=!1;this.loadNumber=0;this.K={};this.logger=new Reb(this.player);this.D=new g.PF(this);this.G=this.N=null;this.events=new g.PF(this);this.hh=this.W=this.j=null;this.qa=[];g.P(this,this.D);this.D.T(this.player,"onVideoAreaChange",function(){b.publish("onVideoAreaChange")});
this.D.T(this.player,"onHideControls",function(){b.publish("onHideControls")});
this.D.T(this.player,"onShowControls",function(){b.publish("onShowControls")});
this.D.T(this.player,"resize",function(d){b.publish("resize",d)});
this.D.T(this.player,"presentingplayerstatechange",function(d){b.publish("presentingplayerstatechange",d)});
this.subscribe("presentingplayerstatechange",this.d5,this);this.subscribe("resize",this.XL,this);this.player.U().La.subscribe("vast_info_card_add",this.b1,this);g.P(this,this.events);this.Aa=this.createElement({I:"div",S:"video-custom-annotations"});this.B=new g.U({I:"div",Ka:["ytp-player-content","ytp-iv-player-content"]});g.P(this,this.B);g.gS(this.player,this.B.element,4);this.B.hide();this.C=new g.U({I:"div",Ka:["ytp-iv-video-content"]});g.P(this,this.C);a=this.createElement({I:"div",S:"video-annotations"});
a.appendChild(this.Aa);this.C.element.appendChild(a);this.Dv()&&this.load();var c=this.createElement({I:"style"});(g.ah("HEAD")[0]||document.body).appendChild(c);this.addOnDisposeCallback(function(){g.oh(c)});
if(a=c.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},Teb=function(a){a=a.createElement({I:"div",
Ka:["annotation","annotation-type-custom"]});g.Km(a,!1);return a},Ueb=function(a,b){b=!b.isCued()&&!g.Z(b,1024);
g.Ax(a.B,b);g.Ax(a.C,b)},Veb=function(a,b,c){a.Z=!0;
a.G=g.Ir(b,c)},Web=function(a,b){for(var c={},d=g.w(b.attributes),e=d.next();!e.done;e=d.next())e=e.value,c[e.name]=e.nodeValue;
for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.Ra(e)&&e.nodeType==1){if(c[e.tagName])var f=c[e.tagName];else if(e.tagName==="data"){e.childNodes.length>0&&(f=e.childNodes[0].nodeValue,c[e.tagName]=typeof f==="string"?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&e.tagName==="TEXT"?e.childNodes.length===1&&e.childNodes[0].nodeType===3?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(Web(a,e))}return c},$eb=function(a){var b=a.player.getVideoData();
if(b.Ta){var c=a.player.U().La.get(b.videoId);if(c){var d={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(e,f,h){e=a.loadNumber;f=b.videoId;a.loaded&&a.loadNumber===e&&a.player.getVideoData().videoId===f&&(h=g.xr(h)&&h.responseXML?h.responseXML:null)&&Xeb(a,h)}};
g.kt()&&(d.onFinish=Yeb(a,d.onFinish));d.postParams={ic_only:"1"};Zeb(d,c);a.Z=!0;g.Ir(b.Ta,d)}}},Zeb=function(a,b){a.method="POST";
a.postParams=a.postParams||{};b.AJ&&(a.postParams.ic_coll=b.AJ);b.XO&&(a.postParams.ic_xml=b.XO);b.mN&&(a.postParams.ic_track=b.mN)},afb=function(a){var b=new g.U({I:"div"});
g.Km(b.element,!1);var c=new reb(a.player,b.element,k3(a));g.P(c,b);b.Ha(a.B.element);c.aI();return c},cfb=function(a,b){var c,d;
if(b=(c=b.getWatchNextResponse())==null?void 0:(d=c.cards)==null?void 0:d.cardCollectionRenderer)a.oa=!0,bfb(a,b),b.headerText&&a.hh&&(c=g.Ex(b.headerText),a.hh.setAttribute("title",c))},k3=function(a){if(!a.W){var b=new Ldb(a);
g.P(a,b);var c=new g.Hk(a);g.P(a,c);a.W=new Keb(b,c,a.player.U(),a.player.getVideoData(),a.logger,a.player,a.Kj)}return a.W},Xeb=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(d.length<1)&&(d=d[0].getAttribute("itct"))){var e=g.Lw();if(e){var f=g.Kw();f&&g.hr(g.ex)(void 0,e,f,[g.Iw(d)])}}b=b.getElementsByTagName("annotation");for(d=0;d<b.length;d++){f=Web(a,b[d]);e=null;try{if(f){var h=f.id,l=/.+/;var m=typeof h==="string"&&l!=null&&h!=null&&h.match(l)?h:"";var n=S2(f.type,dfb),p=S2(f.style,efb),q=aeb(f.data),r=q.length!==0?JSON.parse(q):{};var t=f.action;f=geb;if(t==null)var u=null;else if(g.Qa(t)){l=[];for(var y=g.w(t),A=y.next();!A.done;A=y.next()){var C=f(A.value);
C&&l.push(C)}u=l}else{var F=f(t);u=F?[F]:[]}e=m&&n?new heb(m,n,p,u,r):null}else e=null}catch(fa){}if(e)if(e.type==="branding"||e.type==="promotion"){f=a;l=e;var H=Teb(f),N=null;switch(l.type){case "branding":if(f.player.U().Kd)break;f.B.element.appendChild(H);N=new i3(H,k3(f),l);break;case "promotion":g.gS(f.player,H,4),N=new Leb(H,k3(f),l)}N&&N.aI();if(f=N)g.P(a,f),a.K[e.id]=f}else if(e.type==="card"||e.type==="drawer"){a.j||(a.j=afb(a),g.P(a,a.j));if(e.type==="card"){H=a.j;var M=(c=e)&&c.data&&
c.data.card_type;e=c.data;if(M)switch(f=e.tracking||{},f={JZ:f.impression,click:f.click,close:f.close,m3:f.teaser_impression,hN:f.teaser_click},l=e.tracking_params||{},N=null,M){case "collaborator":c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,tj:f,Yp:l.card?g.Iw(l.card):null,ek:l.teaser?g.Iw(l.teaser):null,Df:l.icon?g.Iw(l.icon):
null,channelId:e.channel_id,customMessage:e.custom_message?e.custom_message:null,profileImageUrl:e.image_url,title:e.title,metaInfo:e.meta_info,url:U2({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null};c3(H,c);break;case "playlist":c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,tj:f,
Yp:l.card?g.Iw(l.card):null,ek:l.teaser?g.Iw(l.teaser):null,Df:l.icon?g.Iw(l.icon):null,qI:e.image_url,playlistVideoCount:e.playlist_video_count,customMessage:e.custom_message?e.custom_message:null,title:e.title,metaInfo:e.meta_info,url:U2({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null};c3(H,c);break;case "productListing":e.signin_url&&(N=U2({target:"current",value:e.signin_url}));M=[];for(var X=e.offers||[],W=0;W<X.length;W++)M.push(new neb(g.hg(X[W].merchant),
g.hg(X[W].price)));c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,tj:f,Yp:l.card?g.Iw(l.card):null,ek:l.teaser?g.Iw(l.teaser):null,Df:l.icon?g.Iw(l.icon):null,imageUrl:e.image_url,displayDomain:e.display_domain?e.display_domain:null,showLinkIcon:!!e.show_link_icon,KE:e.button_icon_url?e.button_icon_url:null,title:e.title,customMessage:e.custom_message?
e.custom_message:null,url:U2({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),uqa:N,tqa:e.signin_title?e.signin_title:void 0,sqa:e.signin_message?e.signin_message:void 0,offers:M,onClickCommand:null};c3(H,c);break;case "simple":c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,tj:f,Yp:l.card?g.Iw(l.card):
null,ek:l.teaser?g.Iw(l.teaser):null,Df:l.icon?g.Iw(l.icon):null,imageUrl:e.image_url,displayDomain:e.display_domain?e.display_domain:null,showLinkIcon:!!e.show_link_icon,KE:e.button_icon_url?e.button_icon_url:null,title:e.title,customMessage:e.custom_message?e.custom_message:null,url:U2({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null};c3(H,c);break;case "video":c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,
startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,tj:f,Yp:l.card?g.Iw(l.card):null,ek:l.teaser?g.Iw(l.teaser):null,Df:l.icon?g.Iw(l.icon):null,qI:e.image_url,videoDuration:e.video_duration||null,customMessage:e.custom_message?e.custom_message:null,title:e.title,metaInfo:e.meta_info,isLiveNow:!!e.is_live_now,url:U2({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null},c3(H,c)}}else seb(a.j,e);c=!0}}c&&
(D2(a.player),a.XL())},bfb=function(a,b){var c=!1;
a.j||(a.j=afb(a),g.P(a,a.j));for(var d=g.w(b.cards||[]),e=d.next();!e.done;e=d.next())e=e.value,e.cardRenderer&&(teb(a.j,e.cardRenderer),c=!0);if(c){var f;(f=a.player.getVideoData())!=null&&g.oR(f)||(c=a.j,d=b.headerText?g.Ex(b.headerText):"",g.qh(c.Lb,d),c.Z&&c.Z.setAttribute("title",d),c.context.videoData.eventId&&(c.eventId=c.context.videoData.eventId),c.Fa=b.trackingParams?g.Iw(b.trackingParams):null,c.N=b.closeButton.infoCardIconRenderer.trackingParams?g.Iw(b.closeButton.infoCardIconRenderer.trackingParams):
null,c.Df=b.icon.infoCardIconRenderer.trackingParams?g.Iw(b.icon.infoCardIconRenderer.trackingParams):null,a.XL());D2(a.player)}},ffb=function(a,b,c,d,e){if(!a.player.U().Kd){var f=[];
b.navigationEndpoint&&g.Q(b.navigationEndpoint,g.hR)&&g.Q(b.navigationEndpoint,g.hR).browseId&&f.push(new deb("openUrl","click",new beb("/channel/"+g.Q(b.navigationEndpoint,g.hR).browseId,"new",!0,!0)));var h=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:h.height,image_type:1,image_url:h.url,image_width:h.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&g.Q(b.subscribeButton,
g.iR)){d.channel_id=g.Q(b.subscribeButton,g.iR).channelId;var l;b=g.Q(b.subscribeButton,g.iR);h=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.Ex(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(h=g.Ex(b.subscriberCountText))):(b.subscriberCountText&&(e=g.Ex(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(h=g.Ex(b.subscriberCountWithSubscribeText)));var m,n=((m=g.Q((l=b.signInEndpoint)==null?void 0:l.commandMetadata,g.w1))==null?void 0:m.url)||"";l={subscribeText:g.Ex(b.unsubscribedButtonText),
subscribeCount:e||"",unsubscribeText:g.Ex(b.subscribedButtonText),unsubscribeCount:h||"",enabled:b.enabled||!1,classic:!1,subscribed:b.subscribed||!1,feature:"iv",signInUrl:n};d.standalone_subscribe_button_data=l}f=new heb(c,"branding","branding",f,d);l=Teb(a);a.B.element.appendChild(l);f=new i3(l,k3(a),f);f.aI();g.P(f,f);a.K[c]=f}},Yeb=function(a,b){return function(){var c=g.Ea.apply(0,arguments);
a.Ia()||a.qa.push(g.bp.Xi(function(){b.apply(null,g.x(c))}))}},gfb=function(a){return a==="annotation-editor"||a==="live-dashboard"};
g.$R.prototype.AC=g.da(35,function(a,b){var c=g.iY(this.yb());c&&c.AC(a,b)});
var F2={},G2=null;g.Ya(I2,g.vp);g.k=I2.prototype;g.k.getDuration=function(){return this.duration};
g.k.play=function(a){if(a||this.j==0)this.progress=0,this.coords=this.B;else if(this.isPlaying())return!1;H2(this);this.startTime=a=g.Xa();this.isPaused()&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.D=this.startTime;this.progress||this.OL();this.ao("play");this.isPaused()&&this.ao("resume");this.j=1;var b=g.Ua(this);b in F2||(F2[b]=this);Edb();Fdb(this,a);return!0};
g.k.stop=function(a){H2(this);this.j=0;a&&(this.progress=1);Gdb(this,this.progress);this.onStop();this.Gs()};
g.k.pause=function(){this.isPlaying()&&(H2(this),this.j=-1,this.ao("pause"))};
g.k.xa=function(){this.j==0||this.stop(!1);this.ao("destroy");I2.Rf.xa.call(this)};
g.k.destroy=function(){this.dispose()};
g.k.nO=function(){this.ao("animate")};
g.k.ao=function(a){this.dispatchEvent(new Hdb(a,this))};
g.Ya(Hdb,g.Th);g.Ya(J2,I2);J2.prototype.C=function(){};
J2.prototype.nO=function(){this.C();J2.Rf.nO.call(this)};
J2.prototype.Gs=function(){this.C();J2.Rf.Gs.call(this)};
J2.prototype.OL=function(){this.C();J2.Rf.OL.call(this)};
g.Ya(Idb,J2);Idb.prototype.C=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.z(Ldb,g.O);g.k=Ldb.prototype;g.k.listen=function(a,b,c,d){c=(0,g.Va)(c,d||this.B);a=g.Fs(a,b,c);this.j.push(a);return a};
g.k.zG=function(a,b,c,d){c=(0,g.Va)(c,d||this.B);a=Cdb(a,b,c);this.j.push(a);return a};
g.k.Lc=function(a){g.Gs(a);g.Ub(this.j,a)};
g.k.removeAll=function(){g.Gs(this.j);this.j.length=0};
g.k.xa=function(){this.removeAll();g.O.prototype.xa.call(this)};g.z(Odb,g.UX);g.k=Odb.prototype;g.k.load=function(){g.UX.prototype.load.call(this);if(!M2(this)){var a=g.VLa(this.player.getVideoData());a?(a=Ndb(a,Pdb(this)),N2(this,a,!1)):Qdb(this)}};
g.k.unload=function(){N2(this,null);this.C&&(this.C.abort(),this.C=null);g.UX.prototype.unload.call(this)};
g.k.ai=function(a,b){return M2(this)?a==="loadCustomEndscreenRenderer"?(a=Ndb(b,"new"),N2(this,a),!0):null:null};
g.k.getOptions=function(){return M2(this)?["loadCustomEndscreenRenderer"]:[]};
g.k.jc=function(){if(this.endscreen&&this.endscreen.elements){var a=this.player.getVideoContentRect();if(a&&a.width!==0&&a.height!==0){var b=this.player.getPlayerSize();if(b&&b.width!==0&&b.height!==0){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<hfb.length;f++){var h=Math.abs(b.width-hfb[f]);if(e===-1||d>=h)e=f,d=h}d=ifb[e];this.B&&g.xm(this.B.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.endscreen.elements.length;++b)if(f=this.endscreen.elements[b].id,e=this.j[f],
h=this.G[f],e&&h){var l=h.width*c/h.aspectRatio,m=Math.round(h.width*a.width);f=Math.round(l*a.height);var n=a.left+Math.round(h.left*a.width),p=a.top+Math.round(h.top*a.height);g.Im(e.element,m,f);g.Em(e.element,n,p);g.tp(e.element,jfb);m>256||f>256?g.qp(e.element,"ytp-ce-large-round"):m>96||f>96?g.qp(e.element,"ytp-ce-medium-round"):g.qp(e.element,"ytp-ce-small-round");g.tp(e.element,kfb);m=h.left+h.width/2;h=h.top+l/2;g.qp(e.element,m<=.5&&h<=.5?"ytp-ce-top-left-quad":m>.5&&h<=.5?"ytp-ce-top-right-quad":
m<=.5&&h>.5?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.tp(e.element,ifb);g.qp(e.element,d);(e=g.bh(document,"div","ytp-ce-expanding-overlay-body",e.element)[0])&&g.xm(e,"height",f+"px")}}}}};
g.k.onCueRangeEnter=function(a){if(this.endscreen)if(a.getId()==="ytp-ce-in-endscreen")R2(this,this.endscreen.impressionUrls),(a=g.Lw())&&this.endscreen.visualElement&&g.nx(a,this.endscreen.visualElement);else{a=a.getId().substring(15);var b=this.j[a],c=this.G[a];g.qp(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.qp(b,"ytp-ce-shown");R2(this,c.impressionUrls);(b=g.Lw())&&g.nx(b,c.visualElement);this.player.U().N&&this.player.fb("endscreenelementshown",
a)}};
g.k.onCueRangeExit=function(a){if(a.getId()!=="ytp-ce-in-endscreen"){a=a.getId().substring(15);var b=this.j[a];g.sp(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden","true");b=this.player.getRootNode();g.sp(b,"ytp-ce-shown");this.player.U().N&&this.player.fb("endscreenelementhidden",a)}};
g.k.oda=function(a){var b=this;a.target===window&&(new g.ip(function(){for(var c=g.w(Object.values(b.j)),d=c.next();!d.done;d=c.next())g.tp(d.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
var hfb=[346,426,470,506,570,640,853,1280,1920],ifb="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),kfb=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"],jfb=["ytp-ce-small-round","ytp-ce-medium-round","ytp-ce-large-round"];var ceb={Kha:"current",pka:"new"};var eeb={CLOSE:"close",uka:"openUrl",SUBSCRIBE:"subscribe"},feb={tha:"click",CLOSE:"close",Mia:"hidden",jla:"rollOut",kla:"rollOver",wla:"shown"};heb.prototype.De=function(){var a=ieb(this,function(b){return b.type==="openUrl"&&b.url!=null});
return a?a.url:null};
var efb={Ega:"anchored",F4:"branding",CHANNEL:"channel",Jha:"cta",Pia:"highlightText",Dja:"label",PLAYLIST:"playlist",POPUP:"popup",Ela:"speech",SUBSCRIBE:"subscribe",Pla:"title",VIDEO:"video",yma:"website"},dfb={F4:"branding",gha:"card",Wha:"drawer",Oia:"highlight",Tja:"marker",Pka:"promotion",TEXT:"text",ana:"widget"};g.z(Y2,g.O);g.k=Y2.prototype;g.k.addCueRange=function(a,b,c,d,e){a=new g.pE(a,b,{id:c,namespace:"annotations_module"});d&&this.Ta.set(a,d);e&&this.Wa.set(a,e);this.context.J.lf([a],1)};
g.k.aI=function(){this.context.B.subscribe("resize",this.vJ,this)};
g.k.Ib=function(){return this.element};
g.k.oO=function(a,b,c,d,e,f){if(this.kb)return!1;f&&(f.stopPropagation(),f.preventDefault());this.navigate(a,c,d,e);return!1};
g.k.show=function(){};
g.k.hide=function(){};
g.k.destroy=function(){g.oh(this.Ib())};
g.k.vJ=function(){};
g.k.navigate=function(a,b,c,d){var e=this,f=T2(a);if(f){var h=peb(f,a.target),l=function(){a.j&&e.context.J.pauseVideo();var m=e.context.videoData.Gf||!1,n=g.nr(f||"");m&&n&&(n.v||n.list)?e.context.J.Gp(n.v,b,n.list,!1):g.ez(f||"",h==="current"?"_top":void 0,b)};
h==="new"&&(l(),l=null);j3(this.context.logger,c,l,d);oeb(f)||(c=g.Lw(),d=b.itct,c&&d&&g.qx(c,g.Iw(d)))}};
g.k.xa=function(){this.Ta.clear();this.Wa.clear();g.O.prototype.xa.call(this)};
g.k.createElement=function(a){a=new g.U(a);g.P(this,a);return a.element};g.z(reb,Y2);g.k=reb.prototype;g.k.uu=function(){this.qa&&c3(this,this.qa)};
g.k.isAvailable=function(){var a;if(a=!!this.cards.length)(a=this.J.getRootNode())?(a=g.Jm(a),a=173<a.width&&173<a.height):a=!1;return a};
g.k.vJ=function(){var a=this.isAvailable();g.Km(this.Ib(),a);g.up(this.context.J.getRootNode(),g.F_.IV_DRAWER_ENABLED,a);D2(this.J)};
g.k.destroy=function(){this.J.AC(!1);try{this.J.getRootNode().removeChild(this.D)}catch(a){}g.wv(this.oa);g.Ms(this.Na);this.Ua&&this.Ua.dispose();this.G&&this.G.dispose();Y2.prototype.destroy.call(this)};
g.k.hJ=function(){var a=this,b=g.dh("iv-drawer-close-button",this.D);this.context.j.listen(b,"click",this.a8,this);this.context.j.listen(this.B,"touchend",function(){a.Ca.start()});
this.context.j.listen(this.B,"scroll",this.z8,this);this.context.B.subscribe("onHideControls",function(){a.La=!0});
this.context.B.subscribe("onShowControls",function(){a.La=!1});
this.context.B.subscribe("onVideoAreaChange",function(){a.La=g.pp(a.J.getRootNode(),"ytp-autohide")});
this.oa.push(g.vv("iv-button-shown",this.caa,this));this.oa.push(g.vv("iv-button-hidden",this.baa,this));yeb(this)};
g.k.findLastIndex=function(a){if(this.cards.length===0)return 0;var b=g.Qb(this.cards,function(c){return a.xf.startMs>c.xf.startMs||a.xf.startMs===c.xf.startMs&&a.xf.timestamp>=c.xf.timestamp?!0:!1});
return b===-1?0:b+1};
g.k.a8=function(){if(this.C){j3(this.context.logger,g3(this).tj.close);var a=g.Lw();a&&this.N&&g.qx(a,this.N);b3(this)}};
g.k.z8=function(){g.up(this.D,"iv-drawer-scrolled",this.B.scrollTop>0)};
g.k.caa=function(){var a=g.Lw(),b=g3(this);b=b?b.Df:this.Df;a&&b&&g.ox(a,[b])};
g.k.baa=function(){var a=g.Lw(),b=g3(this);b=b?b.Df:this.Df;a&&b&&g.px(a,[b])};
g.k.c5=function(){var a=g3(this);j3(this.context.logger,a.tj.m3);var b=g.Lw();if(b&&a)if(this.J.L("web_infocards_teaser_show_logging_fix")){var c=[];a.ek&&c.push(a.ek);a.Df&&c.push(a.Df);c.length>0&&g.ox(b,c)}else g.ox(b,[a.ek,a.Df])};
g.k.eaa=function(){var a=g.Lw(),b=g3(this);a&&b&&g.px(a,[b.ek])};
g.k.b5=function(a){var b=g3(this),c=g.Lw();this.j?a?(a=this.context.logger,j3(a,b.tj.hN),a.J.sendVideoStatsEngageEvent(4,void 0),c&&b.ek&&g.qx(c,b.ek)):(a=this.context.logger,j3(a,b.tj.hN),a.J.sendVideoStatsEngageEvent(4,void 0),c&&b.Df&&g.qx(c,b.Df)):(a=this.context.logger,j3(a,b.tj.hN),a.J.sendVideoStatsEngageEvent(4,void 0),c&&this.Df&&g.qx(c,this.Df))};g.z(h3,Y2);h3.prototype.aI=function(){Y2.prototype.aI.call(this);Feb(this)};
h3.prototype.show=function(){Y2.prototype.show.call(this);var a=g.Lw(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.ox(a,[g.Iw(b.itct)])};
h3.prototype.hide=function(){Y2.prototype.hide.call(this);var a=g.Lw(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.px(a,[g.Iw(b.itct)])};g.z(i3,h3);
i3.prototype.Vy=function(){g.qp(this.Ib(),"iv-branding");var a=this.annotation.data;this.B=this.createElement({I:"img",Ka:["branding-img","iv-click-target"],X:{"aria-label":"Channel watermark",src:a.image_url,width:a.image_width,height:a.image_height}});g.Km(this.B,!1);var b=this.createElement({I:"button",Ka:["branding-img-container","ytp-button"]});b.appendChild(this.B);this.Ib().appendChild(b);var c=this.annotation.De();c&&Z2(this,b,c,this.annotation.id,a.session_data);this.context.J.L("disable_branding_context")||Jeb(this,
a)};
i3.prototype.show=function(){if(!this.isActive&&(h3.prototype.show.call(this),this.N||(this.Vy(),this.N=!0),g.Km(this.Ib(),!0),this.isActive=!0,this.B)){try{Geb(this,this.B)}catch(a){}g.qp(this.context.J.getRootNode(),"ytp-branding-shown")}};
i3.prototype.hide=function(){this.isActive&&(h3.prototype.hide.call(this),g.Km(this.Ib(),!1),this.isActive=!1,g.sp(this.context.J.getRootNode(),"ytp-branding-shown"))};
i3.prototype.destroy=function(){this.j&&(this.j.dispose(),this.j=null);h3.prototype.destroy.call(this)};g.z(Leb,h3);g.k=Leb.prototype;
g.k.Vy=function(){var a=this,b=this.annotation.data;if(this.annotation.style==="cta")var c=6;else if(this.annotation.style==="video"||this.annotation.style==="playlist")c=7;this.K=b.collapsedelay_ms||this.K;var d=["iv-promo","iv-promo-inactive"];this.Ib().setAttribute("aria-hidden","true");this.Ib().setAttribute("aria-label","Promotion");this.Ib().tabIndex=0;var e=this.annotation.De(),f=b.image_url;if(f){var h=this.createElement({I:"div",Ka:["iv-promo-img","iv-click-target"]});f=this.createElement({I:"img",
X:{src:f,"aria-hidden":"true"}});h.appendChild(f);b.video_duration&&!b.is_live?(f=this.createElement({I:"span",S:"iv-promo-video-duration",va:b.video_duration}),h.appendChild(f)):b.playlist_length&&(f=this.createElement({I:"span",S:"iv-promo-playlist-length",va:b.playlist_length.toString()}),h.appendChild(f));e&&Z2(this,h,e,this.annotation.id,b.session_data,void 0,c)}e?(f=this.createElement({I:"a",S:"iv-promo-txt"}),g.Rf(f,T2(e)),this.j=f):this.j=this.createElement({I:"div",S:"iv-promo-txt"});switch(this.annotation.style){case "cta":case "website":var l=
this.createElement({I:"p",V:[{I:"strong",va:b.text_line_1}]});var m=this.createElement({I:"p",V:[{I:"span",S:"iv-promo-link",va:b.text_line_2}]});if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");var n=this.createElement({I:"button",Ka:["iv-promo-round-expand-icon","ytp-button"]});f=this.createElement({I:"button",Ka:["iv-button","iv-promo-button"],V:[{I:"span",S:"iv-button-content",va:f}]});var p=this.createElement({I:"div",S:"iv-promo-button-container"});p.appendChild(f);e&&Z2(this,
this.Ib(),e,this.annotation.id,b.session_data,void 0,c)}g.qp(this.j,"iv-click-target");e&&Z2(this,this.j,e,this.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=this.createElement({I:"p",V:[{I:"span",va:b.text_line_1}]}),m=this.createElement({I:"p",V:[{I:"strong",va:b.text_line_2}]}),b.is_live&&(l=m,m=this.createElement({I:"span",Ka:["yt-badge","iv-promo-badge-live"],va:"LIVE NOW"})),g.qp(this.j,"iv-click-target"),e&&Z2(this,this.j,e,this.annotation.id,b.session_data,void 0,
c),d.push("iv-promo-video")}l&&this.j.appendChild(l);m&&this.j.appendChild(m);this.N.appendChild(this.j);p&&this.N.appendChild(p);c=this.createElement({I:"div",S:"iv-promo-actions"});this.B=this.createElement({I:"button",Ka:["iv-promo-expand","ytp-button"]});this.B.title="Expand";this.context.j.listen(this.B,"click",function(q){Oeb(a,5E3,q)});
c.appendChild(this.B);g.Km(this.B,!1);this.context.j.listen(this.Ib(),"mouseover",this.b$,this);this.context.j.listen(this.Ib(),"mouseout",this.a$,this);this.context.j.listen(this.Ib(),"touchend",function(q){Oeb(a,5E3,q)});
this.C=this.createElement({I:"button",Ka:["iv-promo-close","ytp-button"]});this.C.title="Close";this.context.j.listen(this.C,"click",this.annotation.style==="cta"&&b.text_line_3?this.W9:this.V9,this);c.appendChild(this.C);g.rp(this.Ib(),d);h&&(g.lh(this.Ib(),h),n&&h.appendChild(n));g.lh(this.Ib(),this.N);g.lh(this.Ib(),c)};
g.k.show=function(){this.isActive||(h3.prototype.show.call(this),this.W||(this.Vy(),this.W=!0),g.Km(this.Ib(),!0),g.Gi(function(){g.sp(this.Ib(),"iv-promo-inactive")},100,this),this.Ib().removeAttribute("aria-hidden"),this.isActive=!0,Qeb(this),Meb(this),Neb(this,this.K))};
g.k.hide=function(){this.isActive&&(g.qp(this.Ib(),"iv-promo-inactive"),this.isActive=!1,this.Ib().setAttribute("aria-hidden","true"))};
g.k.oO=function(a,b,c,d,e,f){return this.isCollapsed?!1:h3.prototype.oO.call(this,a,b,c,d,e,f)};
g.k.b$=function(a){this.Z=!0;Oeb(this,500,a)};
g.k.a$=function(){this.Z=!1;Peb(this)};
g.k.V9=function(a){a.stopPropagation();this.hide()};
g.k.W9=function(a){a.stopPropagation();Qeb(this);this.isCollapsed=!0;g.qp(this.Ib(),"iv-promo-collapsed-no-delay");this.G.start()};
g.k.destroy=function(){this.G.dispose();h3.prototype.destroy.call(this)};g.z(Seb,g.UX);g.k=Seb.prototype;g.k.ai=function(a,b){if(!gfb(this.player.U().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":return(a=g.a1(b))&&Xeb(this,a),!0;case "removeCustomAnnotationById":return b&&this.j&&(veb(this.j,b),D2(this.player)),!0}return null};
g.k.getOptions=function(){return gfb(this.player.U().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.k.Dv=function(){var a=this.player.U(),b=this.player.getVideoData(),c=a.annotationsLoadPolicy||b.annotationsLoadPolicy;return g.CR(b)||this.player.isMutedByEmbedsMutedAutoplay()?!1:c===1&&!b.s2||a.La.get(b.videoId)||g.pR(b)||g.qR(b)?!0:!1};
g.k.XL=function(){if(this.C){var a=this.player.ob().getVideoContentRect(!0);g.Im(this.C.element,a.width,a.height);g.Em(this.C.element,a.left,a.top)}if(this.j){var b=this.player.Fo();a=this.j;b=b.width;g.up(a.D,"iv-drawer-small",b<=426);g.up(a.D,"iv-drawer-big",b>=1280)}};
g.k.d5=function(a){Ueb(this,a.state);g.Z(a.state,2)&&(this.Dl()&&this.Vp()&&this.player.getPresentingPlayerType()!==2&&this.BC(!1),this.AC(!1))};
g.k.load=function(){function a(h){var l=b.loadNumber;b.G=null;b.loaded&&b.loadNumber===l&&b.player.getVideoData().videoId===d&&(h=g.xr(h)&&h.responseXML?h.responseXML:null)&&(Xeb(b,h),g.qp(b.player.getRootNode(),"iv-module-loaded"))}
var b=this;g.UX.prototype.load.call(this);Ueb(this,this.player.getPlayerStateObject());this.loadNumber++;var c=this.player.getVideoData(),d=c.videoId;g.kt()&&(a=Yeb(this,a));var e={format:"XML",onFinish:a,onError:function(){b.G=null},
urlParams:{}};c.isPharma&&(e.urlParams.pharma="1");e.method="POST";e.withCredentials=!0;var f=this.player.U().La.get(d);f&&Zeb(e,f);f=f&&(f.XO||f.AJ);if(!c.jw||f)c.Ta?Veb(this,c.Ta,e):(this.N=function(){if(!b.Z)b.onVideoDataChange(e);var h=b.player.getVideoData();(h==null?0:g.oR(h))&&!b.oa&&cfb(b,h)},this.player.addEventListener("videodatachange",this.N));
g.gS(this.player,this.C.element,4);this.XL();(f=g.pR(c))&&bfb(this,f);(f=g.qR(c))&&f.featuredChannel&&ffb(this,f.featuredChannel,f.annotationId||"branding",c.videoId||null,c.eventId||null);this.hh=g.dh("ytp-cards-button",this.player.getRootNode());g.oR(c)&&cfb(this,c)};
g.k.onVideoDataChange=function(a){var b=this.player.getVideoData();b.Ta&&Veb(this,b.Ta,a)};
g.k.unload=function(){this.player.gf("annotations_module");for(var a=g.w(Object.keys(this.K)),b=a.next();!b.done;b=a.next())this.K[b.value].destroy();this.W=null;this.j&&(this.j.destroy(),this.j=null,D2(this.player));this.Z=!1;this.G&&(this.G.abort(),this.G=null);this.oa=!1;this.K={};this.B.hide();g.UX.prototype.unload.call(this);this.C.detach();this.N&&(this.player.removeEventListener("videodatachange",this.N),this.N=null)};
g.k.b1=function(a){a===this.player.getVideoData().videoId&&(this.loaded?$eb(this):this.load())};
g.k.Dl=function(){var a;return((a=this.j)==null?void 0:a.isAvailable())||this.oa};
g.k.Vp=function(){return!!this.j&&this.j.C};
g.k.BC=function(a,b,c){b=b===void 0?!1:b;this.Dl();this.j&&(a?c?a3(this.j,c,b):a3(this.j,"YOUTUBE_DRAWER_AUTO_OPEN",b):b3(this.j))};
g.k.AC=function(a,b){this.player.publish(a?"cardsteasershow":"cardsteaserhide",b)};
g.k.xa=function(){this.player.U().La.unsubscribe("vast_info_card_add",this.b1,this);g.sp(this.player.getRootNode(),g.F_.IV_DRAWER_OPEN);for(var a=this.qa,b=g.bp,c=0,d=a.length;c<d;c++)b.Dj(a[c]);this.qa.length=0;g.UX.prototype.xa.call(this)};
g.k.createElement=function(a){a=new g.U(a);g.P(this,a);return a.element};g.TX("annotations_module",Seb);g.TX("creatorendscreen",Odb);})(_yt_player);
