(function(g){var window=this;'use strict';var nfb=function(a,b,c){var d;g.J(function(e){switch(e.j){case 1:var f=b;a.Y.L("web_player_pt_tt")?(f=g.nr(f).exp||"",f=f.includes("xpv")||f.includes("xpe")):f=!1;if(!f){e.Ea(2);break}if(a.videoData.Bw){e.Ea(3);break}g.wa(e,4);return g.G(e,a.D.promise,6);case 6:g.xa(e,3);break;case 4:return g.ya(e),e.return();case 3:d={potc:"1",pot:a.videoData.Bw},b=g.or(b,d);case 2:a.j=g.Ir(b,c),g.va(e)}})},l3=function(a){a.isActive()||a.start()},ofb=function(a,b){return b?a.captionsInitialState:"CAPTIONS_INITIAL_STATE_UNKNOWN"},
pfb=function(a,b){var c=new g.UP;
c.languageCode=a.languageCode;c.languageName=a.languageName;c.name=a.name;c.displayName=a.displayName;c.kind=a.kind;c.isDefault=!1;c.j=a.j;c.isTranslateable=a.isTranslateable;c.vssId=a.vssId;c.url=a.url;c.translationLanguage=b;a.xtags&&(c.xtags=a.xtags);a.captionId&&(c.captionId=a.captionId);return c},qfb=function(a,b){var c,d,e;
return g.J(function(f){if(f.j==1)return c=a+"|"+b,g.G(f,g.iu(),2);if(f.j!=3){d=f.B;if(!d)throw g.Gt("gct");return g.G(f,g.lQ(d),3)}e=f.B;return f.return(e.get("captions",c))})},rfb=function(a,b,c){qfb(a,b).then(function(d){d&&c(d.trackData,new g.UP(d.metadata))})},ufb=function(a){if(!sfb.test(a))throw Error("'"+a+"' is not a valid hex color");
a.length==4&&(a=a.replace(tfb,"#$1$1$2$2$3$3"));a=a.toLowerCase();a=parseInt(a.slice(1),16);return[a>>16,a>>8&255,a&255]},vfb=function(){var a=void 0;
a=a===void 0?{}:a;var b="suggest_correction"in g.acb?g.acb.suggest_correction:"Edit caption";b=b||"";var c={},d;for(d in a){c={rG:c.rG};c.rG=d;var e=function(f){return function(){return String(a[f.rG])}}(c);
b=b.replace(new RegExp("\\$\\{"+c.rG+"\\}","gi"),e);b=b.replace(new RegExp("\\$"+c.rG,"gi"),e)}return b},wfb=function(){return g.Rs("yt-player-caption-display-settings")},m3=function(){this.segments=[]},xfb=function(a,b){var c=g.bc(a.segments,b);
c>=0||c<0&&(-c-1)%2===1||(c=-c-1,c>0&&b-a.segments[c-1]===1&&c<a.segments.length&&a.segments[c]-b===1?(g.Tb(a.segments,c),g.Tb(a.segments,c-1)):c>0&&b-a.segments[c-1]===1?a.segments[c-1]=b:c<a.segments.length&&a.segments[c]-b===1?a.segments[c]=b:(g.$b(a.segments,c,0,b),g.$b(a.segments,c+1,0,b)))},yfb=function(a,b,c,d,e,f){g.O.call(this);
this.policy=a;this.player=b;this.oa=c;this.Z=d;this.G=e;this.W=f;this.D=new m3;this.K=-1;this.C=this.B=this.j=null;this.N=new g.ip(this.B_,1E3,this);this.events=new g.PF(this);g.P(this,this.N);g.P(this,this.events);this.events.T(b,"SEEK_COMPLETE",this.RB);this.RB();this.B_()},zfb=function(a){return a.j&&a.j.Pf?a.j.Pf+a.player.Ac()<a.player.getCurrentTime():!1},Afb=function(a,b){if(a.policy.zm&&a.player.ju()){var c=g.oN(b,a.policy,{});
c.set("pot",a.player.ju());c=c.De()}else c=g.oN(b,a.policy,{}).De();var d={format:"RAW",withCredentials:!0};if(a.policy.La){d.method="POST";var e=b.D;e&&Object.keys(e).length>0?d.postBody=g.tB(e,g.AL):d.postBody=(0,g.MT)([120,0])}a.G&&(d.responseType="arraybuffer");a.C=g.Mr(c,d,3,100).then(function(f){a:{f=f.xhr;a.Ia();if(a.B){var h=!(a.G?f.response:f.responseText)||f.status>=400,l=g.iFa(f);if(l){f=g.oN(a.B,a.policy,{});a.B.Ol(f,l);Afb(a,a.B);break a}h?a.player.ma("capfail",{status:f.status}):(a.player.Kh().gg("fcb_r"),
l=a.B.gb[0].Oa,a.Z!=null&&a.K!==l&&(h=a.B.gb[0],a.G?a.Z(f.response,(h.startTime+a.player.Ac())*1E3):a.Z(f.responseText,(h.startTime+a.player.Ac())*1E3),a.K=l))}a.B=null;a.C=null}}).al(function(f){a.B=null;
a.C=null;var h;a.player.ma("capfail",{status:(h=f.xhr)==null?void 0:h.status})});
a.B=b;xfb(a.D,a.B.gb[0].Oa)},n3=function(a,b){g.XX.call(this,b.U());
this.j=a;this.J=b;this.C=null;this.K=!1;this.N=g.LD(this.J.U())&&!this.j.isManifestless},Cfb=function(a,b){var c=[],d;
for(d in a.j.j)if(a.j.j.hasOwnProperty(d)){var e=a.j.j[d];if(g.Q_a(e,b||null)){var f=e.info.id,h=f,l="."+f,m="",n="",p="";if(e=e.info.captionTrack)f=e.languageCode,h=e.displayName,l=e.vssId,m=e.kind,a.J.U().L("html5_expose_xtags_through_caption_track")&&(n=e.xtags),p=e.id;else{e=f;var q=g.pdb.get(e);q==null&&(q=Bfb[e]||Bfb[e.replace(/-/g,"_")],g.pdb.set(e,q));h=q||h}c.push(new g.UP({id:d,languageCode:f,languageName:h,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:l,kind:m,xtags:n,captionId:p}))}}return c},
Dfb=function(a,b){return b!=null&&b in a.j.j?a.j.j[b]:null},Efb=function(a,b,c){var d=[],e;
for(e in a.j.j)if(a.j.j.hasOwnProperty(e)){var f=a.j.j[e];if(g.Q_a(f,c||null)){var h=f.info.captionTrack;h&&h.languageCode===b&&d.push(f)}}return d.length?d[0]:null},o3=function(a,b,c,d,e,f,h,l,m,n){var p=n.isInline()&&!0,q={};
Object.assign(q,b);Object.assign(q,a.params);Object.assign(q,c);var r={};Object.assign(r,b.Oe);a.params.Oe&&Object.assign(r,a.params.Oe);Object.assign(r,c.Oe);p&&(q.windowOpacity=.6,r.backgroundOpacity=0);q.Oe=r;var t=q.Si===1,u=[{I:"span",S:"captions-text",X:{style:"word-wrap: normal; display: block;"}}],y,A,C;(l=l.bb("caption_edit_on_hover")&&((y=n.getVideoData().getPlayerResponse())==null?void 0:(A=y.captions)==null?void 0:(C=A.playerCaptionsTracklistRenderer)==null?void 0:C.openTranscriptCommand))&&
u.unshift({I:"button",S:"caption-edit",X:{tabindex:"0","aria-label":vfb()},V:[{I:"svg",X:{fill:"#e3e3e3",height:"100%",viewBox:"5 5 38 38",width:"100%"},V:[{I:"path",X:{d:"M9 39h2.2l24.25-24.25-1.1-1.1-1.1-1.1L9 36.8Zm-3 3v-6.4L35.4 6.2q.85-.85 2.12-.82 1.27.02 2.12.87L41.8 8.4q.85.85.85 2.1t-.85 2.1L12.4 42Zm33.5-31.55L37.45 8.4Zm-4.05 4.3-1.1-1.1-1.1-1.1 2.2 2.2Z"}}]}]});g.U.call(this,{I:"div",S:"caption-window",X:{id:"caption-window-"+a.id,dir:t?"rtl":"ltr",tabindex:"0",lang:q.lang},V:u});var F=
this;this.K=[];this.Fa=!1;this.B=a;this.La=this.Ja=null;this.playerWidth=f;this.playerHeight=h;this.N=null;this.maxWidth=f*.96;this.maxHeight=h*.96;this.j=q;this.wc=c;this.qa=b;this.D=this.Da("captions-text");this.Nb=this.D.style.getPropertyValue("box-decoration-break")!==""||this.D.style.getPropertyValue("-webkit-box-decoration-break")!=="";this.Ua=Ffb(d,e,f,h);this.pc=m;l&&(this.G=this.Da("caption-edit"),this.T(this.G,"click",function(){F.pc()}));
this.type=0;this.Wa=this.Ua*Gfb(r);this.Ab=p;a=new g.xX(this.element,!0);g.P(this,a);a.subscribe("dragstart",this.g5,this);a.subscribe("dragmove",this.f5,this);a.subscribe("dragend",this.e5,this);this.ib=this.Va=this.qb=this.kb=0;a="";this.j.windowOpacity&&(a=ufb(this.j.windowColor),a="rgba("+a[0]+","+a[1]+","+a[2]+","+this.j.windowOpacity+")");b={"background-color":a,display:this.j.isVisible===!1?"none":"","text-align":Hfb[this.j.textAlign]};this.Nb&&(b["border-radius"]=a?this.Wa/8+"px":"");(this.C=
this.B.params.Si===2||this.B.params.Si===3)&&Ifb(this,this.element);g.xm(this.element,b);if(p){var H;(H=this.element.parentElement)==null||H.style.setProperty("--caption-window-color",a)}switch(this.j.Lm){case 0:case 1:case 2:g.qp(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.qp(this.element,"ytp-caption-window-bottom")}},Ifb=function(a,b){var c="vertical-rl";
a.j.HU===1&&(c="vertical-lr");g.zm&&(c=c==="vertical-lr"?"tb-lr":"tb-rl");g.xm(b,"-o-writing-mode",c);g.xm(b,"-webkit-writing-mode",c);g.xm(b,"writing-mode",c);g.xm(b,"text-orientation","upright");g.qp(b,"ytp-vertical-caption");a.B.params.Si===3&&(g.xm(b,"text-orientation",""),g.xm(b,"transform","rotate(180deg)"))},Gfb=function(a){var b=1+.25*(a.fontSizeIncrement||0);
if(a.offset===0||a.offset===2)b*=.8;return b},Jfb=function(a,b){var c={},d=b.background?b.background:a.j.Oe.background;
if(b.backgroundOpacity!=null||b.background){var e=b.backgroundOpacity!=null?b.backgroundOpacity:a.j.Oe.backgroundOpacity;d=ufb(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.Nb&&(c["box-decoration-break"]="clone",c["border-radius"]=a.Wa/8+"px")}if(b.fontSizeIncrement!=null||b.offset!=null)c["font-size"]=a.Ua*Gfb(b)+"px";d=1;e=b.color||a.j.Oe.color;if(b.color||b.textOpacity!=null)e=ufb(e),d=b.textOpacity==null?a.j.Oe.textOpacity:b.textOpacity,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",
c.color=e,c.fill=e;var f=b.charEdgeStyle;f===0&&(f=void 0);if(f){e="rgba(34, 34, 34, "+d+")";var h="rgba(204, 204, 204, "+d+")";b.YO&&(h=e=b.YO);var l=a.Ua/16/2,m=Math.max(l,1),n=Math.max(2*l,1),p=Math.max(3*l,1),q=Math.max(5*l,1);d=[];switch(f){case 4:for(;p<=q;p+=l)d.push(n+"px "+n+"px "+p+"px "+e);break;case 1:n=window.devicePixelRatio>=2?.5:1;for(f=m;f<=p;f+=n)d.push(f+"px "+f+"px "+e);break;case 2:d.push(m+"px "+m+"px "+h);d.push("-"+m+"px -"+m+"px "+e);break;case 3:for(p=0;p<5;p++)d.push("0 0 "+
n+"px "+e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case 1:e='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:e=g.$r()?
'"Carrois Gothic SC", sans-serif-smallcaps':'Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:e='"YouTube Noto", Roboto, Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;e==null&&(e=a.j.Oe.offset);switch(e){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}b.fontFamily===7&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.italic&&(c["font-style"]="italic");b.underline&&(c["text-decoration"]=
"underline");b.v$&&(c.visibility="hidden");b.HZ===1&&a.C&&(c["text-combine-upright"]="all",c["text-orientation"]="mixed",e=g.GP||g.Et,a.B.params.Si===3?c.transform=e?"rotate(90deg)":"rotate(180deg)":e&&(c.transform="rotate(-90deg)"));if(b.vp===1||b.vp===2||b.vp===3||b.vp===4||b.vp===5)if(g.GP)c["font-weight"]="bold";else switch(c["text-emphasis-style"]="filled circle",c["text-emphasis-color"]="currentcolor",c["webkit-text-emphasis"]="filled circle",b.vp){case 4:case 3:c["text-emphasis-position"]=
"under left";c["webkit-text-emphasis-position"]="under left";break;case 5:case 2:c["text-emphasis-position"]="over right",c["webkit-text-emphasis-position"]="over right"}return c},p3=function(a){a=a.split("px");
return a.length>0?(a=Number(a[0]))?a:0:0},Kfb=function(a){a.N=g.jh("SPAN");
g.xm(a.N,{display:"block"});g.qp(a.N,"caption-visual-line");a.D.appendChild(a.N)},Lfb=function(a,b){var c=g.jh("SPAN");
g.xm(c,{display:"inline-block","white-space":"pre-wrap"});g.xm(c,Jfb(a,b));c.classList.add("ytp-caption-segment");a.N.appendChild(c);c.previousElementSibling&&(g.xm(c.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.xm(c,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return c},Mfb=function(a,b,c){a.Fa=a.Fa||!!c;
var d={};Object.assign(d,a.j.Oe);Object.assign(d,c||b.j);Object.assign(d,a.wc.Oe);(c=!a.N)&&Kfb(a);for(var e=a.Ja&&a.La&&g.Qg(d,a.La)?a.Ja:Lfb(a,d),f=typeof b.text==="string",h=f?b.text.split("\n"):[b.text],l=0;l<h.length;l++){var m=l>0||!b.append,n=h[l];m&&!c?(Kfb(a),e=Lfb(a,d)):m&&c&&(c=!1);n&&(e.appendChild(f?g.kh(n):n),f||n.tagName!=="RUBY"||n.childElementCount!==4||g.GP||!g.Am(n.children[2],"text-emphasis")||(m=a.C?"padding-right":"padding-top",g.Am(n.children[2],"text-emphasis-position")&&(m=
a.C?"padding-left":"padding-bottom"),g.fh?g.xm(e,m,"1em"):g.xm(e,m,"0.5em")))}a.La=d;a.Ja=e;a.K.push(b)},Ffb=function(a,b,c,d){var e=b/360*16;
b>=a&&(a=640,d>c*1.3&&(a=480),e=c/a*16);return e},Ofb=function(){this.C=this.time=this.mode=this.B=0;
this.D=new Nfb(this);this.G=new Nfb(this);this.j=[];this.clear()},Qfb=function(a,b,c){if(a===255&&b===255||!a&&!b)return{Tw:a,
Kt:b,result:0};a=Pfb[a];b=Pfb[b];if(a&128){var d;if(d=!(b&128))d=b,d=c.qe()&&c.Kt===d;if(d)return{Tw:a,Kt:b,result:1}}else if(b&128&&1<=a&&a<=31)return{Tw:a,Kt:b,result:2};return{Tw:a,Kt:b,result:3}},Sfb=function(a,b,c,d){b===255&&c===255||!b&&!c?(++a.C===45&&a.reset(),a.D.B.clear(),a.G.B.clear()):(a.C=0,Rfb(a.D,b,c,d))},Tfb=function(a,b){a.j.sort(function(e,f){var h=e.time-f.time;
return h===0?e.order-f.order:h});
for(var c=g.w(a.j),d=c.next();!d.done;d=c.next())d=d.value,a.time=d.time,d.type===0?Sfb(a,d.IX,d.JX,b):d.type===1&&a.B&496&&Rfb(a.G,d.IX,d.JX,b);a.j.length=0},q3=function(){this.type=0},r3=function(){this.state=this.Kt=this.Tw=0},Ufb=function(){this.timestamp=this.j=0},s3=function(a){this.D=a;
this.B=[];this.j=this.col=this.row=0;this.style=new q3;for(a=this.C=0;a<=15;a++){this.B[a]=[];for(var b=0;b<=32;b++)this.B[a][b]=new Ufb}},t3=function(a,b){if(a.style.type===3){for(var c=0,d=0,e=a.D.time+0,f="",h="",l=e,m=1;m<=15;++m){for(var n=!1,p=d?d:1;p<=32;++p){var q=a.B[m][p];
if(q.j!==0){c===0&&(c=m,d=p);n=String.fromCharCode(q.j);var r=q.timestamp;r<e&&(e=r);q.timestamp=l;h&&(f+=h,h="");f+=n;n=!0}if((q.j===0||p===32)&&n){h="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.D(c,d,e,l,f)}else for(d=c=0,f=e=a.D.time+0,h=1;h<=15;++h)for(l="",m=1;m<=32;++m)if(p=a.B[h][m],q=p.j,q!==0&&(c===0&&(c=h,d=m),n=String.fromCharCode(q),r=p.timestamp,r<=e&&(e=r),l+=n,p.reset()),m===32||q===0)l&&b.D(c,d,e,f,l),e=f,l="",d=c=0},qgb=function(a,b){switch(a){case 0:return Vfb[(b&127)-32];
case 1:return Wfb[b&15];case 2:return Xfb[b&31];case 3:return pgb[b&31]}return 0},u3=function(a){return a.B[a.row][a.col]},v3=function(a,b,c){b>=2&&a.col>1&&(--a.col,u3(a).j=0);
var d=u3(a);d.timestamp=a.D.time+0;d.j=qgb(b,c);a.col<32&&a.col++},rgb=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;f<=32;f++){var h=a.B[b+e][f],l=a.B[c+e][f];
h.j=l.j;h.timestamp=l.timestamp}},w3=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;e<=32;e++)a.B[b+d][e].reset()},sgb=function(a){a.row=a.j>0?a.j:1;
a.col=1;w3(a,0,15)},tgb=function(a){this.C=a;
this.G=0;this.style=new q3;this.K=new s3(this.C);this.N=new s3(this.C);this.text=new s3(this.C);this.B=this.K;this.D=this.N;this.j=this.B},ugb=function(a,b,c){var d=a.B,e=!1;
switch(a.style.get()){case 4:case 1:case 2:a.style.get()===4&&d.j>0||(t3(d,c),sgb(a.B),sgb(a.D),d.row=15,d.j=b,e=!0)}a.style.set(3);a.j=d;a.j.style=a.style;a.C.mode=1<<d.C;e?d.col=1:d.j!==b&&(d.j>b?(t3(d,c),w3(d,d.row-d.j,b)):d.row<b&&(b=d.j),d.j=b)},vgb=function(a){a.style.set(1);
a.j=a.D;a.j.j=0;a.j.style=a.style;a.C.mode=1<<a.j.C},wgb=function(a){a.style.set(4);
a.j=a.text;a.j.style=a.style;a.C.mode=1<<a.j.C},Nfb=function(a){this.j=a;
this.G=0;this.C=new tgb(this.j);this.K=new tgb(this.j);this.B=new r3;this.D=this.C},Rfb=function(a,b,c,d){a.B.update();
b=Qfb(b,c,a.B);switch(b.result){case 0:return;case 1:case 2:return}var e=b.Tw;c=b.Kt;if(32<=e||!e)a.j.mode&a.j.B&&(b=e,b&128&&(b=127),c&128&&(c=127),a=a.D.j,b&96&&v3(a,0,b),c&96&&v3(a,0,c),b!==0&&c!==0&&a.style.type===3&&t3(a,d));else if(e&16)a:if(!a.B.matches(e,c)&&(b=a.B,b.Tw=e,b.Kt=c,b.state=2,b=e&8?a.K:a.C,a.D=b,a.j.mode=1<<(a.G<<2)+(b.G<<1)+(b.style.type===4?1:0),(a.j.mode|1<<(a.G<<2)+(b.G<<1)+(b.style.type!==4?1:0))&a.j.B))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];
a=c&16?((c&14)>>1)*4:0;c=b.j;switch(b.style.get()){case 4:d=c.row;break;case 3:if(d!==c.row){if(d<c.j&&(d=c.j,d===c.row))break;var f=1+c.row-c.j,h=1+d-c.j;rgb(c,h,f,c.j);b=f;e=c.j;h<f?(f=h+e-f,f>0&&(b+=f,e-=f)):(f=f+e-h,f>0&&(e-=f));w3(c,b,e)}}c.row=d;c.col=a+1}else switch(e&7){case 1:switch(c&112){case 32:v3(b.j,0,32);break a;case 48:c===57?(d=b.j,u3(d).j=0,d.col<32&&d.col++):v3(b.j,1,c&15)}break;case 2:c&32&&v3(b.j,2,c&31);break;case 3:c&32&&v3(b.j,3,c&31);break;case 4:case 5:if(32<=c&&c<=47)switch(c){case 32:vgb(b);
break;case 33:d=b.j;d.col>1&&(--d.col,u3(d).j=0);break;case 36:d=b.j;b=u3(d);for(a=0;a<=15;a++)for(c=0;c<=32;c++)if(d.B[a][c]===b){for(;c<=32;c++)d.B[a][c].reset();break}break;case 37:ugb(b,2,d);break;case 38:ugb(b,3,d);break;case 39:ugb(b,4,d);break;case 40:v3(b.j,0,32);break;case 41:b.style.set(2);b.j=b.B;b.j.j=0;b.j.style=b.style;b.C.mode=1<<b.j.C;break;case 42:d=b.text;d.j=15;d.style.set(4);sgb(d);wgb(b);break;case 43:wgb(b);break;case 44:a=b.B;switch(b.style.get()){case 1:case 2:case 3:t3(a,
d)}w3(a,0,15);break;case 45:b:{a=b.j;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(a.row<15){++a.row;a.col=1;break b}break;case 3:}a.j<2&&(a.j=2,a.row<a.j&&(a.row=a.j));b=a.row-a.j+1;t3(a,d);rgb(a,b,b+1,a.j-1);w3(a,a.row,1)}break;case 46:w3(b.D,0,15);break;case 47:t3(b.B,d),b.D.updateTime(b.C.time+0),d=b.D,b.D=b.B,b.B=d,vgb(b)}break;case 7:switch(c){case 33:case 34:case 35:d=b.j,(d.col+=c&3)>32&&(d.col=32)}}},xgb=function(){},x3=function(a,b,c,d,e,f,h){f=f===void 0?!1:f;
h=h===void 0?null:h;g.pE.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.append=f;this.j=h},zgb=function(a,b,c,d,e,f,h){var l=f[0],m=h[l.getAttribute("p")];
if(m.fg===1){var n=f[1],p=f[2];f=f[3];l.getAttribute("t");n.getAttribute("t");p.getAttribute("t");f.getAttribute("t");l.getAttribute("p");n.getAttribute("p");f.getAttribute("p");h=h[p.getAttribute("p")];l=ygb(l.textContent,n.textContent,p.textContent,f.textContent,h);return new x3(a,b,e,c,l,d,m)}switch(m.fg){case 9:case 10:m.vp=1;break;case 11:m.vp=2;break;case 12:m.vp=3;break;case 13:m.vp=4;break;case 14:m.vp=5}return new x3(a,b,e,c,l.textContent||"",d,m)},ygb=function(a,b,c,d,e){var f=g.$r(),h=
f?g.jh("DIV"):g.jh("RUBY"),l=g.jh("SPAN");
l.textContent=a;h.appendChild(l);a=f?g.jh("DIV"):g.jh("RP");a.textContent=b;h.appendChild(a);b=f?g.jh("DIV"):g.jh("RT");b.textContent=c;h.appendChild(b);c=e.fg;if(c===10||c===11||c===12||c===13||c===14)if(g.xm(b,"text-emphasis-style","filled circle"),g.xm(b,"text-emphasis-color","currentcolor"),g.xm(b,"webkit-text-emphasis","filled circle"),e.fg===11||e.fg===13)g.xm(b,"webkit-text-emphasis-position","under left"),g.xm(b,"text-emphasis-position","under left");c=!0;if(e.fg===4||e.fg===7||e.fg===12||
e.fg===14)g.xm(h,"ruby-position","over"),g.xm(h,"-webkit-ruby-position","before");else if(e.fg===5||e.fg===6||e.fg===11||e.fg===13)g.xm(h,"ruby-position","under"),g.xm(h,"-webkit-ruby-position","after"),c=!1;e=f?g.jh("DIV"):g.jh("RP");e.textContent=d;h.appendChild(e);f&&(d=c,g.xm(h,{display:"inline-block",position:"relative"}),f=h.firstElementChild.nextElementSibling,g.xm(f,"display","none"),f=f.nextElementSibling,g.xm(f,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",
left:"50%",transform:"translateX(-50%)",width:"400%"}),g.xm(h.lastElementChild,"display","none"),d?(g.xm(h,"padding-top","0.6em"),g.xm(f,"top","0")):(g.xm(h,"padding-bottom","0.6em"),g.xm(f,"bottom","0")));return h},y3=function(){g.O.apply(this,arguments)},z3=function(a,b,c,d,e){g.pE.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.j=[]},Agb=function(a){var b="_"+A3++;
return new z3(0,0x8000000000000,0,b,a)},B3=function(a){y3.call(this);
this.C=a;this.pens={};this.N={};this.Z={};this.D="_"+A3++;this.K={};this.B=this.j=null;this.G=!0},C3=function(a,b){a=a.getAttribute(b);
if(a!=null)return Number(a)},D3=function(a,b){a=a.getAttribute(b);
if(a!=null)return a==="1"},E3=function(a,b){a=C3(a,b);
return a!==void 0?a:null},G3=function(a,b){a=a.getAttribute(b);
if(a!=null)return F3.test(a),a},Bgb=function(a,b){var c={},d=b.getAttribute("ws");
Object.assign(c,d?a.Z[d]:a.C);a=E3(b,"mh");a!=null&&(c.FB=a);a=E3(b,"ju");a!=null&&(c.textAlign=a);a=E3(b,"pd");a!=null&&(c.Si=a);a=E3(b,"sd");a!=null&&(c.HU=a);a=G3(b,"wfc");a!=null&&(c.windowColor=a);b=C3(b,"wfo");b!==void 0&&(c.windowOpacity=b/255);return c},Cgb=function(a,b){var c={},d=b.getAttribute("wp");
d&&Object.assign(c,a.N[d]);a=E3(b,"ap");a!=null&&(c.Lm=a);a=C3(b,"cc");a!=null&&(c.Nt=a);a=C3(b,"ah");a!=null&&(c.Ik=a);a=C3(b,"rc");a!=null&&(c.Os=a);b=C3(b,"av");b!=null&&(c.yp=b);return c},Dgb=function(a,b,c,d){var e={};
Object.assign(e,Cgb(a,b));Object.assign(e,Bgb(a,b));d?g.Qg(e,a.C)?(d=a.D,e=a.C):d="_"+A3++:d=b.getAttribute("id")||"_"+A3++;a=C3(b,"t")+c;b=C3(b,"d")||0x8000000000000;if(e.Si===2||e.Si===3)c=e.Os,e.Os=e.Nt,e.Nt=c;return new z3(a,b,0,d,e)},H3=function(a){y3.call(this);
this.G=a;this.j=new Map;this.C=new Map;this.D=new Map;this.B=new Map},I3=function(a){a=g.xg(Math.round(a),0,16777215).toString(16).toUpperCase();
return"#000000".substr(0,7-a.length)+a},Egb=function(a,b,c,d,e){d===0&&(d=0x8000000000000);
var f={};b.wpWinPosId&&Object.assign(f,a.C.get(b.wpWinPosId));b.wsWinStyleId&&Object.assign(f,a.D.get(b.wsWinStyleId));a=b.rcRowCount;a!==void 0&&(f.Os=a);b=b.ccColCount;b!==void 0&&(f.Nt=b);if(f.Si===2||f.Si===3)b=f.Os,f.Os=f.Nt,f.Nt=b;return new z3(c,d,0,e,f)},J3=function(a,b,c,d){g.XX.call(this,a);
this.videoData=b;this.audioTrack=c;this.Sa=d;this.G=b.yw},K3=function(a,b,c,d,e,f,h,l,m,n){o3.call(this,a,b,c,d,e,f,h,l,m,n);
this.type=1},L3=function(a,b,c){this.trackData=a;
this.K=c;this.version=this.G=this.C=this.byteOffset=0;this.j=new DataView(this.trackData);this.B=[]},M3=function(a){var b=a.byteOffset;
a.byteOffset+=1;return a.j.getUint8(b)},N3=function(a){var b=a.byteOffset;
a.byteOffset+=4;return a.j.getUint32(b)},O3=function(a,b){y3.call(this);
this.B=a;this.C=b;this.track=this.C.languageName==="CC3"?4:0;this.j=new Ofb;this.j.B=1<<this.track},Ggb=function(a){if(typeof a==="string")return!1;
a=new L3(a,8,0);return Fgb(a)},Fgb=function(a){if(!(a.byteOffset<a.j.byteLength)||N3(a)!==1380139777)return!1;
a.version=M3(a);if(a.version>1)return!1;M3(a);M3(a);M3(a);return!0},P3=function(a,b,c,d,e,f,h,l,m,n){o3.call(this,a,b,c,d,e,f,h,l,m,n);
var p=this;this.type=2;this.Aa=[];this.oa=this.W=this.Na=0;this.Ca=NaN;this.Gb=0;this.Sb=null;this.Ta=new g.ip(this.xca,433,this);this.G&&(n.createClientVe(this.G,this,167342),this.T(this.G,"click",function(){n.logClick(p.G)}),a=new g.xX(this.element,!0),g.P(this,a),a.subscribe("hoverstart",function(){n.logVisibility(p.G,!0)},this));
g.qp(this.element,"ytp-caption-window-rollup");g.P(this,this.Ta);g.xm(this.element,"overflow","hidden")},Hgb=function(a,b){if(!b)return"";
a.C&&a.B.params.HU!==1&&(b*=-1);return"translate"+(a.C?"X":"Y")+"("+b+"px)"},Igb=function(a){a.Aa=Array.from(document.getElementsByClassName("caption-visual-line"));
for(var b=a.B.params.Os,c=0,d=0,e=a.Aa.length-1;c<b&&e>-1;){var f=a.Aa[e];d+=a.C?f.offsetWidth:f.offsetHeight;c++;e--}a.W=d;b=Math;c=b.max;isNaN(a.Ca)&&((d=a.j.Nt)?(e=g.jh("SPAN"),g.qh(e,"\u2013".repeat(d)),g.xm(e,Jfb(a,a.j.Oe)),a.D.appendChild(e),a.Ca=e.offsetWidth,a.D.removeChild(e)):a.Ca=0);d=a.D;a.oa=c.call(b,a.Ca,a.Gb,(a.C?d.offsetHeight:d.offsetWidth)+1)},Jgb=function(a,b){Igb(a);
var c=a.Aa.reduce(function(f,h){return(a.C?h.offsetWidth:h.offsetHeight)+f},0);
c=a.W-c;if(c!==a.Na){var d=c>0&&a.Na===0,e=c<a.Na;b||isNaN(c)||d||!e||(g.qp(a.element,"ytp-rollup-mode"),g.jp(a.Ta));g.xm(a.D,"transform",Hgb(a,c));a.Na=c}Igb(a)},Q3=function(){y3.call(this)},Kgb=function(a,b,c,d,e,f,h,l,m){switch(h.tagName){case "b":l.bold=!0;
break;case "i":l.italic=!0;break;case "u":l.underline=!0}for(var n=0;n<h.childNodes.length;n++){var p=h.childNodes[n];if(p.nodeType===3)p=new x3(b,c,d,e.id,p.nodeValue,f||n>0,g.Og(l)?void 0:l),m.push(p),e.j.push(p);else{var q={};Object.assign(q,l);Kgb(a,b,c,d,e,!0,p,q,m)}}},Lgb=function(a){var b=a.split(":");
a=0;b=g.w(b);for(var c=b.next();!c.done;c=b.next())a=a*60+Number(c.value);return a*1E3},Mgb=function(a,b,c,d){d=Object.assign({FB:0},d);
return new z3(a,b,c,"_"+A3++,d)},R3=function(a,b){g.O.call(this);
this.J=a;this.Y=b;this.j=null;this.B=this.J.HA();this.logger=new g.AT("caps")},Ngb=function(a){if(typeof a==="string"||Ggb(a))return a;
var b=new DataView(a);if(b.byteLength<=8||b.getUint32(4)!==1718909296)return"";b=g.tM(b,0,1835295092);if(!b||!b.size)return"";a=new Uint8Array(a,b.dataOffset,b.size-(b.dataOffset-b.offset));return g.YA(a)},Pgb=function(a,b,c){if(typeof b==="string"||Ggb(b))return[{trackData:b,
BU:c}];var d=new DataView(b);if(d.byteLength<=8||d.getUint32(4)!==1718909296)return[];var e=g.iEa(d);if(a.B&&e){var f=g.aEa(e),h=g.bEa(e);e=e.pj;f&&e&&a.B.vI(e,f,h)}a=g.CM(d,1835295092);if(!a||!a.length||!a[0].size)return[];f=[];for(h=0;h<a.length;h++)e=a[h],e=new Uint8Array(b,e.dataOffset,e.size-(e.dataOffset-e.offset)),e=g.YA(e),f.push({trackData:e,BU:c+h*1E3});Ogb(d,f,c);return f=f.filter(function(l){return!!l.trackData})},Ogb=function(a,b,c){var d=g.tM(a,0,1836476516),e=9E4;
d&&(e=g.uM(d)||9E4);d=0;for(var f=g.CM(a,1836019558),h=0;h<f.length;h++){var l=f[h];h<b.length&&(l=g.tM(a,l.dataOffset,1953653094))&&(l=g.tM(a,l.dataOffset,1952867444))&&(l=g.AM(l)/e*1E3,h===0&&(d=l),b[h].BU=l-d+c||c*h*1E3)}},Qgb=function(a,b,c,d,e){if(!Ggb(c))throw Error("Invalid binary caption track data");
a.j||(a.j=new O3(e,b));return a.j.fp(c,d)},Rgb=function(a,b,c){a.j||(a.j=new Q3);
a=a.j.fp(b,c);Math.random()<.01&&g.Uw(Error("Deprecated subtitles format in web player: WebVTT"));return a},Tgb=function(a,b,c,d){if(c[0]==="{")try{return a.j||(a.j=new H3(Sgb(b))),a.j.fp(c,d)}catch(f){return g.Tw(f),[]}var e=g.a1(c);
if(!e||!e.firstChild)throw a=Error("Invalid caption track data"),a.params=c,a;if(e.firstChild.tagName==="timedtext"){if(Number(e.firstChild.getAttribute("format"))===3)return a.j||(a.j=new B3(Sgb(b),a.Y)),a.j.fp(e,d);a=Error("Unsupported subtitles format in web player (Format2)");a.params=c;throw a;}if(e.firstChild.tagName==="transcript")throw a=Error("Unsupported subtitles format in web player (Format1)"),a.params=c,a;a=Error("Invalid caption track data");a.params=c;throw a;},Sgb=function(a){var b=
{};
if(a=g.XP(a))b.lang=a,g.Lab.test(a)&&(b.Si=1);return b},S3=function(a){g.UX.call(this,a);
var b=this;this.J=a;this.Y=this.J.U();this.videoData=this.J.getVideoData();this.qb=this.J.ob();var c;this.ib=(c=this.J.getVideoData(1))==null?void 0:g.LQ(c);this.C={Oe:{}};this.G={Oe:{}};this.Fa=[];this.Aa={};this.Ua={};this.N=!1;this.Nb=g.zR(this.videoData);this.Va=g.R_a(this.videoData,this.J);this.Gb=!!this.videoData.captionTracks.length;this.Sb=!!this.videoData.ze;this.Ta=this.Y.controlsType==="3";this.j=this.Z=this.W=this.Na=this.kb=null;this.Wa=new R3(this.J,this.Y);this.B=null;this.oa=new g.PF(this);
this.K=new g.U({I:"div",S:"ytp-caption-window-container",X:{id:"ytp-caption-window-container"}});this.qa={top:0,right:0,bottom:0,left:0,width:1,height:1};c=null;var d=g.Tp("yt-html5-player-modules::subtitlesModuleData");d&&(c=new g.Kp(d));this.storage=c;var e;this.Lb=!((e=a.Ce())==null||!e.nI());this.D=Ugb(this);this.Ca=!this.D&&this.Ta&&this.Lb&&this.Va;g.P(this,this.Wa);this.D?this.La=this.Ja=null:(this.Ja=new g.hp(this.TU,void 0,this),g.P(this,this.Ja),this.La=new g.ip(this.fea,2E3,this),g.P(this,
this.La));g.P(this,this.oa);g.gS(this.player,this.K.element,4);g.P(this,this.K);this.oa.T(a,"contentPoTokenReady",this.TG);this.D||this.oa.T(a,"resize",this.UU);(this.Ab=g.nP(this.Y)&&!g.As()&&!this.J.isFullscreen()&&!this.D&&!this.Ca)&&this.oa.T(a,"resize",this.Gba);this.oa.T(a,"onPlaybackAudioChange",this.Saa);this.oa.T(a,g.rE("captions"),function(f){b.onCueRangeEnter(f)});
this.oa.T(a,g.sE("captions"),function(f){b.onCueRangeExit(f)});
this.ib&&this.oa.T(a,"videodatachange",function(f,h){b.onVideoDataChange(f,h)});
Vgb(this,wfb()||{});this.player.xd("onCaptionsModuleAvailable")},Ygb=function(a){if(a.Y.Lb===1||a.videoData.mD===1||g.fR(a.videoData,"yt:cc")==="alwayson")return!0;
if(a.videoData.captionTracks.length)var b=a.getAudioTrack().B;if(a.Y.Lb===2){if(g.DP(a.Y))var c=Wgb(a);else if(a.storage)try{c=a.storage.get("module-enabled")}catch(e){a.storage.remove("module-enabled")}else c=null;if(c!=null)return!!c}c=ofb(a.player.getAudioTrack(),g.DP(a.Y));var d=g.fR(a.videoData,"yt:cc");if(Xgb(a)===void 0){if(c==="CAPTIONS_INITIAL_STATE_ON_RECOMMENDED")return d?d==="on":!0;if(c==="CAPTIONS_INITIAL_STATE_OFF_RECOMMENDED")return d==="on"}else return d==="on";return b==="ON"||g.fR(a.videoData,
"yt:cc")==="on"},T3=function(a,b){if(a.B&&(b===void 0||!b)||!a.videoData.captionTracks.length)return!1;
a=a.getAudioTrack();return!!a.j||a.B==="FORCED_ON"},Xgb=function(a){var b=void 0,c=g.Ys(g.Xs(),65);
if(g.DP(a.Y)&&c!=null){if(Wgb(a)!=null)return!1;b=!c}return b},Zgb=function(a){var b;
a.Nb?b=new J3(a.Y,a.videoData,a.getAudioTrack(),a.player):a.Va?b=new n3(a.videoData.j,a.player):a.Gb?b=new g.YX(a.Y,a.videoData,a.getAudioTrack()):b=new g.ZX(a.Y,a.videoData.ze,a.videoData.videoId,g.bMa(a.videoData),a.videoData.Kn,a.videoData.eventId);return b},V3=function(a,b){if(a.j){if(a.Z&&a.Z.D)return a.Z.D;
g.sR(a.videoData)&&(b=!0);b||(b=a.Sb?!1:a.Gb?!1:!0);b=b||$gb(a);b=g.VX(a.j.B,b);var c=null;if(g.DP(a.Y)){var d=a.J.isInline()?void 0:g.Rs("yt-player-caption-sticky-language");for(var e=[d,a.videoData.captionsLanguagePreference,a.Y.captionsLanguagePreference,g.fR(a.videoData,"yt:cc_default_lang")],f=!1,h=0;h<e.length;h++){var l=e[h];if(l){f=!0;for(var m=0;m<b.length;m++)if(g.XP(b[m])===l)return b[m];for(m=0;m<b.length;m++)if(g.XP(b[m]).split("-")[0]===l.split("-")[0])return b[m]}}if(f&&a.j&&(e=a.j.G,
e.length))for(e=g.w(e),f=e.next();!f.done;f=e.next())if(f=f.value,f.languageCode===d){c=f;break}}else for(d=[a.videoData.captionsLanguagePreference,a.Y.captionsLanguagePreference,g.fR(a.videoData,"yt:cc_default_lang")],e=0;e<d.length;e++)for(f=0;f<b.length;f++)if(g.XP(b[f])===d[e])return b[f];d=null;a.Z&&a.Z.C&&(d=a.Z.C);d||(d=b.find(function(n){return n.isDefault})||null);
d||(d=b[0]||U3(a));d&&c&&g.XP(d).split("-")[0]!==c.languageCode.split("-")[0]&&(d=pfb(d,c));return d}return null},U3=function(a){return a.Z&&a.Z.j},W3=function(a){var b=U3(a);
return!!b&&a.B===b},ahb=function(a){var b=ofb(a.player.getAudioTrack(),g.DP(a.Y)),c;
b==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?c=V3(a,a.N):b==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"&&T3(a)?c=U3(a):Xgb(a)||a.N||Ygb(a)?c=V3(a,a.N):T3(a)&&(c=U3(a));if(a.D||a.Ca){var d=g.VX(a.j.B,!0);b=[];for(var e=0;e<d.length;e++){var f=d[e],h=g.jh("TRACK");h.setAttribute("kind","subtitles");h.setAttribute("label",g.VP(f));h.setAttribute("srclang",g.XP(f));h.setAttribute("id",f.toString());a.Ca||h.setAttribute("src",a.j.Ax(f,"vtt"));f===c&&h.setAttribute("default","1");b.push(h)}c=a.J.Ce();c.BE(b);c=
c.Ib();a.Lb&&a.oa.T(c.textTracks,"change",a.fda)}else!a.B&&c&&X3(a,c),a.player.xd("onCaptionsTrackListChanged"),a.player.rf("onApiChange")},bhb=function(a,b){var c=a.J.Ce().Ib().textTracks;
a=a.B.toString();for(var d=0;d<c.length;d++){var e=c[d];e.id===a&&(b?e.mode!=="showing"&&(e.mode="showing"):e.mode==="showing"&&(e.mode="disabled"))}},X3=function(a,b,c){a.loaded&&a.unload();
c!=null&&(a.N=c,a.N&&(g.DP(a.Y)?Y3(a,!!b):Z3(a,!!b)));a.Y.L("html5_report_caption_format_change")&&chb(a,a.B,b,a.N,!1);a.B=b;T3(a)&&(b=U3(a),a.Y.L("html5_report_caption_format_change")&&chb(a,a.B,b,a.N,!0),a.B=b);var d;dhb(a,(d=a.B)!=null?d:void 0);a.load()},fhb=function(a,b){if(b instanceof z3){var c=a.Aa[b.id];
c&&c.B!==b&&(c.dispose(),delete a.Aa[b.id],c=null);c||(c=ehb(a,b))&&(a.Aa[b.id]=c)}else c=b.windowId,a.Ua[c]||(a.Ua[c]=[]),a.Ua[c].push(b)},ehb=function(a,b){var c=ghb(a);
if(!c)return null;var d=a.B?g.XP(a.B):null;d&&g.Lab.test(d)&&(b.params.Si=1);var e=a.qb.getPlayerSize();d=e.height*a.qa.height;e=e.width*a.qa.width;a.Y.playerStyle!=="google-live"||a.C.isDefault||Object.assign(b.params,a.C);switch(b.params.FB!=null?b.params.FB:b.j.length>1?1:0){case 1:return new K3(b,a.C,a.G,c.width,c.height,e,d,a.Y.experiments,a.HN.bind(a),a.J);case 2:return new P3(b,a.C,a.G,c.width,c.height,e,d,a.Y.experiments,a.HN.bind(a),a.J);default:return new o3(b,a.C,a.G,c.width,c.height,e,
d,a.Y.experiments,a.HN.bind(a),a.J)}},Vgb=function(a,b,c){c=c===void 0?!1:c;
var d=$3.Oe;a.C={};Object.assign(a.C,$3);a.C.Oe={};Object.assign(a.C.Oe,d);a.G={Oe:{}};var e=b.backgroundOverride?a.G:a.C,f=b.background||d.background;F3.test(f);e.Oe.background=f;e=b.colorOverride?a.G:a.C;f=b.color||d.color;F3.test(f);e.Oe.color=f;e=b.windowColorOverride?a.G:a.C;f=b.windowColor||$3.windowColor;F3.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.G:a.C;f=b.backgroundOpacity;f==null&&(f=d.backgroundOpacity);e.Oe.backgroundOpacity=f;e=b.fontSizeIncrementOverride?a.G:a.C;f=b.fontSizeIncrement;
f==null&&(f=d.fontSizeIncrement);e.Oe.fontSizeIncrement=f;f=b.fontStyleOverride?a.G:a.C;e=b.fontStyle;e==null&&(e=d.bold&&d.italic?3:d.bold?1:d.italic?2:0);f=f.Oe;switch(e){case 1:f.bold=!0;delete f.italic;break;case 2:delete f.bold;f.italic=!0;break;case 3:f.bold=!0;f.italic=!0;break;default:delete f.bold,delete f.italic}e=b.textOpacityOverride?a.G:a.C;f=b.textOpacity;f==null&&(f=d.textOpacity);e.Oe.textOpacity=f;e=b.windowOpacityOverride?a.G:a.C;f=b.windowOpacity;f==null&&(f=$3.windowOpacity);e.windowOpacity=
f;e=b.charEdgeStyleOverride?a.G:a.C;f=b.charEdgeStyle;f==null&&(f=d.charEdgeStyle);e.Oe.charEdgeStyle=f;e=b.fontFamilyOverride?a.G:a.C;f=b.fontFamily;f==null&&(f=d.fontFamily);e.Oe.fontFamily=f;a.loaded&&a.UU();c&&g.Qs("yt-player-caption-display-settings",b,2592E3)},ihb=function(a,b,c){b&&!a.W?(b=Agb({Si:0,
lang:"en"}),a.W=[b,new x3(b.start,b.end-b.start,0,b.id,c!=null?c:"Captions look like this")],a.player.lf(a.W)):!b&&a.W&&(hhb(a,a.W),a.W=null)},hhb=function(a,b){a.player.pp(b);
b=g.w(b);for(var c=b.next();!c.done;c=b.next())g.Ub(a.Fa,c.value);l3(a.Ja)},dhb=function(a,b){a.Y.L("html5_modify_caption_vss_logging")&&(a.videoData.fE=b)},ghb=function(a){var b=a.qb.getVideoContentRect(!0).height,c=a.qb.getVideoContentRect(!0).width;
if(!b||!c)return null;b*=a.qa.height;c*=a.qa.width;return{width:c,height:b}},Z3=function(a,b){if(a.storage)try{a.storage.set("module-enabled",b)}catch(c){}},Y3=function(a,b){a.J.isInline()||g.Qs("yt-player-sticky-caption",b,2592E3)},Wgb=function(a){if(!a.J.isInline())return g.Rs("yt-player-sticky-caption")},Ugb=function(a){var b,c=!((b=a.J.Ce())==null||!b.mI());
return a.Ta&&c&&!a.Va},$gb=function(a){return a.Y.L("web_deprecate_always_includes_asr_setting")&&g.DP(a.Y)?!0:!!g.Ys(g.Xs(),66)},chb=function(a,b,c,d,e){e?a.mj(c,!0,"g"):d?b?a.mj(c,!!c,"m"):c&&a.mj(c,!0,"m"):!b&&c&&a.mj(c,!0,"s")};
g.XX.prototype.oT=g.da(55,function(){return!1});
g.XX.prototype.Mu=g.da(54,function(){});
g.YX.prototype.Mu=g.da(53,function(a,b,c){var d=this;this.Ia();b=this.Ax(a,b);this.nt();nfb(this,b,{format:"RAW",onSuccess:function(e){d.j=null;c(e.responseText,a)},
withCredentials:!0})});
g.ZX.prototype.Mu=g.da(52,function(a,b,c){var d=this;this.Ia();b=this.Ax(a,b);this.nt();this.j=g.Ir(b,{format:"RAW",onSuccess:function(e){d.j=null;c(e.responseText,a)},
withCredentials:!0})});
g.FX.prototype.cA=g.da(51,function(){for(var a=g.bh(document,"track",void 0,this.j),b=0;b<a.length;b++)g.oh(a[b])});
g.b_.prototype.cA=g.da(50,function(){this.mediaElement.cA()});
g.FX.prototype.nI=g.da(49,function(){return!(!this.j.textTracks||!this.j.textTracks.addEventListener)});
g.b_.prototype.nI=g.da(48,function(){return this.mediaElement.nI()});
g.FX.prototype.mI=g.da(47,function(){return!!this.j.textTracks});
g.b_.prototype.mI=g.da(46,function(){return this.mediaElement.mI()});
g.FX.prototype.BE=g.da(45,function(a){for(var b=0;b<a.length;b++)this.j.appendChild(a[b])});
g.b_.prototype.BE=g.da(44,function(a){this.mediaElement.BE(a)});
g.FV.prototype.vI=g.da(40,function(a,b,c){this.Xc.vI(a,b,c)});
g.k_.prototype.vI=g.da(39,function(a,b,c){this.Ja.set(a,{St:b,Pz:c})});
g.FV.prototype.EF=g.da(38,function(a){return this.Xc.EF(a)});
g.k_.prototype.EF=g.da(37,function(a){var b=2;this.K.has(a)?b=0:g.z5a(this,a)&&(b=1);return b});
g.AT.prototype.j=g.da(36,function(a){g.vOa.apply(null,[6,this.tag,a].concat(g.x(g.Ea.apply(1,arguments))))});
g.$R.prototype.Vk=g.da(34,function(a,b){var c=g.SR(this.app);c&&c.Vk(a,b)});
g.XV.prototype.Vk=g.da(33,function(a,b){a=[a,b];g.WV(this,g.pK(this.provider),"cfi",a)});
g.kW.prototype.Vk=g.da(32,function(a,b){this.qoe&&this.qoe.Vk(a,b)});
g.LW.prototype.Vk=g.da(31,function(a,b){this.Qb().Vk(a,b)});
g.$R.prototype.mj=g.da(30,function(a,b,c){var d=g.SR(this.app);d&&d.mj(a,b,c)});
g.XV.prototype.mj=g.da(29,function(a,b,c){b=[a,b,this.Gb,c];g.WV(this,g.pK(this.provider),"cfs",b);this.Gb=a});
g.kW.prototype.mj=g.da(28,function(a,b,c){this.qoe&&this.qoe.mj(a,b,c)});
g.LW.prototype.mj=g.da(27,function(a,b,c){this.Qb().mj(a,b,c)});
g.AV.prototype.SF=g.da(18,function(){return this.N});
g.I_.prototype.SF=g.da(17,function(){var a;return((a=g.SR(this))==null?void 0:a.HA())||null});
g.$R.prototype.HA=g.da(16,function(){return this.app.SF()});
g.LW.prototype.HA=g.da(15,function(){var a;return((a=this.ra)==null?void 0:a.SF())||null});
g.fM.prototype.CK=g.da(1,function(a){return(a=this.xo(a))?a.j:0});
g.EN.prototype.CK=g.da(0,function(){return 0});
var tfb=/#(.)(.)(.)/,sfb=/^#(?:[0-9a-f]{3}){1,2}$/i,Bfb={aa:"Afar",ab:"Abkhazian",ace:"Acehnese",ach:"Acoli",ada:"Adangme",ady:"Adyghe",ae:"Avestan",aeb:"Tunisian Arabic",af:"Afrikaans",afh:"Afrihili",agq:"Aghem",ain:"Ainu",ak:"Akan",akk:"Akkadian",akz:"Alabama",ale:"Aleut",aln:"Gheg Albanian",alt:"Southern Altai",am:"Amharic",an:"Aragonese",ang:"Old English",anp:"Angika",ar:"Arabic",ar_001:"Arabic (world)",arc:"Aramaic",arn:"Mapuche",aro:"Araona",arp:"Arapaho",arq:"Algerian Arabic",ars:"Najdi Arabic",
arw:"Arawak",ary:"Moroccan Arabic",arz:"Egyptian Arabic",as:"Assamese",asa:"Asu",ase:"American Sign Language",ast:"Asturian",av:"Avaric",avk:"Kotava",awa:"Awadhi",ay:"Aymara",az:"Azerbaijani",az_Cyrl:"Azerbaijani (Cyrillic)",az_Latn:"Azerbaijani (Latin)",ba:"Bashkir",bal:"Baluchi",ban:"Balinese",bar:"Bavarian",bas:"Basaa",bax:"Bamun",bbc:"Batak Toba",bbj:"Ghomala",be:"Belarusian",bej:"Beja",bem:"Bemba",bew:"Betawi",bez:"Bena",bfd:"Bafut",bfq:"Badaga",bg:"Bulgarian",bgc:"Haryanvi",bgn:"Western Balochi",
bho:"Bhojpuri",bi:"Bislama",bik:"Bikol",bin:"Bini",bjn:"Banjar",bkm:"Kom",bla:"Siksik\u00e1",blo:"Anii",bm:"Bambara",bn:"Bangla",bo:"Tibetan",bpy:"Bishnupriya",bqi:"Bakhtiari",br:"Breton",bra:"Braj",brh:"Brahui",brx:"Bodo",bs:"Bosnian",bs_Cyrl:"Bosnian (Cyrillic)",bs_Latn:"Bosnian (Latin)",bss:"Akoose",bua:"Buriat",bug:"Buginese",bum:"Bulu",byn:"Blin",byv:"Medumba",ca:"Catalan",cad:"Caddo",car:"Carib",cay:"Cayuga",cch:"Atsam",ccp:"Chakma",ce:"Chechen",ceb:"Cebuano",cgg:"Chiga",ch:"Chamorro",chb:"Chibcha",
chg:"Chagatai",chk:"Chuukese",chm:"Mari",chn:"Chinook Jargon",cho:"Choctaw",chp:"Chipewyan",chr:"Cherokee",chy:"Cheyenne",ckb:"Central Kurdish",co:"Corsican",cop:"Coptic",cps:"Capiznon",cr:"Cree",crh:"Crimean Tatar",cs:"Czech",csb:"Kashubian",csw:"Swampy Cree",cu:"Church Slavic",cv:"Chuvash",cy:"Welsh",da:"Danish",dak:"Dakota",dar:"Dargwa",dav:"Taita",de:"German",de_AT:"German (Austria)",de_CH:"German (Switzerland)",del:"Delaware",den:"Slave",dgr:"Dogrib",din:"Dinka",dje:"Zarma",doi:"Dogri",dsb:"Lower Sorbian",
dua:"Duala",dum:"Middle Dutch",dv:"Divehi",dyo:"Jola-Fonyi",dyu:"Dyula",dz:"Dzongkha",dzg:"Dazaga",ebu:"Embu",ee:"Ewe",efi:"Efik",egy:"Ancient Egyptian",eka:"Ekajuk",el:"Greek",elx:"Elamite",en:"English",en_AU:"English (Australia)",en_CA:"English (Canada)",en_GB:"English (United Kingdom)",en_US:"English (United States)",enm:"Middle English",eo:"Esperanto",es:"Spanish",es_419:"Spanish (Latin America)",es_ES:"Spanish (Spain)",es_MX:"Spanish (Mexico)",et:"Estonian",eu:"Basque",ewo:"Ewondo",fa:"Persian",
fa_AF:"Persian (Afghanistan)",fan:"Fang",fat:"Fanti",ff:"Fula",ff_Adlm:"Fula (Adlam)",ff_Latn:"Fula (Latin)",fi:"Finnish",fil:"Filipino",fj:"Fijian",fo:"Faroese",fon:"Fon",fr:"French",fr_CA:"French (Canada)",fr_CH:"French (Switzerland)",frm:"Middle French",fro:"Old French",frr:"Northern Frisian",frs:"Eastern Frisian",fur:"Friulian",fy:"Western Frisian",ga:"Irish",gaa:"Ga",gay:"Gayo",gba:"Gbaya",gd:"Scottish Gaelic",gez:"Geez",gil:"Gilbertese",gl:"Galician",gmh:"Middle High German",gn:"Guarani",goh:"Old High German",
gon:"Gondi",gor:"Gorontalo",got:"Gothic",grb:"Grebo",grc:"Ancient Greek",gsw:"Swiss German",gu:"Gujarati",guz:"Gusii",gv:"Manx",gwi:"Gwich\u02bcin",ha:"Hausa",hai:"Haida",haw:"Hawaiian",he:"Hebrew",hi:"Hindi",hi_Latn:"Hindi (Latin)",hil:"Hiligaynon",hit:"Hittite",hmn:"Hmong",ho:"Hiri Motu",hr:"Croatian",hsb:"Upper Sorbian",ht:"Haitian Creole",hu:"Hungarian",hup:"Hupa",hy:"Armenian",hz:"Herero",ia:"Interlingua",iba:"Iban",ibb:"Ibibio",id:"Indonesian",ie:"Interlingue",ig:"Igbo",ii:"Sichuan Yi",ik:"Inupiaq",
ilo:"Iloko","in":"Indonesian",inh:"Ingush",io:"Ido",is:"Icelandic",it:"Italian",iu:"Inuktitut",iw:"Hebrew",ja:"Japanese",jbo:"Lojban",jgo:"Ngomba",jmc:"Machame",jpr:"Judeo-Persian",jrb:"Judeo-Arabic",jv:"Javanese",ka:"Georgian",kaa:"Kara-Kalpak",kab:"Kabyle",kac:"Kachin",kaj:"Jju",kam:"Kamba",kaw:"Kawi",kbd:"Kabardian",kbl:"Kanembu",kcg:"Tyap",kde:"Makonde",kea:"Kabuverdianu",kfo:"Koro",kg:"Kongo",kgp:"Kaingang",kha:"Khasi",kho:"Khotanese",khq:"Koyra Chiini",ki:"Kikuyu",kj:"Kuanyama",kk:"Kazakh",
kkj:"Kako",kl:"Kalaallisut",kln:"Kalenjin",km:"Khmer",kmb:"Kimbundu",kn:"Kannada",ko:"Korean",kok:"Konkani",kos:"Kosraean",kpe:"Kpelle",kr:"Kanuri",krc:"Karachay-Balkar",krl:"Karelian",kru:"Kurukh",ks:"Kashmiri",ks_Arab:"Kashmiri (Arabic)",ks_Deva:"Kashmiri (Devanagari)",ksb:"Shambala",ksf:"Bafia",ksh:"Colognian",ku:"Kurdish",kum:"Kumyk",kut:"Kutenai",kv:"Komi",kw:"Cornish",kxv:"Kuvi",kxv_Deva:"Kuvi (Devanagari)",kxv_Latn:"Kuvi (Latin)",kxv_Orya:"Kuvi (Odia)",kxv_Telu:"Kuvi (Telugu)",ky:"Kyrgyz",
la:"Latin",lad:"Ladino",lag:"Langi",lah:"Western Panjabi",lam:"Lamba",lb:"Luxembourgish",lez:"Lezghian",lg:"Ganda",li:"Limburgish",lij:"Ligurian",lkt:"Lakota",lmo:"Lombard",ln:"Lingala",lo:"Lao",lol:"Mongo",loz:"Lozi",lrc:"Northern Luri",lt:"Lithuanian",lu:"Luba-Katanga",lua:"Luba-Lulua",lui:"Luiseno",lun:"Lunda",luo:"Luo",lus:"Mizo",luy:"Luyia",lv:"Latvian",mad:"Madurese",maf:"Mafa",mag:"Magahi",mai:"Maithili",mak:"Makasar",man:"Mandingo",mas:"Masai",mde:"Maba",mdf:"Moksha",mdr:"Mandar",men:"Mende",
mer:"Meru",mfe:"Morisyen",mg:"Malagasy",mga:"Middle Irish",mgh:"Makhuwa-Meetto",mgo:"Meta\u02bc",mh:"Marshallese",mi:"M\u0101ori",mic:"Mi'kmaw",min:"Minangkabau",mk:"Macedonian",ml:"Malayalam",mn:"Mongolian",mnc:"Manchu",mni:"Manipuri",mni_Beng:"Manipuri (Bangla)",mo:"Romanian",moh:"Mohawk",mos:"Mossi",mr:"Marathi",ms:"Malay",mt:"Maltese",mua:"Mundang",mul:"Multiple languages",mus:"Muscogee",mwl:"Mirandese",mwr:"Marwari",my:"Burmese",mye:"Myene",myv:"Erzya",mzn:"Mazanderani",na:"Nauru",nap:"Neapolitan",
naq:"Nama",nb:"Norwegian Bokm\u00e5l",nd:"North Ndebele",nds:"Low German",nds_NL:"Low German (Netherlands)",ne:"Nepali","new":"Newari",ng:"Ndonga",nia:"Nias",niu:"Niuean",nl:"Dutch",nl_BE:"Dutch (Belgium)",nmg:"Kwasio",nn:"Norwegian Nynorsk",nnh:"Ngiemboon",no:"Norwegian",nog:"Nogai",non:"Old Norse",nqo:"N\u2019Ko",nr:"South Ndebele",nso:"Northern Sotho",nus:"Nuer",nv:"Navajo",nwc:"Classical Newari",ny:"Nyanja",nym:"Nyamwezi",nyn:"Nyankole",nyo:"Nyoro",nzi:"Nzima",oc:"Occitan",oj:"Ojibwa",om:"Oromo",
or:"Odia",os:"Ossetic",osa:"Osage",ota:"Ottoman Turkish",pa:"Punjabi",pa_Arab:"Punjabi (Arabic)",pa_Guru:"Punjabi (Gurmukhi)",pag:"Pangasinan",pal:"Pahlavi",pam:"Pampanga",pap:"Papiamento",pau:"Palauan",pcm:"Nigerian Pidgin",peo:"Old Persian",phn:"Phoenician",pi:"Pali",pl:"Polish",pon:"Pohnpeian",prg:"Prussian",pro:"Old Proven\u00e7al",ps:"Pashto",pt:"Portuguese",pt_BR:"Portuguese (Brazil)",pt_PT:"Portuguese (Portugal)",qu:"Quechua",raj:"Rajasthani",rap:"Rapanui",rar:"Rarotongan",rm:"Romansh",rn:"Rundi",
ro:"Romanian",ro_MD:"Romanian (Moldova)",rof:"Rombo",rom:"Romany",ru:"Russian",rup:"Aromanian",rw:"Kinyarwanda",rwk:"Rwa",sa:"Sanskrit",sad:"Sandawe",sah:"Yakut",sam:"Samaritan Aramaic",saq:"Samburu",sas:"Sasak",sat:"Santali",sat_Olck:"Santali (Ol Chiki)",sba:"Ngambay",sbp:"Sangu",sc:"Sardinian",scn:"Sicilian",sco:"Scots",sd:"Sindhi",sd_Arab:"Sindhi (Arabic)",sd_Deva:"Sindhi (Devanagari)",se:"Northern Sami",see:"Seneca",seh:"Sena",sel:"Selkup",ses:"Koyraboro Senni",sg:"Sango",sga:"Old Irish",sh:"Serbo-Croatian",
shi:"Tachelhit",shi_Latn:"Tachelhit (Latin)",shi_Tfng:"Tachelhit (Tifinagh)",shn:"Shan",shu:"Chadian Arabic",si:"Sinhala",sid:"Sidamo",sk:"Slovak",sl:"Slovenian",sm:"Samoan",sma:"Southern Sami",smj:"Lule Sami",smn:"Inari Sami",sms:"Skolt Sami",sn:"Shona",snk:"Soninke",so:"Somali",sog:"Sogdien",sq:"Albanian",sr:"Serbian",sr_Cyrl:"Serbian (Cyrillic)",sr_Latn:"Serbian (Latin)",srn:"Sranan Tongo",srr:"Serer",ss:"Swati",ssy:"Saho",st:"Southern Sotho",su:"Sundanese",su_Latn:"Sundanese (Latin)",suk:"Sukuma",
sus:"Susu",sux:"Sumerian",sv:"Swedish",sw:"Swahili",sw_CD:"Swahili (Congo - Kinshasa)",swb:"Comorian",syc:"Classical Syriac",syr:"Syriac",szl:"Silesian",ta:"Tamil",te:"Telugu",tem:"Timne",teo:"Teso",ter:"Tereno",tet:"Tetum",tg:"Tajik",th:"Thai",ti:"Tigrinya",tig:"Tigre",tiv:"Tiv",tk:"Turkmen",tkl:"Tokelau",tl:"Tagalog",tlh:"Klingon",tli:"Tlingit",tmh:"Tamashek",tn:"Tswana",to:"Tongan",tog:"Nyasa Tonga",tok:"Toki Pona",tpi:"Tok Pisin",tr:"Turkish",trv:"Taroko",ts:"Tsonga",tsi:"Tsimshian",tt:"Tatar",
tum:"Tumbuka",tvl:"Tuvalu",tw:"Twi",twq:"Tasawaq",ty:"Tahitian",tyv:"Tuvinian",tzm:"Central Atlas Tamazight",udm:"Udmurt",ug:"Uyghur",uga:"Ugaritic",uk:"Ukrainian",umb:"Umbundu",ur:"Urdu",uz:"Uzbek",uz_Arab:"Uzbek (Arabic)",uz_Cyrl:"Uzbek (Cyrillic)",uz_Latn:"Uzbek (Latin)",vai:"Vai",vai_Latn:"Vai (Latin)",vai_Vaii:"Vai (Vai)",ve:"Venda",vec:"Venetian",vi:"Vietnamese",vmw:"Makhuwa",vo:"Volap\u00fck",vot:"Votic",vun:"Vunjo",wa:"Walloon",wae:"Walser",wal:"Wolaytta",war:"Waray",was:"Washo",wo:"Wolof",
xal:"Kalmyk",xh:"Xhosa",xnr:"Kangri",xog:"Soga",yao:"Yao",yap:"Yapese",yav:"Yangben",ybb:"Yemba",yi:"Yiddish",yo:"Yoruba",yrl:"Nheengatu",yue:"Cantonese",yue_Hans:"Cantonese (Simplified)",yue_Hant:"Cantonese (Traditional)",za:"Zhuang",zap:"Zapotec",zbl:"Blissymbols",zen:"Zenaga",zgh:"Standard Moroccan Tamazight",zh:"Chinese",zh_Hans:"Chinese (Simplified)",zh_Hant:"Chinese (Traditional)",zh_TW:"Chinese (Taiwan)",zu:"Zulu",zun:"Zuni",zxx:"No linguistic content",zza:"Zaza"};
m3.prototype.contains=function(a){a=g.bc(this.segments,a);return a>=0||a<0&&(-a-1)%2===1};
m3.prototype.length=function(){return this.segments.length/2};
g.z(yfb,g.O);g.k=yfb.prototype;g.k.xa=function(){g.O.prototype.xa.call(this);this.C&&this.C.cancel()};
g.k.RB=function(){this.seekTo(this.player.getCurrentTime())};
g.k.seekTo=function(a){a-=this.player.Ac();var b=this.j;this.j=g.Nb(this.oa.Wr(a).gb);b!==this.j&&this.W&&this.W()};
g.k.reset=function(){this.D=new m3;this.K=-1;this.C&&(this.C.cancel(),this.C=null)};
g.k.B_=function(){this.Ia();var a;if(a=this.j!=null)a=this.j,a=a.j.Dt(a);if(a&&!this.C&&!(this.j&&this.j.startTime-this.player.getCurrentTime()>30)){a=this.j;a=a.j.LD(a);var b=a.gb[0],c;if((c=this.player.getVideoData())==null?0:c.enableServerStitchedDai)if(c=this.player.HA()){var d=b.j.info.id,e=b.Oa,f=a.gb[0].Ue;if(this.policy.La){if(c=c.FK(f,e,d,3))a.D=c}else if(d=c.yA(f,e,d,3))if(c=c.EF(e),c===0)d&&(a.j=new g.YL(d));else if(c===2){this.N.start();zfb(this)&&this.seekTo(this.player.getCurrentTime());
return}}b.j.index.Jo(b.Oa)?(this.D.contains(a.gb[0].Oa)||Afb(this,a),this.j=g.Nb(a.gb)):zfb(this)&&this.seekTo(this.player.getCurrentTime())}this.N.start()};
g.z(n3,g.XX);g.k=n3.prototype;g.k.Mu=function(a,b,c){var d=this;this.nt();b=Dfb(this,a.getId());b||(b=a.languageCode,b=this.j.isManifestless?Efb(this,b,"386"):Efb(this,b));if(b){var e=(b.index.CK(b.index.Ao())-b.index.getStartTime(b.index.Ao()))*1E3,f=new g.wRa(this.Y),h=function(){d.C&&d.C.reset();d.K=!0};
this.Y.L("html5_keep_caption_data_after_seek")&&(h=null);this.C=new yfb(f,this.J,b,function(l,m){c(l,a,m,e)},this.N||g.cG(b.info),h)}};
g.k.oT=function(){var a=this.K;this.K=!1;return a};
g.k.sB=function(a){var b=this.N?[new g.UP({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.UP({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]:this.j.isManifestless?Cfb(this,"386"):Cfb(this);b=g.w(b);for(var c=b.next();!c.done;c=b.next())g.WX(this.B,c.value);a()};
g.k.nt=function(){this.C&&(this.C.dispose(),this.C=null)};
g.k.Ax=function(){return""};
g.k.EH=function(){this.C&&(this.C.reset(),this.J.gf("captions"))};
var F3=/^#(?:[0-9a-f]{3}){1,2}$/i;var Hfb=["left","right","center","justify"];g.z(o3,g.U);g.k=o3.prototype;g.k.g5=function(a,b){this.Va=a;this.ib=b;var c=g.Hm(this.element,this.element.parentElement);this.kb=a-c.x;this.qb=b-c.y};
g.k.f5=function(a,b){if(a!==this.Va||b!==this.ib){g.pp(this.element,"ytp-dragging")||g.qp(this.element,"ytp-dragging");var c=g.Jm(this.element);a=a-this.kb-.02*this.playerWidth;var d=b-this.qb-.02*this.playerHeight,e=(a+c.width/2)/this.maxWidth*3;e=Math.floor(g.xg(e,0,2));var f=(d+c.height/2)/this.maxHeight*3;f=Math.floor(g.xg(f,0,2));b=e+f*3;a=(a+e/2*c.width)/this.maxWidth;a=g.xg(a,0,1)*100;c=(d+f/2*c.height)/this.maxHeight;c=g.xg(c,0,1)*100;this.B.params.Lm=b;this.B.params.yp=c;this.B.params.Ik=
a;this.B.params.isDefault=!1;this.j.Lm=b;this.j.yp=c;this.j.Ik=a;this.j.isDefault=!1;this.qa.Lm=b;this.qa.yp=c;this.qa.Ik=a;this.qa.isDefault=!1;this.j2()}};
g.k.e5=function(){g.sp(this.element,"ytp-dragging")};
g.k.j2=function(){this.IC(this.K)};
g.k.getType=function(){return this.type};
g.k.IC=function(a){var b=this.Ab?0:Math.min(this.MY(),this.maxWidth),c=this.LY(),d=this.Ab;if(d){var e=getComputedStyle(this.D.parentNode);e=p3(e.borderLeftWidth)+p3(e.borderRightWidth)+p3(e.paddingLeft)+p3(e.paddingRight)}else e=0;var f=e;e="";this.B.params.Si===3&&(e="rotate(180deg)");var h=d?"calc(96% - "+f+"px)":"96%";g.xm(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:c?c+"px":"","max-width":h,"max-height":h,margin:"",transform:""});this.FO(a);e={transform:e,top:"",left:"",
width:b?b+"px":"",height:c?c+"px":"","max-width":"","max-height":""};var l=this.j.Ik*.96+2;h=this.j.Lm;switch(h){case 0:case 3:case 6:(d=this.j.Oe.fontSizeIncrement)&&d>0&&this.j.Si!==2&&this.j.Si!==3&&(l=Math.max(l/(1+d*2),2));e.left=l+"%";break;case 1:case 4:case 7:e.left=l+"%";l=this.D.offsetWidth;b||l?(b=b||l+1,e.width=b+"px",e["margin-left"]=d?b/-2-f/2+"px":b/-2+"px"):e.transform+=" translateX(-50%)";break;case 2:case 5:case 8:e.right=100-l+"%"}d=this.j.yp*.96+2;switch(h){case 0:case 1:case 2:e.top=
d+"%";break;case 3:case 4:case 5:e.top=d+"%";(c=c||this.element.clientHeight)?(e.height=c+"px",e["margin-top"]=c/-2+"px"):e.transform+=" translateY(-50%)";break;case 6:case 7:case 8:e.bottom=100-d+"%"}g.xm(this.element,e);if(this.G){c=this.D.offsetHeight;d=1;for(b=0;b<a.length;b++)e=a[b],typeof e.text==="string"&&(d+=e.text.split("\n").length-1,e.append||b===0||d++);c/=d;this.G.style.height=c+"px";this.G.style.width=c+"px";this.element.style.paddingLeft=c+5+"px";this.element.style.paddingRight=c+
5+"px";a=Number(this.element.style.marginLeft.replace("px",""))-c-5;c=Number(this.element.style.marginRight.replace("px",""))-c-5;this.element.style.marginLeft=a+"px";this.element.style.marginRight=c+"px"}};
g.k.FO=function(a){var b;for(b=0;b<a.length&&a[b]===this.K[b];b++);if(this.Fa||this.K.length>b)b=0,this.Fa=!1,this.K=[],this.N=this.La=this.Ja=null,g.mh(this.D);for(;b<a.length;b++)Mfb(this,a[b])};
g.k.MY=function(){return 0};
g.k.LY=function(){return 0};
g.k.toString=function(){return g.U.prototype.toString.call(this)};Ofb.prototype.clear=function(){this.C=this.time=this.mode=0;this.j=[];this.reset()};
Ofb.prototype.reset=function(){this.mode=0;this.D.reset(0);this.G.reset(1)};
var Pfb=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];q3.prototype.set=function(a){this.type=a};
q3.prototype.get=function(){return this.type};
r3.prototype.clear=function(){this.state=0};
r3.prototype.update=function(){this.state=this.state===2?1:0};
r3.prototype.qe=function(){return this.state!==0};
r3.prototype.matches=function(a,b){return this.qe()&&a===this.Tw&&b===this.Kt};
Ufb.prototype.reset=function(){this.timestamp=this.j=0};
s3.prototype.updateTime=function(a){for(var b=1;b<=15;++b)for(var c=1;c<=32;++c)this.B[b][c].timestamp=a};
s3.prototype.debugString=function(){for(var a="\n",b=1;b<=15;++b){for(var c=1;c<=32;++c){var d=this.B[b][c];a=d.j===0?a+"_":a+String.fromCharCode(d.j)}a+="\n"}return a};
s3.prototype.reset=function(a){for(var b=0;b<=15;b++)for(var c=0;c<=32;c++)this.B[b][c].reset();this.C=a;this.j=0;this.col=this.row=1};
var Vfb=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],Wfb=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],Xfb=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],pgb=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];tgb.prototype.reset=function(a,b){this.G=b;this.style.set(2);this.B=this.K;this.D=this.N;this.j=this.B;var c=(a<<2)+(b<<1);this.K.reset(c);this.N.reset(c);this.text.reset((a<<2)+(b<<1)+1)};
Nfb.prototype.reset=function(a){this.G=a;this.B.clear();this.D=this.C;this.C.reset(a,0);this.K.reset(a,1)};xgb.prototype.D=function(){};g.z(x3,g.pE);x3.prototype.toString=function(){return g.pE.prototype.toString.call(this)};g.z(y3,g.O);y3.prototype.fp=function(){return[]};
y3.prototype.reset=function(){};g.z(z3,g.pE);z3.prototype.toString=function(){return g.pE.prototype.toString.call(this)};
var A3=0;g.z(B3,y3);B3.prototype.reset=function(){this.K={};this.B=this.j=null;this.G=!0};
B3.prototype.fp=function(a,b){a=a.firstChild;a.getAttribute("format");b=b||0;Number.isFinite(b);a=Array.from(a.childNodes);a=g.w(a);for(var c=a.next();!c.done;c=a.next())if(c=c.value,c.nodeType===1)switch(c.tagName){case "head":var d=c;break;case "body":var e=c}if(d)for(d=Array.from(d.childNodes),d=g.w(d),a=d.next();!a.done;a=d.next())if(a=a.value,a.nodeType===1)switch(a.tagName){case "pen":c=a.getAttribute("id");var f=this.pens,h={},l=a.getAttribute("p");l&&Object.assign(h,this.pens[l]);l=D3(a,"b");
l!=null&&(h.bold=l);l=D3(a,"i");l!=null&&(h.italic=l);l=D3(a,"u");l!=null&&(h.underline=l);l=E3(a,"et");l!=null&&(h.charEdgeStyle=l);l=E3(a,"of");l!=null&&(h.offset=l);l=G3(a,"bc");l!=null&&(h.background=l);l=G3(a,"ec");l!=null&&(h.YO=l);l=G3(a,"fc");l!=null&&(h.color=l);l=E3(a,"fs");l!=null&&l!==0&&(h.fontFamily=l);l=C3(a,"sz");l!==void 0&&(h.fontSizeIncrement=l/100-1);l=C3(a,"bo");l!==void 0&&(h.backgroundOpacity=l/255);l=C3(a,"fo");l!==void 0&&(h.textOpacity=l/255);l=E3(a,"rb");l!=null&&l!==10&&
l!==0&&(h.fg=l>10?l-1:l);a=E3(a,"hg");a!=null&&(h.HZ=a);f[c]=h;break;case "ws":c=a.getAttribute("id");this.Z[c]=Bgb(this,a);break;case "wp":c=a.getAttribute("id"),this.N[c]=Cgb(this,a)}if(e){d=[];e=Array.from(e.childNodes);e=g.w(e);for(a=e.next();!a.done;a=e.next())if(a=a.value,a.nodeType===1)switch(a.tagName){case "w":this.j=Dgb(this,a,b,!1);(a=this.K[this.j.id])&&a.end>this.j.start&&(a.end=this.j.start);this.K[this.j.id]=this.j;d.push(this.j);break;case "p":var m=a;l=b;c=[];f=m.getAttribute("w")||
this.D;h=!!D3(m,"a");l=(C3(m,"t")||0)+l;var n=C3(m,"d")||5E3;h||(!this.G&&this.B&&this.B.windowId===f&&this.B.end>l&&(this.B.end=l),this.B&&this.B.text==="\n"&&(this.B.text=""));var p=h?6:5,q=m.getAttribute("p");q=q?this.pens[q]:null;var r=Array.from(m.childNodes);r.length&&(this.G=m.getAttribute("d")!=null);for(m=0;m<r.length;m++){var t=r[m],u=void 0;m>0&&(h=!0);var y=void 0;t.nodeType===1&&(y=t);if(y&&y.tagName==="s"){if((t=(t=y.getAttribute("p"))?this.pens[t]:null)&&t.fg&&(t.fg===1?(t=r.slice(m,
m+4),t.length===4&&(u=zgb(l,n,f,h,p,t,this.pens),m+=3)):u=zgb(l,n,f,h,p,[y],this.pens)),!u){var A=y;u=l;y=n;t=f;var C=h,F=p,H=A.textContent?A.textContent:"",N=A.getAttribute("p");N=N?this.pens[N]:null;A=C3(A,"t")||0;u=new x3(u+A,y-A,F,t,H,C,N)}}else u=new x3(l,n,p,f,t.textContent||"",h,q);c.push(u);this.B=u}if(c.length>0)for(c[0].windowId===this.D&&(this.j=Dgb(this,a,b,!0),d.push(this.j)),a=g.w(c),c=a.next();!c.done;c=a.next())c=c.value,c.windowId=this.j.id,this.j.j.push(c),d.push(c)}b=d}else b=[];
return b};var jhb=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]);g.z(H3,y3);H3.prototype.reset=function(){this.B.clear()};
H3.prototype.fp=function(a,b){var c=JSON.parse(a);if(!c)return[];if(c.pens){a=0;for(var d=g.w(c.pens),e=d.next();!e.done;e=d.next()){e=e.value;var f={},h=e.pParentId;h&&Object.assign(f,this.j.get(h));e.bAttr&&(f.bold=!0);e.iAttr&&(f.italic=!0);e.uAttr&&(f.underline=!0);h=e.ofOffset;h!=null&&(f.offset=h);e.szPenSize!==void 0&&(f.fontSizeIncrement=e.szPenSize/100-1);h=e.etEdgeType;h!=null&&(f.charEdgeStyle=h);e.ecEdgeColor!==void 0&&(f.YO=I3(e.ecEdgeColor));h=e.fsFontStyle;h!=null&&h!==0&&(f.fontFamily=
h);e.fcForeColor!==void 0&&(f.color=I3(e.fcForeColor));e.foForeAlpha!==void 0&&(f.textOpacity=e.foForeAlpha/255);e.bcBackColor!==void 0&&(f.background=I3(e.bcBackColor));e.boBackAlpha!==void 0&&(f.backgroundOpacity=e.boBackAlpha/255);(h=e.rbRuby)&&h!==10&&(f.fg=h>10?h-1:h,f.vp=jhb.get(f.fg));e.hgHorizGroup&&(f.HZ=e.hgHorizGroup);this.j.set(a++,f)}}if(c.wsWinStyles)for(a=0,d=g.w(c.wsWinStyles),e=d.next();!e.done;e=d.next())e=e.value,f={},(h=e.wsParentId)?Object.assign(f,this.D.get(h)):Object.assign(f,
this.G),e.mhModeHint!==void 0&&(f.FB=e.mhModeHint),e.juJustifCode!==void 0&&(f.textAlign=e.juJustifCode),e.pdPrintDir!==void 0&&(f.Si=e.pdPrintDir),e.sdScrollDir!==void 0&&(f.HU=e.sdScrollDir),e.wfcWinFillColor!==void 0&&(f.windowColor=I3(e.wfcWinFillColor)),e.wfoWinFillAlpha!==void 0&&(f.windowOpacity=e.wfoWinFillAlpha/255),this.D.set(a++,f);if(c.wpWinPositions)for(a=0,d=g.w(c.wpWinPositions),e=d.next();!e.done;e=d.next())e=e.value,f={},(h=e.wpParentId)&&Object.assign(f,this.C.get(h)),e.ahHorPos!==
void 0&&(f.Ik=e.ahHorPos),e.apPoint!==void 0&&(f.Lm=e.apPoint),e.avVerPos!==void 0&&(f.yp=e.avVerPos),e.ccCols!==void 0&&(f.Nt=e.ccCols),e.rcRows!==void 0&&(f.Os=e.rcRows),this.C.set(a++,f);if(c.events){a=[];c=g.w(c.events);for(d=c.next();!d.done;d=c.next()){var l=d.value;e=(l.tStartMs||0)+b;f=l.dDurationMs||0;if(l.id)h=String(l.id),d=Egb(this,l,e,f,h),a.push(d),this.B.set(h,d);else{l.wWinId?h=l.wWinId.toString():(h="_"+A3++,d=Egb(this,l,e,f,h),a.push(d),this.B.set(h,d));d=a;var m=l;f===0&&(f=5E3);
l=this.B.get(h);var n=!!m.aAppend,p=n?6:5,q=m.segs,r=null;m.pPenId&&(r=this.j.get(m.pPenId));for(m=0;m<q.length;m++){var t=q[m],u=t.utf8;if(u){var y=t.tOffsetMs||0,A=null;t.pPenId&&(A=this.j.get(t.pPenId));if((l.params.FB!=null?l.params.FB:l.j.length>1?1:0)===2&&n&&u==="\n")continue;t=null;var C=[],F;if(F=A&&A.fg===1){F=q;var H=m;if(H+3>=F.length||!F[H+1].pPenId||!F[H+2].pPenId||!F[H+3].pPenId)F=!1;else{var N=F[H+1].pPenId;(N=this.j.get(N))&&N.fg&&N.fg===2?(N=F[H+2].pPenId,N=this.j.get(N),!N||!N.fg||
N.fg<3?F=!1:(N=F[H+3].pPenId,F=(N=this.j.get(N))&&N.fg&&N.fg===2?!0:!1)):F=!1}}if(F)y=q[m+1].utf8,t=q[m+3].utf8,F=q[m+2].utf8,H=this.j.get(q[m+2].pPenId),u=ygb(u,y,F,t,H),t=new x3(e,f,p,h,u,n,A),m+=3;else{if(u.indexOf("<")>-1){var M=void 0;C=A;F=r;H=e;N=f;var X=y,W=p,fa=n,pa=[],aa=g.a1("<html>"+u+"</html>");if(!aa.getElementsByTagName("parsererror").length&&((M=aa.firstChild)==null?0:M.childNodes.length))for(M=g.w(aa.firstChild.childNodes),aa=M.next();!aa.done;aa=M.next()){aa=aa.value;var R=void 0,
T=void 0,v=(T=(R=aa.textContent)==null?void 0:R.replace(/\n/g,""))!=null?T:"";if(aa.nodeType!==3||v&&v.match(/^ *$/)==null){R={};Object.assign(R,C||F);T=void 0;switch((T=aa)==null?void 0:T.tagName){case "b":R.bold=!0;break;case "i":R.italic=!0;break;case "u":R.underline=!0}pa.push(new x3(H+X,N-X,W,l.id,v,fa,R))}}C=pa}C.length||(C=[new x3(e+y,f-y,p,l.id,u,n,A||r)])}if(C.length)for(n=g.w(C),A=n.next();!A.done;A=n.next())A=A.value,d.push(A),l.j.push(A);else t&&(d.push(t),l.j.push(t))}n=!0}}}b=a}else b=
[];return b};g.z(J3,g.XX);J3.prototype.Mu=function(a,b,c){rfb(this.videoData.videoId,a.vssId,c)};
J3.prototype.sB=function(a){if(this.audioTrack)for(var b=g.w(this.audioTrack.captionTracks),c=b.next();!c.done;c=b.next())g.WX(this.B,c.value);a()};g.z(K3,o3);K3.prototype.FO=function(a){var b=this.B.j;o3.prototype.FO.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.j===e)var d=f;else{d={};Object.assign(d,c.j);Object.assign(d,khb);var e=c.j;var f=d}Mfb(this,c,d)}};
var khb={v$:!0};g.z(L3,xgb);L3.prototype.D=function(a,b,c,d,e){if(c<d){var f="_"+A3++;c=c/1E3-this.K;d=d/1E3-this.K;a=new z3(c,d-c,5,f,{textAlign:0,Lm:0,Ik:b*2.5,yp:a*5.33});e=new x3(c,d-c,5,f,e);this.B.push(a);this.B.push(e)}};
g.z(O3,y3);O3.prototype.fp=function(a){a=new L3(a,a.byteLength,this.B);if(Fgb(a)){for(;a.byteOffset<a.j.byteLength;)for(a.version===0?a.C=N3(a)*(1E3/45):a.version===1&&(a.C=N3(a)*4294967296+N3(a)),a.G=M3(a);a.G>0;a.G--){var b=M3(a),c=M3(a),d=M3(a);b&4&&(b&3)===this.track&&(this.track===0||this.track===1)&&(b=this.j,b.j.push({time:a.C,type:this.track,IX:c,JX:d,order:b.j.length}))}Tfb(this.j,a);return a.B}return[]};
O3.prototype.reset=function(){this.j.clear()};g.z(P3,o3);g.k=P3.prototype;g.k.j2=function(){g.kp(this.Ta)};
g.k.xca=function(){g.sp(this.element,"ytp-rollup-mode");this.IC(this.Sb,!0)};
g.k.LY=function(){return this.C?this.oa:this.W};
g.k.MY=function(){return this.C?this.W:this.oa};
g.k.IC=function(a,b){this.Sb=a;if(this.B.params.Os){for(var c=0,d=0;d<this.K.length&&c<a.length;d++)this.K[d]===a[c]&&c++;c>0&&c<a.length&&(a=this.K.concat(a.slice(c)));this.Gb=this.oa;this.W=this.oa=0;o3.prototype.IC.call(this,a);Jgb(this,b)}o3.prototype.IC.call(this,a)};g.z(Q3,y3);
Q3.prototype.fp=function(a,b){var c=[];a=a.split(lhb);for(var d=1;d<a.length;d++){var e=a[d],f=b;if(e!==""&&!mhb.test(e)){var h=nhb.exec(e);if(h&&h.length>=4){var l=Lgb(h[1]),m=Lgb(h[2])-l;l+=f;var n=(h=h[3])?h.split(" "):[];h={};var p=null;var q="";var r=null,t="";n=g.w(n);for(var u=n.next();!u.done;u=n.next())if(u=u.value.split(":"),u.length===2){var y=u[1];switch(u[0]){case "line":u=y.split(",");u[0].endsWith("%")&&(p=u[0],h.yp=Number.parseInt(p,10),u.length===2&&(q=u[1].trim()));break;case "position":u=
y.split(",");r=u[0];h.Ik=Number.parseInt(r,10);u.length===2&&(t=u[1].trim());break;case "align":switch(y){case "start":h.textAlign=0;break;case "middle":h.textAlign=2;break;case "end":h.textAlign=1}}}p||q||(q="end");if(!r)switch(h.textAlign){case 0:h.Ik=0;break;case 1:h.Ik=100;break;case 2:h.Ik=50}if(h.textAlign!=null){p=0;switch(q){case "center":p+=3;break;case "end":p+=6;break;default:p+=0}switch(t){case "line-left":p+=0;break;case "center":p+=1;break;case "line-right":p+=2;break;default:switch(h.textAlign){case 0:p+=
0;break;case 2:p+=1;break;case 1:p+=2}}q=p<0||p>8?7:p;h.Lm=q}e=e.substring(nhb.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");t=h;h=e;e={};if(h.indexOf("<")<0&&h.indexOf("&")<0)f=Mgb(l,m,5,t),m=new x3(l,m,5,f.id,h,!1,g.Og(e)?void 0:e),c.push(f),c.push(m),f.j.push(m);else for(q=h.split(ohb),q.length===1?(h=5,t=Mgb(l,m,h,t)):(p=h=6,t=Object.assign({Nt:32},t),t=new z3(l,m,p,"_"+A3++,t)),c.push(t),p=l,r=0;r<q.length;r++)n=q[r],r%2===0?(u=g.a1("<html>"+n+"</html>"),u.getElementsByTagName("parsererror").length?
(y=u.createElement("span"),y.appendChild(u.createTextNode(n))):y=u.firstChild,Kgb(this,p,m-(p-l),h,t,r>0,y,e,c)):p=Lgb(n)+f}nhb.lastIndex=0}}return c};
var mhb=/^NOTE/,lhb=/(?:\r\n|\r|\n){2,}/,nhb=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),ohb=RegExp("<((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})>");g.c_.aL(Q3,{fp:"wvppt"});g.z(R3,g.O);
R3.prototype.fp=function(a,b,c,d){c=c||0;d=d||0;if(this.B&&a||this.Y.L("html5_use_subfragcaps_parser_for_all_live")){a:{var e=d,f=Pgb(this,a,c),h=[];try{for(var l=g.w(f),m=l.next();!m.done;m=l.next()){var n=m.value,p=n.trackData,q=n.BU;h=typeof p!=="string"?h.concat(Qgb(this,b,p,q,e)):p.substring(0,6)==="WEBVTT"?h.concat(Rgb(this,p,q)):h.concat(Tgb(this,b,p,q))}var r=h;break a}catch(u){this.logger.j(187101178,"SS caps parsing failure fallback: "+u.message+". ");this.clear();r=null;break a}r=void 0}if(r!==
null&&r.length!==0)return r;if(this.Y.L("html5_disable_subfragcaps_fallback"))return[];r===null?(r=this.logger,g.yOa(r.tag,5,"SS caps fallback due to parse failure.",r.B)):this.logger.info("SS caps fallback due to no data received.")}if(a=Ngb(a))try{var t=typeof a!=="string"?Qgb(this,b,a,c,d):a.substring(0,6)==="WEBVTT"?Rgb(this,a,c):Tgb(this,b,a,c)}catch(u){this.clear(),t=[]}else t=[];return t};
R3.prototype.clear=function(){this.j&&this.j.dispose();this.j=null};
R3.prototype.reset=function(){this.j&&this.j.reset()};
R3.prototype.xa=function(){g.O.prototype.xa.call(this);this.clear()};var $3={windowColor:"#080808",windowOpacity:0,textAlign:2,Lm:7,Ik:50,yp:100,isDefault:!0,Oe:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.z(S3,g.UX);g.k=S3.prototype;g.k.xa=function(){if(this.D||this.Ca){var a=this.J.Ce();a&&!a.Ia()&&a.cA()}else ihb(this,!1);g.UX.prototype.xa.call(this)};
g.k.nU=function(){return this.Y.L("html5_honor_caption_availabilities_in_audio_track")&&!this.Va};
g.k.Dv=function(){if(this.Ta)return this.D||this.Ca;var a=this.getAudioTrack();if(this.nU()){if(!a.captionTracks.length)return!1;if(!this.j)return!0}a=ofb(a,g.DP(this.Y));return a==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?!0:a==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"?T3(this):Xgb(this)||T3(this)?!0:Ygb(this)};
g.k.load=function(){var a=this;g.UX.prototype.load.call(this);this.Z=this.getAudioTrack();this.j?this.B&&(this.Wa.clear(),this.D?bhb(this,!0):this.player.getPresentingPlayerType()!==3&&this.j.Mu(this.B,"json3",function(b,c,d,e){if(b){var f;dhb(a,(f=a.B)!=null?f:void 0);a.j.oT()&&(a.Fa=[],a.J.gf("captions"),l3(a.Ja),a.Wa.reset());if(a.videoData.Ad){var h;d=((h=d)!=null?h:0)+a.videoData.Ad}b=a.Wa.fp(b,c,d,e);if(a.ib)for(c=g.w(b),e=c.next();!e.done;e=c.next())e=e.value,e.C=a.videoData.clientPlaybackNonce,
e.Zl=a.videoData.Ad;c=!a.Y.L("html5_keep_caption_data_after_seek")&&a.Va;a.player.lf(b,void 0,c);!a.N||a.Ca||W3(a)||!a.Y.In||g.ND(a.Y)||g.pP(a.Y)||g.Zy(a.Y)||a.Y.Ja==="shortspage"||a.player.isInline()||(g.lp(a.La),b=Agb({Lm:0,Ik:5,yp:5,Os:2,textAlign:0,Si:0,lang:"en"}),a.Na=[b],c=["Click "," for settings"],a.kb||(e=new g.xx(g.Qx()),g.P(a,e),a.kb=e.element),e=b.end-b.start,(f=g.VP(a.B))&&a.Na.push(new x3(b.start,e,0,b.id,f)),a.Na.push(new x3(b.start,e,0,b.id,c[0]),new x3(b.start,e,0,b.id,a.kb,!0),
new x3(b.start,e,0,b.id,c[1],!0)),a.player.lf(a.Na),g.jp(a.La));!a.N||a.Ca||W3(a)||(g.DP(a.Y)?Y3(a,!0):Z3(a,!0),a.Z&&(a.Z.D=a.B),a.player.Dp());a.N=!1}}),this.D||this.Ca||W3(this)||this.player.xd("captionschanged",g.WP(this.B))):(this.j=Zgb(this),g.P(this,this.j),this.j.sB(function(){ahb(a)}))};
g.k.unload=function(){this.D&&this.B?bhb(this,!1):(this.La&&g.lp(this.La),this.player.gf("captions"),this.Fa=[],this.j&&this.j.nt(),this.Wa.clear(),this.W&&this.player.lf(this.W),this.UU());g.UX.prototype.unload.call(this);this.player.Dp();this.player.xd("captionschanged",{})};
g.k.create=function(){this.Dv()&&this.load();var a;a:{var b,c,d;if(this.Y.L("web_player_nitrate_promo_tooltip")&&((b=this.videoData.getPlayerResponse())==null?0:(c=b.captions)==null?0:(d=c.playerCaptionsTracklistRenderer)==null?0:d.enableTouchCaptionsNitrate)){var e,f;if(b=(a=this.videoData.getPlayerResponse())==null?void 0:(e=a.captions)==null?void 0:(f=e.playerCaptionsTracklistRenderer)==null?void 0:f.captionTracks)for(a=g.w(b),e=a.next();!e.done;e=a.next())if(e=e.value,e.kind==="asr"&&e.languageCode===
"en"){a=!0;break a}}a=!1}a&&this.J.publish("showpromotooltip",this.K.element)};
g.k.fda=function(){for(var a=this.J.Ce().Ib().textTracks,b=null,c=0;c<a.length;c++)if(a[c].mode==="showing")a:{b=g.VX(this.j.B,!0);for(var d=0;d<b.length;d++)if(b[d].toString()===a[c].id){b=b[d];break a}b=null}(this.loaded?this.B:null)!==b&&X3(this,b,!0)};
g.k.Ifa=function(){!this.B&&this.D||this.unload()};
g.k.onCueRangeEnter=function(a){this.Fa.push(a);l3(this.Ja)};
g.k.onCueRangeExit=function(a){g.Ub(this.Fa,a);this.j instanceof n3&&this.j.N&&this.player.pp([a]);l3(this.Ja)};
g.k.getCaptionWindowContainerId=function(){return this.K.element.id};
g.k.fea=function(){hhb(this,this.Na);this.Na=null};
g.k.TU=function(){var a=this;if(!this.Ab||!this.D){this.Ja.stop();g.Fea(this.Ua);this.Fa.sort(g.qE);var b=this.Fa;if(this.W){var c=g.tn(b,function(f){return this.W.indexOf(f)===-1},this);
c.length&&(b=c)}b=g.w(b);for(c=b.next();!c.done;c=b.next())fhb(this,c.value);b=g.w(Object.entries(this.Aa));var d=b.next();for(c={};!d.done;c={VA:void 0,Xp:void 0},d=b.next()){var e=g.w(d.value);d=e.next().value;e=e.next().value;c.VA=d;c.Xp=e;this.Ua[c.VA]?(c.Xp.element.parentNode||(c.Xp instanceof P3||c.Xp instanceof K3||g.Hg(this.Aa,function(f){return function(h,l){l!==f.VA&&h.B.params.Lm===f.Xp.B.params.Lm&&h.B.params.Ik===f.Xp.B.params.Ik&&h.B.params.yp===f.Xp.B.params.yp&&(h.dispose(),delete a.Aa[l]);
return l===f.VA}}(c),this),this.K.element.appendChild(c.Xp.element)),c.Xp.IC(this.Ua[c.VA])):(c.Xp.dispose(),delete this.Aa[c.VA])}}};
g.k.mea=function(){Vgb(this,{},!0);this.player.xd("captionssettingschanged")};
g.k.H9=function(){var a=$3.Oe;a={background:a.background,backgroundOpacity:a.backgroundOpacity,charEdgeStyle:a.charEdgeStyle,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.fontSizeIncrement,fontStyle:a.bold&&a.italic?3:a.bold?1:a.italic?2:0,textOpacity:a.textOpacity,windowColor:$3.windowColor,windowOpacity:$3.windowOpacity};var b=wfb()||{};b.background!=null&&(a.background=b.background);b.backgroundOverride!=null&&(a.backgroundOverride=b.backgroundOverride);b.backgroundOpacity!=null&&(a.backgroundOpacity=
b.backgroundOpacity);b.backgroundOpacityOverride!=null&&(a.backgroundOpacityOverride=b.backgroundOpacityOverride);b.charEdgeStyle!=null&&(a.charEdgeStyle=b.charEdgeStyle);b.charEdgeStyleOverride!=null&&(a.charEdgeStyleOverride=b.charEdgeStyleOverride);b.color!=null&&(a.color=b.color);b.colorOverride!=null&&(a.colorOverride=b.colorOverride);b.fontFamily!=null&&(a.fontFamily=b.fontFamily);b.fontFamilyOverride!=null&&(a.fontFamilyOverride=b.fontFamilyOverride);b.fontSizeIncrement!=null&&(a.fontSizeIncrement=
b.fontSizeIncrement);b.fontSizeIncrementOverride!=null&&(a.fontSizeIncrementOverride=b.fontSizeIncrementOverride);b.fontStyle!=null&&(a.fontStyle=b.fontStyle);b.fontStyleOverride!=null&&(a.fontStyleOverride=b.fontStyleOverride);b.textOpacity!=null&&(a.textOpacity=b.textOpacity);b.textOpacityOverride!=null&&(a.textOpacityOverride=b.textOpacityOverride);b.windowColor!=null&&(a.windowColor=b.windowColor);b.windowColorOverride!=null&&(a.windowColorOverride=b.windowColorOverride);b.windowOpacity!=null&&
(a.windowOpacity=b.windowOpacity);b.windowOpacityOverride!=null&&(a.windowOpacityOverride=b.windowOpacityOverride);return a};
g.k.W3=function(a,b){var c={};Object.assign(c,wfb());Object.assign(c,a);Vgb(this,c,b);this.player.xd("captionssettingschanged")};
g.k.UU=function(){!this.D&&this.loaded&&(g.Eg(this.Aa,function(a,b){a.dispose();delete this.Aa[b]},this),this.TU())};
g.k.ai=function(a,b){switch(a){case "fontSize":if(isNaN(b))break;var c=g.xg(b,-2,4);this.W3({fontSizeIncrement:c});return c;case "reload":b&&!this.D&&X3(this,this.B,!0);break;case "stickyLoading":b!==void 0&&this.Y.N&&(g.DP(this.Y)?Y3(this,!!b):Z3(this,!!b));break;case "track":if(!this.j)return{};if(b){this.Y.L("html5_report_caption_format_intent")&&!g.Og(b)&&this.Vk(b.vss_id,"m");if(this.D)break;if(!g.Ra(b))break;if(g.Og(b)){X3(this,null,!0);break}a=g.VX(this.j.B,!0);for(var d=0;d<a.length;d++){var e=
a[d];e.languageCode!==b.languageCode||c&&(e.languageName!==b.languageName||(e.captionId||"")!==(b.captionId||"")||g.VP(e)!==b.displayName)||(c=b.translationLanguage?pfb(e,b.translationLanguage):e)}this.uN(b.position);!c||c===this.B&&this.loaded||(b=g.uL(),a=g.XP(c),b.length&&a===b[b.length-1]||(b.push(a),g.Qs("yt-player-caption-language-preferences",b)),g.DP(this.Y)&&!this.J.isInline()&&g.Qs("yt-player-caption-sticky-language",a,2592E3),X3(this,c,!0))}else return this.loaded&&this.B&&!W3(this)?g.WP(this.B):
{};return"";case "tracklist":return this.j?g.Il(g.VX(this.j.B,!(!b||!b.includeAsr)),function(f){return g.WP(f)}):[];
case "translationLanguages":return this.j?this.j.G.map(function(f){return Object.assign({},f)}):[];
case "sampleSubtitles":this.D||b===void 0||ihb(this,!!b);break;case "sampleSubtitlesCustomized":this.D||ihb(this,!!b,b);break;case "recommendedTranslationLanguages":return g.uL();case "defaultTranslationSourceTrackIndices":return this.j?this.j.Z:[]}};
g.k.getOptions=function(){var a="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.Y.N&&a.push("stickyLoading");return a};
g.k.Xr=function(){var a=this.B;if(this.Y.L("html5_cue_ranges_based_caption_vss")&&!this.J.PK("captions"))return{};if(this.Y.L("html5_modify_caption_vss_logging")){var b;return(a=(b=this.videoData.fE)!=null?b:null)?{cc:g.mKa(a)}:{}}return a?(b=a.vssId,a.translationLanguage&&b&&(b="t"+b+"."+g.XP(a)),{cc:b}):{}};
g.k.ufa=function(){this.isSubtitlesOn()?(g.DP(this.Y)?Y3(this,!1):Z3(this,!1),dhb(this),this.Y.L("html5_report_caption_format_change")?X3(this,null,!0):(this.unload(),T3(this,!0)&&X3(this,U3(this),!1))):this.x3()};
g.k.x3=function(){var a=W3(this)||!this.B?V3(this,!0):this.B;this.Y.L("html5_report_caption_format_intent")&&a&&this.Vk(a.vssId,"m");this.isSubtitlesOn()||X3(this,W3(this)||!this.B?V3(this,!0):this.B,!0)};
g.k.isSubtitlesOn=function(){return!!this.loaded&&!!this.B&&!W3(this)};
g.k.TG=function(){this.j&&this.j.TG()};
g.k.Saa=function(){var a=W3(this);T3(this,a)?X3(this,this.getAudioTrack().j,!1):this.videoData.captionTracks.length&&(this.loaded&&this.unload(),this.nU()&&(this.N=!1,this.B=null,this.j&&(this.j.dispose(),this.j=null)),this.Dv()&&(a?X3(this,V3(this),!1):this.load()))};
g.k.uN=function(a){a&&(this.qa={top:a.top,right:a.right,bottom:a.bottom,left:a.left,width:1-a.left-a.right,height:1-a.top-a.bottom},this.K.element.style.top=this.qa.top*100+"%",this.K.element.style.left=this.qa.left*100+"%",this.K.element.style.width=this.qa.width*100+"%",this.K.element.style.height=this.qa.height*100+"%",this.K.element.style.position="absolute",a=ghb(this))&&(this.K.element.style.width=a.width+"px",this.K.element.style.height=a.height+"px")};
g.k.onVideoDataChange=function(a,b){a==="newdata"&&(this.videoData=b,this.loaded&&this.unload(),this.N=!1,this.B=null,this.j&&(this.j.dispose(),this.j=null,this.player.xd("captionschanged",{})),this.Dv()&&this.load())};
g.k.getAudioTrack=function(){return this.ib&&this.player.getPresentingPlayerType()===2?this.videoData.bl:this.player.getAudioTrack()};
g.k.Gba=function(){var a=this.J.Ce();a&&!a.Ia()&&a.cA();this.J.isFullscreen()?(this.D=this.Ta=!0,this.loaded&&ahb(this)):(this.Ta=this.Y.controlsType==="3",this.D=Ugb(this));X3(this,this.B)};
g.k.HN=function(){var a,b,c,d=(a=this.videoData.getPlayerResponse())==null?void 0:(b=a.captions)==null?void 0:(c=b.playerCaptionsTracklistRenderer)==null?void 0:c.openTranscriptCommand;d&&this.player.fb("innertubeCommand",d)};
g.k.mj=function(a,b,c){var d=/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,e="";a&&(e=a.vssId,e=e.replace(d,""));var f="";a&&a.getId()&&(f=a.getId()||"",f=f.replace(d,""));a&&a.getXtags()&&(a=a.getXtags(),a=a.replace(d,""),f=f.concat(";"+a));this.J.mj(b?e:"",b?f:"",c)};
g.k.Vk=function(a,b){a=(a||"").replace(/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,"");this.J.Vk(a,b)};
g.k.EH=function(){this.j instanceof n3&&this.j.EH()};
g.c_.aL(S3,{TU:"smucd"});g.TX("captions",S3);})(_yt_player);
