(function(g){var window=this;'use strict';var ckb=function(a,b){a.fb("onAutonavCoundownStarted",b)},k5=function(a,b,c){g.up(a.element,"ytp-suggestion-set",!!b.videoId);
var d=b.playlistId;c=b.kh(c?c:"mqdefault.jpg");var e=null,f=null;b instanceof g.eQ&&(b.lengthText?(e=b.lengthText||null,f=b.Zx||null):b.lengthSeconds&&(e=g.My(b.lengthSeconds),f=g.My(b.lengthSeconds,!0)));var h=!!d;d=h&&g.cQ(d).type==="RD";var l=b instanceof g.eQ?b.isLivePlayback:null,m=b instanceof g.eQ?b.isUpcoming:null,n=b.author,p=b.shortViewCount,q=b.publishedTimeText,r=[],t=[];n&&r.push(n);p&&(r.push(p),t.push(p));q&&t.push(q);c={title:b.title,author:n,author_and_views:r.join(" \u2022 "),aria_label:b.ariaLabel||
g.CE("Watch $TITLE",{TITLE:b.title}),duration:e,timestamp:f,url:b.Nl(),is_live:l,is_upcoming:m,is_list:h,is_mix:d,background:c?"background-image: url("+c+")":"",views_and_publish_time:t.join(" \u2022 "),autoplayAlternativeHeader:b.Jt};b instanceof g.dQ&&(c.playlist_length=b.playlistLength);a.update(c)},l5=function(a){var b=a.U(),c=b.D;
g.U.call(this,{I:"a",S:"ytp-autonav-suggestion-card",X:{href:"{{url}}",target:c?b.W:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},V:[{I:"div",Ka:["ytp-autonav-endscreen-upnext-thumbnail","ytp-autonav-thumbnail-small"],X:{style:"{{background}}"},V:[{I:"div",X:{"aria-label":"{{timestamp}}"},Ka:["ytp-autonav-timestamp"],va:"{{duration}}"},{I:"div",Ka:["ytp-autonav-live-stamp"],va:"Live"},{I:"div",
Ka:["ytp-autonav-upcoming-stamp"],va:"Upcoming"},{I:"div",S:"ytp-autonav-list-overlay",V:[{I:"div",S:"ytp-autonav-mix-text",va:"Mix"},{I:"div",S:"ytp-autonav-mix-icon"}]}]},{I:"div",Ka:["ytp-autonav-endscreen-upnext-title","ytp-autonav-title-card"],va:"{{title}}"},{I:"div",Ka:["ytp-autonav-endscreen-upnext-author","ytp-autonav-author-card"],va:"{{author}}"},{I:"div",Ka:["ytp-autonav-endscreen-upnext-author","ytp-autonav-view-and-date-card"],va:"{{views_and_publish_time}}"}]});this.J=a;this.suggestion=
null;this.j=c;this.listen("click",this.onClick);this.listen("keypress",this.onKeyPress)},m5=function(a,b){b=b===void 0?!1:b;
g.U.call(this,{I:"div",S:"ytp-autonav-endscreen-countdown-overlay"});var c=this;this.K=b;this.cancelCommand=this.G=void 0;this.C=0;this.container=new g.U({I:"div",S:"ytp-autonav-endscreen-countdown-container"});g.P(this,this.container);this.container.Ha(this.element);b=a.U();var d=b.D;this.J=a;this.suggestion=null;this.onVideoDataChange("newdata",this.J.getVideoData());this.T(a,"videodatachange",this.onVideoDataChange);this.j=new g.U({I:"div",S:"ytp-autonav-endscreen-upnext-container",X:{"aria-label":"{{aria_label}}",
"data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},V:[{I:"div",S:"ytp-autonav-endscreen-upnext-header"},{I:"div",S:"ytp-autonav-endscreen-upnext-alternative-header",va:"{{autoplayAlternativeHeader}}"},{I:"a",S:"ytp-autonav-endscreen-link-container",X:{href:"{{url}}",target:d?b.W:""},V:[{I:"div",S:"ytp-autonav-endscreen-upnext-thumbnail",X:{style:"{{background}}"},V:[{I:"div",X:{"aria-label":"{{timestamp}}"},Ka:["ytp-autonav-timestamp"],
va:"{{duration}}"},{I:"div",Ka:["ytp-autonav-live-stamp"],va:"Live"},{I:"div",Ka:["ytp-autonav-upcoming-stamp"],va:"Upcoming"}]},{I:"div",S:"ytp-autonav-endscreen-video-info",V:[{I:"div",S:"ytp-autonav-endscreen-premium-badge"},{I:"div",S:"ytp-autonav-endscreen-upnext-title",va:"{{title}}"},{I:"div",S:"ytp-autonav-endscreen-upnext-author",va:"{{author}}"},{I:"div",S:"ytp-autonav-view-and-date",va:"{{views_and_publish_time}}"},{I:"div",S:"ytp-autonav-author-and-view",va:"{{author_and_views}}"}]}]}]});
g.P(this,this.j);this.j.Ha(this.container.element);d||this.T(this.j.Da("ytp-autonav-endscreen-link-container"),"click",this.sV);this.J.createClientVe(this.container.element,this,115127);this.J.createClientVe(this.j.Da("ytp-autonav-endscreen-link-container"),this,115128);this.overlay=new g.U({I:"div",S:"ytp-autonav-overlay"});g.P(this,this.overlay);this.overlay.Ha(this.container.element);this.B=new g.U({I:"div",S:"ytp-autonav-endscreen-button-container"});g.P(this,this.B);this.B.Ha(this.container.element);
this.cancelButton=new g.U({I:"button",Ka:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-cancel-button",b.L("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],X:{"aria-label":"Cancel autoplay"},va:"Cancel"});g.P(this,this.cancelButton);this.cancelButton.Ha(this.B.element);this.cancelButton.listen("click",this.l5,this);this.J.createClientVe(this.cancelButton.element,this,115129);this.playButton=new g.U({I:"a",Ka:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-play-button",
b.L("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],X:{href:"{{url}}",role:"button","aria-label":"Play next video"},va:"Play Now"});g.P(this,this.playButton);this.playButton.Ha(this.B.element);this.playButton.listen("click",this.sV,this);this.J.L("web_player_autonav_next_button_renderer")?(this.J.createServerVe(this.playButton.element,this.playButton,!0),(b=this.J.getVideoData())&&dkb(this,b)):this.J.createClientVe(this.playButton.element,this,115130);this.D=new g.ip(function(){ekb(c)},
500);
g.P(this,this.D);this.rV();this.T(a,"autonavvisibility",this.rV);this.J.L("web_autonav_color_transition")&&(this.T(a,"autonavchange",this.k5),this.T(a,"onAutonavCoundownStarted",this.Taa))},n5=function(a){var b=a.J.Fo(!0,a.J.isFullscreen());
g.up(a.container.element,"ytp-autonav-endscreen-small-mode",a.Rg(b));g.up(a.container.element,"ytp-autonav-endscreen-is-premium",!!a.suggestion&&!!a.suggestion.cN);g.up(a.J.getRootNode(),"ytp-autonav-endscreen-cancelled-state",!a.J.Ef());g.up(a.J.getRootNode(),"countdown-running",a.Ul());g.up(a.container.element,"ytp-player-content",a.J.Ef());g.xm(a.overlay.element,{width:b.width+"px"});if(!a.Ul()){a.J.Ef()?fkb(a,Math.round(gkb(a)/1E3)):fkb(a);b=!!a.suggestion&&!!a.suggestion.Jt;var c=a.J.Ef()||!b;
g.up(a.container.element,"ytp-autonav-endscreen-upnext-alternative-header-only",!c&&b);g.up(a.container.element,"ytp-autonav-endscreen-upnext-no-alternative-header",c&&!b);g.Ax(a.B,a.J.Ef());g.up(a.element,"ytp-enable-w2w-color-transitions",hkb(a))}},ekb=function(a){var b=gkb(a),c=Math,d=c.min;
var e=a.C?Date.now()-a.C:0;c=d.call(c,e,b);fkb(a,Math.ceil((b-c)/1E3));b-c<=500&&a.Ul()?a.select(!0):a.Ul()&&a.D.start()},gkb=function(a){if(a.J.isFullscreen()){var b;
a=(b=a.J.getVideoData())==null?void 0:b.VD;return a===-1||a===void 0?8E3:a}return a.J.Yt()>=0?a.J.Yt():g.zD(a.J.U().experiments,"autoplay_time")||1E4},dkb=function(a,b){a.J.L("web_player_autonav_next_button_renderer");
b=b.N4;a.G=b==null?void 0:b.navigationEndpoint;b=b==null?void 0:b.trackingParams;a.playButton&&b&&a.J.setTrackingParams(a.playButton.element,b)},hkb=function(a){var b;
return!((b=a.J.getVideoData())==null||!b.watchToWatchTransitionRenderer)},fkb=function(a,b){b=b===void 0?-1:b;
a=a.j.Da("ytp-autonav-endscreen-upnext-header");g.mh(a);if(b>=0){b=String(b);var c="Up next in $SECONDS".match(RegExp("\\$SECONDS","gi"))[0],d="Up next in $SECONDS".indexOf(c);if(d>=0){a.appendChild(g.kh("Up next in $SECONDS".slice(0,d)));var e=g.jh("span");g.op(e,"ytp-autonav-endscreen-upnext-header-countdown-number");g.qh(e,b);a.appendChild(e);a.appendChild(g.kh("Up next in $SECONDS".slice(d+c.length)));return}}g.qh(a,"Up next")},o5=function(a,b){g.U.call(this,{I:"div",
Ka:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.created=!1;this.player=a},p5=function(a){g.U.call(this,{I:"div",
Ka:["ytp-upnext","ytp-player-content"],X:{"aria-label":"{{aria_label}}"},V:[{I:"div",S:"ytp-cued-thumbnail-overlay-image",X:{style:"{{background}}"}},{I:"span",S:"ytp-upnext-top",V:[{I:"span",S:"ytp-upnext-header",va:"Up Next"},{I:"span",S:"ytp-upnext-title",va:"{{title}}"},{I:"span",S:"ytp-upnext-author",va:"{{author}}"}]},{I:"a",S:"ytp-upnext-autoplay-icon",X:{role:"button",href:"{{url}}","aria-label":"Play next video"},V:[{I:"svg",X:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},
V:[{I:"circle",S:"ytp-svg-autoplay-circle",X:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{I:"circle",S:"ytp-svg-autoplay-ring",X:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{I:"path",S:"ytp-svg-fill",X:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{I:"span",S:"ytp-upnext-bottom",V:[{I:"span",S:"ytp-upnext-cancel"},{I:"span",S:"ytp-upnext-paused",
va:"Autoplay is paused"}]}]});this.api=a;this.cancelButton=null;this.G=this.Da("ytp-svg-autoplay-ring");this.C=this.notification=this.j=this.suggestion=null;this.D=new g.ip(this.DJ,5E3,this);this.B=0;var b=this.Da("ytp-upnext-cancel");this.cancelButton=new g.U({I:"button",Ka:["ytp-upnext-cancel-button","ytp-button"],X:{tabindex:"0","aria-label":"Cancel autoplay"},va:"Cancel"});g.P(this,this.cancelButton);this.cancelButton.listen("click",this.m5,this);this.cancelButton.Ha(b);this.cancelButton&&this.api.createClientVe(this.cancelButton.element,
this,115129);g.P(this,this.D);this.api.createClientVe(this.element,this,18788);b=this.Da("ytp-upnext-autoplay-icon");this.T(b,"click",this.n5);this.api.createClientVe(b,this,115130);this.tV();this.T(a,"autonavvisibility",this.tV);this.T(a,"mdxnowautoplaying",this.Iba);this.T(a,"mdxautoplaycanceled",this.Jba);g.up(this.element,"ytp-upnext-mobile",this.api.U().B)},ikb=function(a,b){if(b)return b;
if(a.api.isFullscreen()){var c;a=(c=a.api.getVideoData())==null?void 0:c.VD;return a===-1||a===void 0?8E3:a}return a.api.Yt()>=0?a.api.Yt():g.zD(a.api.U().experiments,"autoplay_time")||1E4},jkb=function(a,b){b=ikb(a,b);
var c=Math,d=c.min;var e=(0,g.S)()-a.B;c=d.call(c,e,b);b=b===0?1:Math.min(c/b,1);a.G.setAttribute("stroke-dashoffset",""+-211*(b+1));b>=1&&a.Ul()&&a.api.getPresentingPlayerType()!==3?a.select(!0):a.Ul()&&a.j.start()},q5=function(a){o5.call(this,a,"autonav-endscreen");
this.overlay=this.videoData=null;this.table=new g.U({I:"div",S:"ytp-suggestion-panel",V:[{I:"div",Ka:["ytp-autonav-endscreen-upnext-header","ytp-autonav-endscreen-more-videos"],va:"More videos"}]});this.N=new g.U({I:"div",S:"ytp-suggestions-container"});this.videos=[];this.C=null;this.G=this.K=!1;this.B=new m5(this.player);g.P(this,this.B);this.B.Ha(this.element);a.getVideoData().Sf?this.j=this.B:(this.j=new p5(a),g.gS(this.player,this.j.element,4),g.P(this,this.j));this.overlay=new g.U({I:"div",
S:"ytp-autonav-overlay-cancelled-state"});g.P(this,this.overlay);this.overlay.Ha(this.element);this.D=new g.PF(this);g.P(this,this.D);g.P(this,this.table);this.table.Ha(this.element);this.table.show();g.P(this,this.N);this.N.Ha(this.table.element);this.hide()},r5=function(a){var b=a.Ef();
b!==a.G&&(a.G=b,a.player.publish("autonavvisibility"),a.G?(a.B!==a.j&&a.B.hide(),a.table.hide()):(a.B!==a.j&&a.B.show(),a.table.show()))},s5=function(a,b){g.U.call(this,{I:"button",
Ka:["ytp-watch-on-youtube-button","ytp-button"],va:"{{content}}"});this.J=a;this.buttonType=this.buttonType=b;this.M2();this.buttonType===2&&g.qp(this.element,"ytp-continue-watching-button");this.listen("click",this.onClick);this.listen("videodatachange",this.M2);g.Ax(this,!0)},t5=function(a,b){o5.call(this,a,"embeds-lite-endscreen");
this.J=a;this.Me=b;this.J.createClientVe(this.element,this,156943);this.watchButton=new s5(a,2);g.P(this,this.watchButton);this.watchButton.Ha(this.element);this.hide()},kkb=function(a){o5.call(this,a,"subscribecard-endscreen");
this.j=new g.U({I:"div",S:"ytp-subscribe-card",V:[{I:"img",S:"ytp-author-image",X:{src:"{{profilePicture}}"}},{I:"div",S:"ytp-subscribe-card-right",V:[{I:"div",S:"ytp-author-name",va:"{{author}}"},{I:"div",S:"html5-subscribe-button-container"}]}]});g.P(this,this.j);this.j.Ha(this.element);var b=a.getVideoData();this.subscribeButton=new g.AY("Subscribe",null,"Unsubscribe",null,!0,!1,b.wm,b.subscribed,"trailer-endscreen",null,a,!1);g.P(this,this.subscribeButton);this.subscribeButton.Ha(this.j.Da("html5-subscribe-button-container"));
this.T(a,"videodatachange",this.Ra);this.Ra();this.hide()},u5=function(a){var b=a.U(),c=g.LF||g.gP?{style:"will-change: opacity"}:void 0,d=b.D,e=["ytp-videowall-still"];
b.B&&e.push("ytp-videowall-show-text");g.U.call(this,{I:"a",Ka:e,X:{href:"{{url}}",target:d?b.W:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},V:[{I:"div",S:"ytp-videowall-still-image",X:{style:"{{background}}"}},{I:"span",S:"ytp-videowall-still-info",X:{"aria-hidden":"true"},V:[{I:"span",S:"ytp-videowall-still-info-bg",V:[{I:"span",S:"ytp-videowall-still-info-content",X:c,V:[{I:"span",S:"ytp-videowall-still-info-title",va:"{{title}}"},
{I:"span",S:"ytp-videowall-still-info-author",va:"{{author_and_views}}"},{I:"span",S:"ytp-videowall-still-info-live",va:"Live"},{I:"span",S:"ytp-videowall-still-info-duration",va:"{{duration}}"}]}]}]},{I:"span",Ka:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],X:{"aria-hidden":"true"},V:[{I:"span",S:"ytp-videowall-still-listlabel-icon"},"Playlist",{I:"span",S:"ytp-videowall-still-listlabel-length",V:[" (",{I:"span",va:"{{playlist_length}}"},")"]}]},{I:"span",Ka:["ytp-videowall-still-listlabel-mix",
"ytp-videowall-still-listlabel"],X:{"aria-hidden":"true"},V:[{I:"span",S:"ytp-videowall-still-listlabel-mix-icon"},"Mix",{I:"span",S:"ytp-videowall-still-listlabel-length",va:" (50+)"}]}]});this.suggestion=null;this.B=d;this.api=a;this.j=new g.PF(this);g.P(this,this.j);this.listen("click",this.onClick);this.listen("keypress",this.onKeyPress);this.j.T(a,"videodatachange",this.onVideoDataChange);a.createServerVe(this.element,this);this.onVideoDataChange()},v5=function(a){o5.call(this,a,"videowall-endscreen");
var b=this;this.J=a;this.C=0;this.stills=[];this.D=this.videoData=null;this.G=this.N=!1;this.W=null;this.B=new g.PF(this);g.P(this,this.B);this.K=new g.ip(function(){g.qp(b.element,"ytp-show-tiles")},0);
g.P(this,this.K);var c=new g.U({I:"button",Ka:["ytp-button","ytp-endscreen-previous"],X:{"aria-label":"Previous"},V:[g.Hx()]});g.P(this,c);c.Ha(this.element);c.listen("click",this.r5,this);this.table=new g.xx({I:"div",S:"ytp-endscreen-content"});g.P(this,this.table);this.table.Ha(this.element);c=new g.U({I:"button",Ka:["ytp-button","ytp-endscreen-next"],X:{"aria-label":"Next"},V:[g.Ix()]});g.P(this,c);c.Ha(this.element);c.listen("click",this.q5,this);a.getVideoData().Sf?this.j=new m5(a,!0):this.j=
new p5(a);g.P(this,this.j);g.gS(this.player,this.j.element,4);a.createClientVe(this.element,this,158789);this.hide()},w5=function(a){return g.BS(a.player)&&a.GE()&&!a.D},x5=function(a){var b=a.Ef();
b!==a.N&&(a.N=b,a.player.publish("autonavvisibility"))},y5=function(a){o5.call(this,a,"watch-again-on-youtube-endscreen");
this.watchButton=new s5(a,1);g.P(this,this.watchButton);this.watchButton.Ha(this.element);g.$9a(a)&&(this.j=new g.c1(a),g.P(this,this.j),this.B=new g.U({I:"div",Ka:["ytp-watch-again-on-youtube-endscreen-more-videos-container"],X:{tabIndex:"-1"},V:[this.j]}),g.P(this,this.B),this.j.Ha(this.B.element),this.B.Ha(this.element));a.createClientVe(this.element,this,156914);this.hide()},okb=function(a){g.UX.call(this,a);
var b=this;this.endScreen=null;this.B=this.j=this.C=this.D=!1;this.listeners=new g.PF(this);g.P(this,this.listeners);var c=a.U(),d=a.getVideoData();d=d&&d.limitedPlaybackDurationInSeconds!==0;g.ts(g.rP(c))&&d&&!g.dS(a)?(this.B=!0,this.endScreen=new t5(a,g.PR(a))):a.bd()?this.endScreen=new y5(a):lkb(a)?(this.D=!0,mkb(this),this.j?this.endScreen=new q5(a):this.endScreen=new v5(a)):c.Dh?this.endScreen=new kkb(a):this.endScreen=new o5(a);g.P(this,this.endScreen);g.gS(a,this.endScreen.element,4);nkb(this);
this.listeners.T(a,"videodatachange",this.onVideoDataChange,this);this.listeners.T(a,g.rE("endscreen"),function(e){b.onCueRangeEnter(e)});
this.listeners.T(a,g.sE("endscreen"),function(e){b.onCueRangeExit(e)})},mkb=function(a){var b=a.player.getVideoData();
if(!b||a.j===b.xm&&a.C===b.Sf)return!1;a.j=b.xm;a.C=b.Sf;return!0},lkb=function(a){a=a.U();
return a.Ad&&!a.Dh},nkb=function(a){a.player.gf("endscreen");
var b=a.player.getVideoData();b=new g.pE(Math.max((b.lengthSeconds-10)*1E3,0),0x8000000000000,{id:"preload",namespace:"endscreen"});var c=new g.pE(0x8000000000000,0x8000000000000,{id:"load",priority:8,namespace:"endscreen"});a.player.lf([b,c])};
g.$R.prototype.Yt=g.da(14,function(){return this.app.Yt()});
g.I_.prototype.Yt=g.da(13,function(){return this.getVideoData().l_});
g.VR.prototype.Ss=g.da(12,function(a){this.Ki().Ss(a)});
g.QY.prototype.Ss=g.da(11,function(a){this.j!==a&&(this.j=a,this.Ra())});
g.YZ.prototype.Ss=g.da(10,function(a){this.overflowButton&&this.overflowButton.Ss(a)});
g.VR.prototype.Ts=g.da(9,function(a){this.Ki().Ts(a)});
g.VY.prototype.Ts=g.da(8,function(a){this.j!==a&&(this.j=a,this.Ra())});
g.YZ.prototype.Ts=g.da(7,function(a){this.shareButton&&this.shareButton.Ts(a)});
g.VR.prototype.EC=g.da(6,function(a){this.Ki().EC(a)});
g.tY.prototype.EC=g.da(5,function(a){this.aT!==a&&(this.aT=a,this.yr())});
g.VR.prototype.DC=g.da(4,function(a){this.Ki().DC(a)});
g.YZ.prototype.DC=g.da(3,function(a){this.ZS!==a&&(this.ZS=a,this.xr())});g.z(l5,g.U);l5.prototype.select=function(){this.J.Gp(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.nF||void 0)&&this.J.logClick(this.element)};
l5.prototype.onClick=function(a){g.US(a,this.J,this.j,this.suggestion.sessionData||void 0)&&this.select()};
l5.prototype.onKeyPress=function(a){switch(a.keyCode){case 13:case 32:a.defaultPrevented||(this.select(),a.preventDefault())}};g.z(m5,g.U);g.k=m5.prototype;g.k.JI=function(a){this.suggestion!==a&&(this.suggestion=a,k5(this.j,a),this.playButton.updateValue("url",this.suggestion.Nl()),n5(this))};
g.k.Ul=function(){return this.C>0};
g.k.OC=function(){this.Ul()||(this.C=Date.now(),ekb(this),ckb(this.J,gkb(this)),g.up(this.J.getRootNode(),"countdown-running",this.Ul()))};
g.k.Jy=function(){this.jr();ekb(this);var a=this.j.Da("ytp-autonav-endscreen-upnext-header");a&&g.qh(a,"Up next")};
g.k.jr=function(){this.Ul()&&(this.D.stop(),this.C=0)};
g.k.select=function(a){this.J.nextVideo(!1,a===void 0?!1:a);this.jr()};
g.k.sV=function(a){g.US(a,this.J)&&(a.currentTarget===this.playButton.element?this.J.logClick(this.playButton.element):a.currentTarget===this.j.Da("ytp-autonav-endscreen-link-container")&&(a=this.j.Da("ytp-autonav-endscreen-link-container"),this.J.logVisibility(a,!0),this.J.logClick(a)),this.J.L("web_player_autonav_next_button_renderer")&&this.G?(this.J.fb("innertubeCommand",this.G),this.jr()):this.select())};
g.k.l5=function(){this.J.logClick(this.cancelButton.element);g.bS(this.J,!0);this.cancelCommand&&this.J.fb("innertubeCommand",this.cancelCommand)};
g.k.onVideoDataChange=function(a,b){this.J.L("web_player_autonav_next_button_renderer")&&dkb(this,b);var c;this.cancelCommand=(c=b.I4)==null?void 0:c.command};
g.k.Taa=function(a){if(hkb(this)){var b=this.J.getVideoData().watchToWatchTransitionRenderer,c=b==null?void 0:b.fromColorPaletteDark;b=b==null?void 0:b.toColorPaletteDark;if(c&&b){var d=this.element;d.style.setProperty("--w2w-start-background-color",g.az(c.surgeColor));d.style.setProperty("--w2w-start-primary-text-color",g.az(c.primaryTitleColor));d.style.setProperty("--w2w-start-secondary-text-color",g.az(c.secondaryTitleColor));d.style.setProperty("--w2w-end-background-color",g.az(b.surgeColor));
d.style.setProperty("--w2w-end-primary-text-color",g.az(b.primaryTitleColor));d.style.setProperty("--w2w-end-secondary-text-color",g.az(b.secondaryTitleColor));d.style.setProperty("--w2w-animation-duration",a+"ms")}g.up(this.element,"ytp-w2w-animate",!0)}};
g.k.k5=function(a){this.J.L("web_autonav_color_transition")&&a!==2&&g.up(this.element,"ytp-w2w-animate",!1)};
g.k.rV=function(){var a=this.J.Ef();this.K&&this.Eb!==a&&g.Ax(this,a);n5(this);this.J.logVisibility(this.container.element,a);this.J.logVisibility(this.cancelButton.element,a);this.J.logVisibility(this.j.Da("ytp-autonav-endscreen-link-container"),a);this.J.logVisibility(this.playButton.element,a)};
g.k.Rg=function(a){return a.width<400||a.height<459};g.z(o5,g.U);g.k=o5.prototype;g.k.create=function(){this.created=!0};
g.k.destroy=function(){this.created=!1};
g.k.GE=function(){return!1};
g.k.Ef=function(){return!1};
g.k.i_=function(){return!1};g.z(p5,g.U);g.k=p5.prototype;g.k.DJ=function(){this.notification&&(this.D.stop(),this.Lc(this.C),this.C=null,this.notification.close(),this.notification=null)};
g.k.JI=function(a){this.suggestion=a;k5(this,a,"hqdefault.jpg")};
g.k.tV=function(){g.Ax(this,this.api.Ef());this.api.logVisibility(this.element,this.api.Ef());this.api.logVisibility(this.Da("ytp-upnext-autoplay-icon"),this.api.Ef());this.cancelButton&&this.api.logVisibility(this.cancelButton.element,this.api.Ef())};
g.k.Rba=function(){window.focus();this.DJ()};
g.k.OC=function(a){var b=this;this.Ul()||(g.xv("a11y-announce","Up Next "+this.suggestion.title),this.B=(0,g.S)(),this.j=new g.ip(function(){jkb(b,a)},25),jkb(this,a),ckb(this.api,ikb(this,a)));
g.sp(this.element,"ytp-upnext-autoplay-paused")};
g.k.hide=function(){g.U.prototype.hide.call(this)};
g.k.Ul=function(){return!!this.j};
g.k.Jy=function(){this.jr();this.B=(0,g.S)();jkb(this);g.qp(this.element,"ytp-upnext-autoplay-paused")};
g.k.jr=function(){this.Ul()&&(this.j.dispose(),this.j=null)};
g.k.select=function(a){a=a===void 0?!1:a;if(this.api.U().L("autonav_notifications")&&a&&window.Notification&&typeof document.hasFocus==="function"){var b=Notification.permission;b==="default"?Notification.requestPermission():b!=="granted"||document.hasFocus()||(this.DJ(),this.notification=new Notification("Up Next",{body:this.suggestion.title,icon:this.suggestion.kh()}),this.C=this.T(this.notification,"click",this.Rba),this.D.start())}this.jr();this.api.nextVideo(!1,a)};
g.k.n5=function(a){!g.ph(this.cancelButton.element,a.target)&&g.US(a,this.api)&&(this.api.Ef()&&this.api.logClick(this.Da("ytp-upnext-autoplay-icon")),this.select())};
g.k.m5=function(){this.api.Ef()&&this.cancelButton&&this.api.logClick(this.cancelButton.element);g.bS(this.api,!0)};
g.k.Iba=function(a){this.api.getPresentingPlayerType();this.show();this.OC(a)};
g.k.Jba=function(){this.api.getPresentingPlayerType();this.jr();this.hide()};
g.k.xa=function(){this.jr();this.DJ();g.U.prototype.xa.call(this)};g.z(q5,o5);g.k=q5.prototype;g.k.create=function(){o5.prototype.create.call(this);this.D.T(this.player,"appresize",this.zD);this.D.T(this.player,"onVideoAreaChange",this.zD);this.D.T(this.player,"videodatachange",this.onVideoDataChange);this.D.T(this.player,"autonavchange",this.uV);this.D.T(this.player,"onAutonavCancelled",this.o5);this.onVideoDataChange()};
g.k.show=function(){o5.prototype.show.call(this);(this.K||this.C&&this.C!==this.videoData.clientPlaybackNonce)&&g.bS(this.player,!1);g.BS(this.player)&&this.GE()&&!this.C?(r5(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3?this.j.select(!0):this.j.OC():this.videoData.autonavState===3&&this.j.Jy()):(g.bS(this.player,!0),r5(this));this.zD()};
g.k.hide=function(){o5.prototype.hide.call(this);this.j.Jy();r5(this)};
g.k.zD=function(){var a=this.player.Fo(!0,this.player.isFullscreen());r5(this);n5(this.B);g.up(this.element,"ytp-autonav-cancelled-small-mode",this.Rg(a));g.up(this.element,"ytp-autonav-cancelled-tiny-mode",this.fL(a));g.up(this.element,"ytp-autonav-cancelled-mini-mode",a.width<=400||a.height<=360);this.overlay&&g.xm(this.overlay.element,{width:a.width+"px"});if(!this.G)for(a=0;a<this.videos.length;a++)g.up(this.videos[a].element,"ytp-suggestion-card-with-margin",a%2===1)};
g.k.onVideoDataChange=function(){var a=this.player.getVideoData();if(this.videoData!==a&&a){this.videoData=a;if((a=this.videoData.suggestions)&&a.length||this.player.L("web_player_autonav_empty_suggestions_fix")){var b=g.PQ(this.videoData);b&&(this.j.JI(b),this.j!==this.B&&this.B.JI(b))}if(a&&a.length)for(b=0;b<pkb.length;++b){var c=pkb[b];if(a&&a[c]){this.videos[b]=new l5(this.player);var d=this.videos[b];c=a[c];d.suggestion!==c&&(d.suggestion=c,k5(d,c));g.P(this,this.videos[b]);this.videos[b].Ha(this.N.element)}}this.zD()}};
g.k.uV=function(a){a===1?(this.K=!1,this.C=this.videoData.clientPlaybackNonce,this.j.jr(),this.Eb&&this.zD()):(this.K=!0,this.Ef()&&(a===2?this.j.OC():a===3&&this.j.Jy()))};
g.k.o5=function(a){a?this.uV(1):(this.C=null,this.K=!1)};
g.k.GE=function(){return this.videoData.autonavState!==1};
g.k.Rg=function(a){return(a.width<910||a.height<459)&&!this.fL(a)&&!(a.width<=400||a.height<=360)};
g.k.fL=function(a){return a.width<800&&!(a.width<=400||a.height<=360)};
g.k.Ef=function(){return this.Eb&&g.BS(this.player)&&this.GE()&&!this.C};
var pkb=[1,3,2,4];g.z(s5,g.U);g.k=s5.prototype;g.k.M2=function(){switch(this.buttonType){case 1:var a="Watch again on YouTube";var b=156915;break;case 2:a="Continue watching on YouTube";b=156942;break;default:a="Continue watching on YouTube",b=156942}this.update({content:a});this.J.hasVe(this.element)&&this.J.destroyVe(this.element);this.J.createClientVe(this.element,this,b)};
g.k.onClick=function(a){this.J.L("web_player_log_click_before_generating_ve_conversion_params")&&this.J.logClick(this.element);g.VS(this.getVideoUrl(),this.J,a);this.J.L("web_player_log_click_before_generating_ve_conversion_params")||this.J.logClick(this.element)};
g.k.getVideoUrl=function(){var a=!0;switch(this.buttonType){case 1:a=!0;break;case 2:a=!1}a=this.J.getVideoUrl(a,!1,!1,!0);var b=this.J.U();if(g.iP(b)){var c={};g.iP(b)&&g.KR(this.J,"addEmbedsConversionTrackingParams",[c]);a=g.$i(a,c)}return a};
g.k.logVisibility=function(){this.J.logVisibility(this.element,this.Eb&&this.Z)};
g.k.show=function(){g.U.prototype.show.call(this);this.logVisibility()};
g.k.hide=function(){g.U.prototype.hide.call(this);this.logVisibility()};
g.k.Kc=function(a){g.U.prototype.Kc.call(this,a);this.logVisibility()};g.z(t5,o5);t5.prototype.show=function(){this.player.getPlayerState()!==3&&(o5.prototype.show.call(this),this.Me.DC(!0),this.Me.Ts(!0),this.J.U().ge||this.Me.Ss(!0),this.J.logVisibility(this.element,!0),this.watchButton.Kc(!0))};
t5.prototype.hide=function(){o5.prototype.hide.call(this);this.Me.DC(!1);this.Me.Ts(!1);this.Me.Ss(!1);this.J.logVisibility(this.element,!1);this.watchButton.Kc(!1)};g.z(kkb,o5);kkb.prototype.Ra=function(){var a=this.player.getVideoData();this.j.update({profilePicture:a.profilePicture,author:a.author});this.subscribeButton.channelId=a.wm;var b=this.subscribeButton;a.subscribed?b.j():b.B()};g.z(u5,g.U);u5.prototype.select=function(){this.api.Gp(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.nF||void 0)&&this.api.logClick(this.element)};
u5.prototype.onClick=function(a){if(g.iP(this.api.U())&&this.api.L("web_player_log_click_before_generating_ve_conversion_params")){this.api.logClick(this.element);var b=this.suggestion.Nl(),c={};g.DMa(this.api,c);b=g.$i(b,c);g.VS(b,this.api,a)}else g.US(a,this.api,this.B,this.suggestion.sessionData||void 0)&&this.select()};
u5.prototype.onKeyPress=function(a){switch(a.keyCode){case 13:case 32:a.defaultPrevented||(this.select(),a.preventDefault())}};
u5.prototype.onVideoDataChange=function(){var a=this.api.getVideoData(),b=this.api.U();this.B=a.Gf?!1:b.D};g.z(v5,o5);g.k=v5.prototype;g.k.create=function(){o5.prototype.create.call(this);var a=this.player.getVideoData();a&&(this.videoData=a);this.Cr();this.B.T(this.player,"appresize",this.Cr);this.B.T(this.player,"onVideoAreaChange",this.Cr);this.B.T(this.player,"videodatachange",this.onVideoDataChange);this.B.T(this.player,"autonavchange",this.JN);this.B.T(this.player,"onAutonavCancelled",this.p5);a=this.videoData.autonavState;a!==this.W&&this.JN(a);this.B.T(this.element,"transitionend",this.gda)};
g.k.destroy=function(){g.Ms(this.B);g.og(this.stills);this.stills=[];o5.prototype.destroy.call(this);g.sp(this.element,"ytp-show-tiles");this.K.stop();this.W=this.videoData.autonavState};
g.k.GE=function(){return this.videoData.autonavState!==1};
g.k.show=function(){var a=this.Eb;o5.prototype.show.call(this);g.sp(this.element,"ytp-show-tiles");this.player.U().B?g.kp(this.K):this.K.start();(this.G||this.D&&this.D!==this.videoData.clientPlaybackNonce)&&g.bS(this.player,!1);w5(this)?(x5(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3?this.j.select(!0):this.j.OC():this.videoData.autonavState===3&&this.j.Jy()):(g.bS(this.player,!0),x5(this));a!==this.Eb&&this.player.logVisibility(this.element,!0)};
g.k.hide=function(){var a=this.Eb;o5.prototype.hide.call(this);this.j.Jy();x5(this);a!==this.Eb&&this.player.logVisibility(this.element,!1)};
g.k.gda=function(a){a.target===this.element&&this.Cr()};
g.k.Cr=function(){var a,b,c,d;var e=((a=this.videoData)==null?0:(b=a.suggestions)==null?0:b.length)?(c=this.videoData)==null?void 0:c.suggestions:[(d=this.videoData)==null?void 0:g.PQ(d)];if(e.length){g.qp(this.element,"ytp-endscreen-paginate");var f=this.J.Fo(!0,this.J.isFullscreen());if(a=g.PR(this.J))a=a.Nh()?48:32,f.width-=a*2;var h=f.width/f.height;d=96/54;b=a=2;var l=Math.max(f.width/96,2),m=Math.max(f.height/54,2);c=e.length;var n=c*4;for(n-=4;n>0&&(a<l||b<m);){var p=a/2,q=b/2,r=a<=l-2&&n>=
q*4,t=b<=m-2&&n>=p*4;if((p+1)/q*d/h>h/(p/(q+1)*d)&&t)n-=p*4,b+=2;else if(r)n-=q*4,a+=2;else if(t)n-=p*4,b+=2;else break}d=!1;n>=12&&c*4-n<=6&&(b>=4||a>=4)&&(d=!0);n=a*96;l=b*54;h=n/l<h?f.height/l:f.width/n;h=Math.min(h,2);n=Math.floor(Math.min(f.width,n*h));l=Math.floor(Math.min(f.height,l*h));f=this.table.element;f.ariaLive="polite";g.Im(f,n,l);g.xm(f,{marginLeft:n/-2+"px",marginTop:l/-2+"px"});this.j.JI(g.PQ(this.videoData));this.j instanceof m5&&n5(this.j);g.up(this.element,"ytp-endscreen-takeover",
w5(this));x5(this);n+=4;l+=4;h=0;f.ariaBusy="true";for(m=0;m<a;m++)for(p=0;p<b;p++)if(q=h,t=0,d&&m>=a-2&&p>=b-2?t=1:p%2===0&&m%2===0&&(p<2&&m<2?p===0&&m===0&&(t=2):t=2),q=g.yg(q+this.C,c),t!==0){r=this.stills[h];r||(r=new u5(this.player),this.stills[h]=r,f.appendChild(r.element));var u=Math.floor(l*p/b),y=Math.floor(n*m/a),A=Math.floor(l*(p+t)/b)-u-4,C=Math.floor(n*(m+t)/a)-y-4;g.Em(r.element,y,u);g.Im(r.element,C,A);g.xm(r.element,"transitionDelay",(p+m)/20+"s");g.up(r.element,"ytp-videowall-still-mini",
t===1);g.up(r.element,"ytp-videowall-still-large",t>2);t=Math.max(C,A);g.up(r.element,"ytp-videowall-still-round-large",t>=256);g.up(r.element,"ytp-videowall-still-round-medium",t>96&&t<256);g.up(r.element,"ytp-videowall-still-round-small",t<=96);q=e[q];r.suggestion!==q&&(r.suggestion=q,t=r.api.U(),u=g.pp(r.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",k5(r,q,u),g.iP(t)&&!r.api.L("web_player_log_click_before_generating_ve_conversion_params")&&(t=q.Nl(),u={},g.KR(r.api,"addEmbedsConversionTrackingParams",
[u]),t=g.$i(t,u),r.updateValue("url",t)),(q=(q=q.sessionData)&&q.itct)&&r.api.setTrackingParams(r.element,q));h++}f.ariaBusy="false";g.up(this.element,"ytp-endscreen-paginate",h<c);for(e=this.stills.length-1;e>=h;e--)a=this.stills[e],g.oh(a.element),g.ng(a);this.stills.length=h}};
g.k.onVideoDataChange=function(){var a=this.player.getVideoData(1);this.videoData!==a&&(a!=null&&g.PQ(a)?(this.C=0,this.videoData=a,this.Cr()):this.player.ma("missg",{vid:(a==null?void 0:a.videoId)||"",cpn:(a==null?void 0:a.clientPlaybackNonce)||""}))};
g.k.q5=function(){this.C+=this.stills.length;this.Cr()};
g.k.r5=function(){this.C-=this.stills.length;this.Cr()};
g.k.i_=function(){return this.j.Ul()};
g.k.JN=function(a){a===1?(this.G=!1,this.D=this.videoData.clientPlaybackNonce,this.j.jr(),this.Eb&&this.Cr()):(this.G=!0,this.Eb&&w5(this)&&(a===2?this.j.OC():a===3&&this.j.Jy()))};
g.k.p5=function(a){if(a){for(a=0;a<this.stills.length;a++)this.J.logVisibility(this.stills[a].element,!0);this.JN(1)}else this.D=null,this.G=!1;this.Cr()};
g.k.Ef=function(){return this.Eb&&w5(this)};g.z(y5,o5);y5.prototype.show=function(){if(this.player.getPlayerState()!==3){o5.prototype.show.call(this);var a=this.B;if(a){var b=this.j.suggestionData.length>0;g.up(this.element,"ytp-shorts-branded-ui",b);b?a.show():a.hide()}var c;(c=g.PR(this.player))==null||c.EC(!0);this.player.logVisibility(this.element,!0);this.watchButton.Kc(!0)}};
y5.prototype.hide=function(){o5.prototype.hide.call(this);var a;(a=g.PR(this.player))==null||a.EC(!1);this.player.logVisibility(this.element,!1);this.watchButton.Kc(!1)};g.z(okb,g.UX);g.k=okb.prototype;g.k.Dv=function(){var a=this.player.getVideoData(),b=a.mutedAutoplay;if((this.player.bd()||this.B)&&!b)return!0;var c;var d=!!((a==null?0:g.PQ(a))||(a==null?0:(c=a.suggestions)==null?0:c.length));d=!lkb(this.player)||d;a=a.Pj;c=this.player.AF();return d&&!a&&!c&&!b};
g.k.Ef=function(){return this.endScreen.Ef()};
g.k.F$=function(){return this.Ef()?this.endScreen.i_():!1};
g.k.xa=function(){this.player.gf("endscreen");g.UX.prototype.xa.call(this)};
g.k.load=function(){var a=this.player.getVideoData();var b=a.transitionEndpointAtEndOfStream;if(b&&b.videoId){var c=this.player.yb().He.get("heartbeat"),d=g.PQ(a);!d||b.videoId!==d.videoId||a.RW?(this.player.Gp(b.videoId,void 0,void 0,!0,!0,b),c&&c.oL("HEARTBEAT_ACTION_TRIGGER_AT_STREAM_END","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT"),a=!0):a=!1}else a=!1;a||(g.UX.prototype.load.call(this),this.endScreen.show())};
g.k.unload=function(){g.UX.prototype.unload.call(this);this.endScreen.hide();this.endScreen.destroy()};
g.k.onCueRangeEnter=function(a){this.Dv()&&(this.endScreen.created||this.endScreen.create(),a.getId()==="load"&&this.load())};
g.k.onCueRangeExit=function(a){a.getId()==="load"&&this.loaded&&this.unload()};
g.k.onVideoDataChange=function(){nkb(this);this.D&&mkb(this)&&(this.endScreen&&(this.endScreen.hide(),this.endScreen.created&&this.endScreen.destroy(),this.endScreen.dispose()),this.j?this.endScreen=new q5(this.player):this.endScreen=new v5(this.player),g.P(this,this.endScreen),g.gS(this.player,this.endScreen.element,4))};g.TX("endscreen",okb);})(_yt_player);
