(function(g){var window=this;'use strict';var M5=function(a,b){g.U.call(this,{I:"button",Ka:["ytp-miniplayer-expand-watch-page-button","ytp-button","ytp-miniplayer-button-top-left"],X:{title:"{{title}}","data-tooltip-target-id":"ytp-miniplayer-expand-watch-page-button","aria-keyshortcuts":"i","data-title-no-tooltip":"{{data-title-no-tooltip}}"},V:[{I:"svg",X:{height:"24px",version:"1.1",viewBox:"0 0 24 24",width:"24px"},V:[{I:"g",X:{fill:"none","fill-rule":"evenodd",stroke:"none","stroke-width":"1"},V:[{I:"g",X:{transform:"translate(12.000000, 12.000000) scale(-1, 1) translate(-12.000000, -12.000000) "},
V:[{I:"path",X:{d:"M19,19 L5,19 L5,5 L12,5 L12,3 L5,3 C3.89,3 3,3.9 3,5 L3,19 C3,20.1 3.89,21 5,21 L19,21 C20.1,21 21,20.1 21,19 L21,12 L19,12 L19,19 Z M14,3 L14,5 L17.59,5 L7.76,14.83 L9.17,16.24 L19,6.41 L19,10 L21,10 L21,3 L14,3 Z",fill:"#fff","fill-rule":"nonzero"}}]}]}]}]});this.J=a;this.listen("click",this.onClick,this);this.updateValue("title",g.ZR(a,"Expand","i"));this.update({"data-title-no-tooltip":"Expand"});this.addOnDisposeCallback(g.WR(b.Qe(),this.element))},mlb=function(a){g.U.call(this,
{I:"div",
S:"ytp-miniplayer-ui"});this.N=this.G=!1;this.player=a;this.T(a,"minimized",this.wh);this.T(a,"onStateChange",this.afa);this.T(a,"documentpictureinpicturechange",this.nba)},nlb=function(a,b){g.up(a.player.getRootNode(),"ytp-player-minimized",b);
a.player.L("web_cairo_modern_miniplayer")&&g.up(a.player.getRootNode(),"ytp-modern-miniplayer",b);a.player.L("web_cairo_modern_miniplayer_inset_progress_bar")&&g.up(a.player.getRootNode(),"ytp-miniplayer-alternate-ui",b)},olb=function(a){var b=a.player.ob().getPlayerSize().width,c=0,d=b;
if(a.player.L("web_cairo_modern_miniplayer")&&!a.N&&!a.player.L("web_cairo_modern_miniplayer_infobar")||a.player.L("web_cairo_modern_miniplayer_inset_progress_bar"))c=12,d=b-24;g.C3a(a.progressBar,c,d,!1);g.nZ(a.progressBar)},plb=function(a){g.UX.call(this,a);
this.B=new g.PF(this);this.j=new mlb(this.player);this.j.hide();g.gS(this.player,this.j.element,4);a.isMinimized()&&(this.load(),g.up(a.getRootNode(),"ytp-player-minimized",!0))};
g.z(M5,g.U);M5.prototype.onClick=function(){this.J.fb("onExpandMiniplayer")};g.z(mlb,g.U);g.k=mlb.prototype;
g.k.show=function(){this.j=new g.hp(this.w5,null,this);this.j.start();if(!this.G){this.tooltip=new g.XZ(this.player,this);g.P(this,this.tooltip);g.gS(this.player,this.tooltip.element,4);this.tooltip.scale=.6;this.je=new g.wY(this.player);g.P(this,this.je);this.progressBar=new g.mZ(this.player,this);g.P(this,this.progressBar);g.gS(this.player,this.progressBar.element,4);this.player.L("web_cairo_modern_miniplayer_infobar")&&g.qp(this.player.getRootNode(),"ytp-always-showing-infobar");this.B=new g.U({I:"div",
S:"ytp-miniplayer-scrim"});g.P(this,this.B);this.B.Ha(this.element);this.T(this.B.element,"click",this.S0);var a=new g.U({I:"button",Ka:["ytp-miniplayer-close-button","ytp-button"],X:{"aria-label":"Close"},V:[g.Jx()]});g.P(this,a);a.Ha(this.B.element);this.T(a.element,"click",this.wV);a=new M5(this.player,this);g.P(this,a);a.Ha(this.B.element);this.C=new g.U({I:"div",S:"ytp-miniplayer-controls"});g.P(this,this.C);this.C.Ha(this.B.element);this.player.L("web_cairo_modern_miniplayer")||this.T(this.C.element,
"click",this.S0);var b=new g.U({I:"div",S:"ytp-miniplayer-button-container"});g.P(this,b);b.Ha(this.C.element);a=new g.U({I:"div",S:"ytp-miniplayer-play-button-container"});g.P(this,a);a.Ha(this.C.element);var c=new g.U({I:"div",S:"ytp-miniplayer-button-container"});g.P(this,c);c.Ha(this.C.element);this.W=new g.hZ(this.player,this,!1);g.P(this,this.W);this.W.Ha(b.element);b=new g.gZ(this.player,this);g.P(this,b);b.Ha(a.element);this.nextButton=new g.hZ(this.player,this,!0);g.P(this,this.nextButton);
this.nextButton.Ha(c.element);this.K=this.player.L("web_cairo_modern_miniplayer")?new g.QZ(this.player,this,0):new g.QZ(this.player,this);g.P(this,this.K);this.K.Ha(this.B.element);this.D=new g.U({I:"div",S:"ytp-miniplayer-buttons"});g.P(this,this.D);g.gS(this.player,this.D.element,4);a=new g.U({I:"button",Ka:["ytp-miniplayer-close-button","ytp-button"],X:{"aria-label":"Close"},V:[g.Jx()]});g.P(this,a);a.Ha(this.D.element);this.T(a.element,"click",this.wV);a=new g.U({I:"button",Ka:["ytp-miniplayer-replay-button",
"ytp-button"],X:{"aria-label":"Close"},V:[g.Px()]});g.P(this,a);a.Ha(this.D.element);this.T(a.element,"click",this.tca);this.player.L("web_cairo_modern_miniplayer")&&(a=new M5(this.player,this),g.P(this,a),a.Ha(this.D.element));this.T(this.player,"presentingplayerstatechange",this.x5);this.T(this.player,"appresize",this.jc);this.T(this.player,"fullscreentoggled",this.jc);this.player.L("web_cairo_modern_miniplayer")&&this.T(this.player,"onPlaylistUpdate",this.IS);this.jc();this.G=!0}this.player.getPlayerState()!==
0&&g.U.prototype.show.call(this);this.progressBar.show();this.player.unloadModule("annotations_module")};
g.k.hide=function(){this.j&&(this.j.dispose(),this.j=void 0);g.U.prototype.hide.call(this);this.player.isMinimized()||(this.G&&this.progressBar.hide(),this.player.loadModule("annotations_module"))};
g.k.xa=function(){this.j&&(this.j.dispose(),this.j=void 0);g.U.prototype.xa.call(this)};
g.k.wV=function(){this.player.stopVideo();this.player.fb("onCloseMiniplayer")};
g.k.tca=function(){this.player.playVideo()};
g.k.S0=function(a){if(a.target===this.B.element||a.target===this.C.element)this.player.getPlayerStateObject().isOrWillBePlaying()?this.player.pauseVideo():this.player.playVideo()};
g.k.wh=function(){nlb(this,this.player.isMinimized());this.player.L("web_cairo_modern_miniplayer")&&this.IS()};
g.k.nba=function(){nlb(this,this.player.ej());this.player.L("web_cairo_modern_miniplayer")&&this.IS();g.up(this.player.getRootNode(),"ytp-player-document-picture-in-picture",this.player.ej())};
g.k.Dg=function(){this.progressBar.Rc();this.K.Rc()};
g.k.w5=function(){this.Dg();this.j&&this.j.start()};
g.k.x5=function(a){g.Z(a.state,32)&&this.tooltip.hide()};
g.k.IS=function(){this.N=(this.player.isMinimized()||this.player.ej())&&!!this.player.getPlaylist();g.up(this.player.getRootNode(),"ytp-has-playlist-data",this.N);olb(this)};
g.k.jc=function(){olb(this)};
g.k.afa=function(a){this.player.isMinimized()&&(a===0?this.hide():this.show())};
g.k.Qe=function(){return this.tooltip};
g.k.Ly=function(a,b,c,d,e){var f=0,h=0,l=0,m=g.Jm(a);d=b&&(g.pp(b,"ytp-prev-button")||g.pp(b,"ytp-next-button"));if(b){c=g.pp(b,"ytp-play-button");var n=g.pp(b,"ytp-miniplayer-expand-watch-page-button");d?f=l=12:c?(b=g.Hm(b,this.element),l=b.x,f=b.y-12):n&&(l=g.pp(b,"ytp-miniplayer-button-top-left"),f=g.Hm(b,this.element),b=g.Jm(b),l?(l=8,f=f.y+40):(l=f.x-m.width+b.width,f=f.y-20))}else l=c-m.width/2,h=25+(e||0);b=this.player.ob().getPlayerSize();e=f+(e||0);m=g.xg(l,0,b.width-m.width-12);e?(a.style.top=
e+"px",a.style.bottom=""):(a.style.top="",a.style.bottom=h+"px");a.style.left=m+"px";this.player.L("web_cairo_modern_miniplayer")&&(h=g.pp(a,"ytp-preview"),a.style.visibility=d&&h&&b.height<225?"hidden":"")};g.z(plb,g.UX);g.k=plb.prototype;g.k.onVideoDataChange=function(){if(this.player.getVideoData()){var a=this.player.getVideoAspectRatio(),b=16/9;a=a>b+.1||a<b-.1;g.up(this.player.getRootNode(),"ytp-rounded-miniplayer-not-regular-wide-video",a)}};
g.k.create=function(){g.UX.prototype.create.call(this);this.B.T(this.player,"videodatachange",this.onVideoDataChange);this.onVideoDataChange()};
g.k.En=function(){return!1};
g.k.load=function(){this.player.hideControls();this.j.show()};
g.k.unload=function(){this.player.showControls();this.j.hide()};g.TX("miniplayer",plb);})(_yt_player);
